// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package payment

import (
	"context"

	"github.com/google/uuid"
	"github.com/residwi/go-api-project-template/internal/features/inventory"
	"github.com/residwi/go-api-project-template/internal/features/order"
	"github.com/residwi/go-api-project-template/internal/features/payment/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockGateway creates a new instance of MockGateway. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGateway(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGateway {
	mock := &MockGateway{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGateway is an autogenerated mock type for the Gateway type
type MockGateway struct {
	mock.Mock
}

type MockGateway_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGateway) EXPECT() *MockGateway_Expecter {
	return &MockGateway_Expecter{mock: &_m.Mock}
}

// Charge provides a mock function for the type MockGateway
func (_mock *MockGateway) Charge(ctx context.Context, req GatewayChargeRequest) (GatewayChargeResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Charge")
	}

	var r0 GatewayChargeResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, GatewayChargeRequest) (GatewayChargeResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, GatewayChargeRequest) GatewayChargeResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Get(0).(GatewayChargeResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, GatewayChargeRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGateway_Charge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Charge'
type MockGateway_Charge_Call struct {
	*mock.Call
}

// Charge is a helper method to define mock.On call
//   - ctx context.Context
//   - req GatewayChargeRequest
func (_e *MockGateway_Expecter) Charge(ctx any, req any) *MockGateway_Charge_Call {
	return &MockGateway_Charge_Call{Call: _e.mock.On("Charge", ctx, req)}
}

func (_c *MockGateway_Charge_Call) Run(run func(ctx context.Context, req GatewayChargeRequest)) *MockGateway_Charge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 GatewayChargeRequest
		if args[1] != nil {
			arg1 = args[1].(GatewayChargeRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGateway_Charge_Call) Return(gatewayChargeResponse GatewayChargeResponse, err error) *MockGateway_Charge_Call {
	_c.Call.Return(gatewayChargeResponse, err)
	return _c
}

func (_c *MockGateway_Charge_Call) RunAndReturn(run func(ctx context.Context, req GatewayChargeRequest) (GatewayChargeResponse, error)) *MockGateway_Charge_Call {
	_c.Call.Return(run)
	return _c
}

// Refund provides a mock function for the type MockGateway
func (_mock *MockGateway) Refund(ctx context.Context, req GatewayRefundRequest) (GatewayRefundResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Refund")
	}

	var r0 GatewayRefundResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, GatewayRefundRequest) (GatewayRefundResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, GatewayRefundRequest) GatewayRefundResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Get(0).(GatewayRefundResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, GatewayRefundRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGateway_Refund_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Refund'
type MockGateway_Refund_Call struct {
	*mock.Call
}

// Refund is a helper method to define mock.On call
//   - ctx context.Context
//   - req GatewayRefundRequest
func (_e *MockGateway_Expecter) Refund(ctx any, req any) *MockGateway_Refund_Call {
	return &MockGateway_Refund_Call{Call: _e.mock.On("Refund", ctx, req)}
}

func (_c *MockGateway_Refund_Call) Run(run func(ctx context.Context, req GatewayRefundRequest)) *MockGateway_Refund_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 GatewayRefundRequest
		if args[1] != nil {
			arg1 = args[1].(GatewayRefundRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGateway_Refund_Call) Return(gatewayRefundResponse GatewayRefundResponse, err error) *MockGateway_Refund_Call {
	_c.Call.Return(gatewayRefundResponse, err)
	return _c
}

func (_c *MockGateway_Refund_Call) RunAndReturn(run func(ctx context.Context, req GatewayRefundRequest) (GatewayRefundResponse, error)) *MockGateway_Refund_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockJobQueue creates a new instance of MockJobQueue. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJobQueue(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJobQueue {
	mock := &MockJobQueue{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockJobQueue is an autogenerated mock type for the JobQueue type
type MockJobQueue struct {
	mock.Mock
}

type MockJobQueue_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJobQueue) EXPECT() *MockJobQueue_Expecter {
	return &MockJobQueue_Expecter{mock: &_m.Mock}
}

// CancelPendingForOrder provides a mock function for the type MockJobQueue
func (_mock *MockJobQueue) CancelPendingForOrder(ctx context.Context, orderID uuid.UUID) error {
	ret := _mock.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for CancelPendingForOrder")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, orderID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockJobQueue_CancelPendingForOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelPendingForOrder'
type MockJobQueue_CancelPendingForOrder_Call struct {
	*mock.Call
}

// CancelPendingForOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID uuid.UUID
func (_e *MockJobQueue_Expecter) CancelPendingForOrder(ctx any, orderID any) *MockJobQueue_CancelPendingForOrder_Call {
	return &MockJobQueue_CancelPendingForOrder_Call{Call: _e.mock.On("CancelPendingForOrder", ctx, orderID)}
}

func (_c *MockJobQueue_CancelPendingForOrder_Call) Run(run func(ctx context.Context, orderID uuid.UUID)) *MockJobQueue_CancelPendingForOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockJobQueue_CancelPendingForOrder_Call) Return(err error) *MockJobQueue_CancelPendingForOrder_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockJobQueue_CancelPendingForOrder_Call) RunAndReturn(run func(ctx context.Context, orderID uuid.UUID) error) *MockJobQueue_CancelPendingForOrder_Call {
	_c.Call.Return(run)
	return _c
}

// EnqueueRefund provides a mock function for the type MockJobQueue
func (_mock *MockJobQueue) EnqueueRefund(ctx context.Context, paymentID uuid.UUID, orderID uuid.UUID) error {
	ret := _mock.Called(ctx, paymentID, orderID)

	if len(ret) == 0 {
		panic("no return value specified for EnqueueRefund")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, paymentID, orderID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockJobQueue_EnqueueRefund_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnqueueRefund'
type MockJobQueue_EnqueueRefund_Call struct {
	*mock.Call
}

// EnqueueRefund is a helper method to define mock.On call
//   - ctx context.Context
//   - paymentID uuid.UUID
//   - orderID uuid.UUID
func (_e *MockJobQueue_Expecter) EnqueueRefund(ctx any, paymentID any, orderID any) *MockJobQueue_EnqueueRefund_Call {
	return &MockJobQueue_EnqueueRefund_Call{Call: _e.mock.On("EnqueueRefund", ctx, paymentID, orderID)}
}

func (_c *MockJobQueue_EnqueueRefund_Call) Run(run func(ctx context.Context, paymentID uuid.UUID, orderID uuid.UUID)) *MockJobQueue_EnqueueRefund_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockJobQueue_EnqueueRefund_Call) Return(err error) *MockJobQueue_EnqueueRefund_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockJobQueue_EnqueueRefund_Call) RunAndReturn(run func(ctx context.Context, paymentID uuid.UUID, orderID uuid.UUID) error) *MockJobQueue_EnqueueRefund_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOrders creates a new instance of MockOrders. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrders(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrders {
	mock := &MockOrders{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOrders is an autogenerated mock type for the Orders type
type MockOrders struct {
	mock.Mock
}

type MockOrders_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrders) EXPECT() *MockOrders_Expecter {
	return &MockOrders_Expecter{mock: &_m.Mock}
}

// CancelUnpaid provides a mock function for the type MockOrders
func (_mock *MockOrders) CancelUnpaid(ctx context.Context, orderID uuid.UUID) error {
	ret := _mock.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for CancelUnpaid")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, orderID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOrders_CancelUnpaid_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelUnpaid'
type MockOrders_CancelUnpaid_Call struct {
	*mock.Call
}

// CancelUnpaid is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID uuid.UUID
func (_e *MockOrders_Expecter) CancelUnpaid(ctx any, orderID any) *MockOrders_CancelUnpaid_Call {
	return &MockOrders_CancelUnpaid_Call{Call: _e.mock.On("CancelUnpaid", ctx, orderID)}
}

func (_c *MockOrders_CancelUnpaid_Call) Run(run func(ctx context.Context, orderID uuid.UUID)) *MockOrders_CancelUnpaid_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrders_CancelUnpaid_Call) Return(err error) *MockOrders_CancelUnpaid_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOrders_CancelUnpaid_Call) RunAndReturn(run func(ctx context.Context, orderID uuid.UUID) error) *MockOrders_CancelUnpaid_Call {
	_c.Call.Return(run)
	return _c
}

// FulfilmentSnapshot provides a mock function for the type MockOrders
func (_mock *MockOrders) FulfilmentSnapshot(ctx context.Context, orderID uuid.UUID) (order.FulfilmentSnapshot, error) {
	ret := _mock.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for FulfilmentSnapshot")
	}

	var r0 order.FulfilmentSnapshot
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (order.FulfilmentSnapshot, error)); ok {
		return returnFunc(ctx, orderID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) order.FulfilmentSnapshot); ok {
		r0 = returnFunc(ctx, orderID)
	} else {
		r0 = ret.Get(0).(order.FulfilmentSnapshot)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, orderID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrders_FulfilmentSnapshot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FulfilmentSnapshot'
type MockOrders_FulfilmentSnapshot_Call struct {
	*mock.Call
}

// FulfilmentSnapshot is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID uuid.UUID
func (_e *MockOrders_Expecter) FulfilmentSnapshot(ctx any, orderID any) *MockOrders_FulfilmentSnapshot_Call {
	return &MockOrders_FulfilmentSnapshot_Call{Call: _e.mock.On("FulfilmentSnapshot", ctx, orderID)}
}

func (_c *MockOrders_FulfilmentSnapshot_Call) Run(run func(ctx context.Context, orderID uuid.UUID)) *MockOrders_FulfilmentSnapshot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrders_FulfilmentSnapshot_Call) Return(fulfilmentSnapshot order.FulfilmentSnapshot, err error) *MockOrders_FulfilmentSnapshot_Call {
	_c.Call.Return(fulfilmentSnapshot, err)
	return _c
}

func (_c *MockOrders_FulfilmentSnapshot_Call) RunAndReturn(run func(ctx context.Context, orderID uuid.UUID) (order.FulfilmentSnapshot, error)) *MockOrders_FulfilmentSnapshot_Call {
	_c.Call.Return(run)
	return _c
}

// ListItemQuantities provides a mock function for the type MockOrders
func (_mock *MockOrders) ListItemQuantities(ctx context.Context, orderID uuid.UUID) (map[uuid.UUID]int, error) {
	ret := _mock.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for ListItemQuantities")
	}

	var r0 map[uuid.UUID]int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (map[uuid.UUID]int, error)); ok {
		return returnFunc(ctx, orderID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) map[uuid.UUID]int); ok {
		r0 = returnFunc(ctx, orderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[uuid.UUID]int)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, orderID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrders_ListItemQuantities_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListItemQuantities'
type MockOrders_ListItemQuantities_Call struct {
	*mock.Call
}

// ListItemQuantities is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID uuid.UUID
func (_e *MockOrders_Expecter) ListItemQuantities(ctx any, orderID any) *MockOrders_ListItemQuantities_Call {
	return &MockOrders_ListItemQuantities_Call{Call: _e.mock.On("ListItemQuantities", ctx, orderID)}
}

func (_c *MockOrders_ListItemQuantities_Call) Run(run func(ctx context.Context, orderID uuid.UUID)) *MockOrders_ListItemQuantities_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrders_ListItemQuantities_Call) Return(uUIDToInt map[uuid.UUID]int, err error) *MockOrders_ListItemQuantities_Call {
	_c.Call.Return(uUIDToInt, err)
	return _c
}

func (_c *MockOrders_ListItemQuantities_Call) RunAndReturn(run func(ctx context.Context, orderID uuid.UUID) (map[uuid.UUID]int, error)) *MockOrders_ListItemQuantities_Call {
	_c.Call.Return(run)
	return _c
}

// MarkAwaitingPayment provides a mock function for the type MockOrders
func (_mock *MockOrders) MarkAwaitingPayment(ctx context.Context, orderID uuid.UUID) error {
	ret := _mock.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for MarkAwaitingPayment")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, orderID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOrders_MarkAwaitingPayment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkAwaitingPayment'
type MockOrders_MarkAwaitingPayment_Call struct {
	*mock.Call
}

// MarkAwaitingPayment is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID uuid.UUID
func (_e *MockOrders_Expecter) MarkAwaitingPayment(ctx any, orderID any) *MockOrders_MarkAwaitingPayment_Call {
	return &MockOrders_MarkAwaitingPayment_Call{Call: _e.mock.On("MarkAwaitingPayment", ctx, orderID)}
}

func (_c *MockOrders_MarkAwaitingPayment_Call) Run(run func(ctx context.Context, orderID uuid.UUID)) *MockOrders_MarkAwaitingPayment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrders_MarkAwaitingPayment_Call) Return(err error) *MockOrders_MarkAwaitingPayment_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOrders_MarkAwaitingPayment_Call) RunAndReturn(run func(ctx context.Context, orderID uuid.UUID) error) *MockOrders_MarkAwaitingPayment_Call {
	_c.Call.Return(run)
	return _c
}

// MarkFulfillmentFailedAfterCharge provides a mock function for the type MockOrders
func (_mock *MockOrders) MarkFulfillmentFailedAfterCharge(ctx context.Context, orderID uuid.UUID) error {
	ret := _mock.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for MarkFulfillmentFailedAfterCharge")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, orderID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOrders_MarkFulfillmentFailedAfterCharge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkFulfillmentFailedAfterCharge'
type MockOrders_MarkFulfillmentFailedAfterCharge_Call struct {
	*mock.Call
}

// MarkFulfillmentFailedAfterCharge is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID uuid.UUID
func (_e *MockOrders_Expecter) MarkFulfillmentFailedAfterCharge(ctx any, orderID any) *MockOrders_MarkFulfillmentFailedAfterCharge_Call {
	return &MockOrders_MarkFulfillmentFailedAfterCharge_Call{Call: _e.mock.On("MarkFulfillmentFailedAfterCharge", ctx, orderID)}
}

func (_c *MockOrders_MarkFulfillmentFailedAfterCharge_Call) Run(run func(ctx context.Context, orderID uuid.UUID)) *MockOrders_MarkFulfillmentFailedAfterCharge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrders_MarkFulfillmentFailedAfterCharge_Call) Return(err error) *MockOrders_MarkFulfillmentFailedAfterCharge_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOrders_MarkFulfillmentFailedAfterCharge_Call) RunAndReturn(run func(ctx context.Context, orderID uuid.UUID) error) *MockOrders_MarkFulfillmentFailedAfterCharge_Call {
	_c.Call.Return(run)
	return _c
}

// MarkFulfillmentFailedCompensating provides a mock function for the type MockOrders
func (_mock *MockOrders) MarkFulfillmentFailedCompensating(ctx context.Context, orderID uuid.UUID) error {
	ret := _mock.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for MarkFulfillmentFailedCompensating")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, orderID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOrders_MarkFulfillmentFailedCompensating_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkFulfillmentFailedCompensating'
type MockOrders_MarkFulfillmentFailedCompensating_Call struct {
	*mock.Call
}

// MarkFulfillmentFailedCompensating is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID uuid.UUID
func (_e *MockOrders_Expecter) MarkFulfillmentFailedCompensating(ctx any, orderID any) *MockOrders_MarkFulfillmentFailedCompensating_Call {
	return &MockOrders_MarkFulfillmentFailedCompensating_Call{Call: _e.mock.On("MarkFulfillmentFailedCompensating", ctx, orderID)}
}

func (_c *MockOrders_MarkFulfillmentFailedCompensating_Call) Run(run func(ctx context.Context, orderID uuid.UUID)) *MockOrders_MarkFulfillmentFailedCompensating_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrders_MarkFulfillmentFailedCompensating_Call) Return(err error) *MockOrders_MarkFulfillmentFailedCompensating_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOrders_MarkFulfillmentFailedCompensating_Call) RunAndReturn(run func(ctx context.Context, orderID uuid.UUID) error) *MockOrders_MarkFulfillmentFailedCompensating_Call {
	_c.Call.Return(run)
	return _c
}

// MarkPaid provides a mock function for the type MockOrders
func (_mock *MockOrders) MarkPaid(ctx context.Context, orderID uuid.UUID) error {
	ret := _mock.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for MarkPaid")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, orderID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOrders_MarkPaid_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkPaid'
type MockOrders_MarkPaid_Call struct {
	*mock.Call
}

// MarkPaid is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID uuid.UUID
func (_e *MockOrders_Expecter) MarkPaid(ctx any, orderID any) *MockOrders_MarkPaid_Call {
	return &MockOrders_MarkPaid_Call{Call: _e.mock.On("MarkPaid", ctx, orderID)}
}

func (_c *MockOrders_MarkPaid_Call) Run(run func(ctx context.Context, orderID uuid.UUID)) *MockOrders_MarkPaid_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrders_MarkPaid_Call) Return(err error) *MockOrders_MarkPaid_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOrders_MarkPaid_Call) RunAndReturn(run func(ctx context.Context, orderID uuid.UUID) error) *MockOrders_MarkPaid_Call {
	_c.Call.Return(run)
	return _c
}

// MarkPaymentProcessing provides a mock function for the type MockOrders
func (_mock *MockOrders) MarkPaymentProcessing(ctx context.Context, orderID uuid.UUID) error {
	ret := _mock.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for MarkPaymentProcessing")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, orderID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOrders_MarkPaymentProcessing_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkPaymentProcessing'
type MockOrders_MarkPaymentProcessing_Call struct {
	*mock.Call
}

// MarkPaymentProcessing is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID uuid.UUID
func (_e *MockOrders_Expecter) MarkPaymentProcessing(ctx any, orderID any) *MockOrders_MarkPaymentProcessing_Call {
	return &MockOrders_MarkPaymentProcessing_Call{Call: _e.mock.On("MarkPaymentProcessing", ctx, orderID)}
}

func (_c *MockOrders_MarkPaymentProcessing_Call) Run(run func(ctx context.Context, orderID uuid.UUID)) *MockOrders_MarkPaymentProcessing_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrders_MarkPaymentProcessing_Call) Return(err error) *MockOrders_MarkPaymentProcessing_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOrders_MarkPaymentProcessing_Call) RunAndReturn(run func(ctx context.Context, orderID uuid.UUID) error) *MockOrders_MarkPaymentProcessing_Call {
	_c.Call.Return(run)
	return _c
}

// MarkRefunded provides a mock function for the type MockOrders
func (_mock *MockOrders) MarkRefunded(ctx context.Context, orderID uuid.UUID) error {
	ret := _mock.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for MarkRefunded")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, orderID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOrders_MarkRefunded_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkRefunded'
type MockOrders_MarkRefunded_Call struct {
	*mock.Call
}

// MarkRefunded is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID uuid.UUID
func (_e *MockOrders_Expecter) MarkRefunded(ctx any, orderID any) *MockOrders_MarkRefunded_Call {
	return &MockOrders_MarkRefunded_Call{Call: _e.mock.On("MarkRefunded", ctx, orderID)}
}

func (_c *MockOrders_MarkRefunded_Call) Run(run func(ctx context.Context, orderID uuid.UUID)) *MockOrders_MarkRefunded_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrders_MarkRefunded_Call) Return(err error) *MockOrders_MarkRefunded_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOrders_MarkRefunded_Call) RunAndReturn(run func(ctx context.Context, orderID uuid.UUID) error) *MockOrders_MarkRefunded_Call {
	_c.Call.Return(run)
	return _c
}

// Snapshot provides a mock function for the type MockOrders
func (_mock *MockOrders) Snapshot(ctx context.Context, orderID uuid.UUID) (order.Snapshot, error) {
	ret := _mock.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for Snapshot")
	}

	var r0 order.Snapshot
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (order.Snapshot, error)); ok {
		return returnFunc(ctx, orderID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) order.Snapshot); ok {
		r0 = returnFunc(ctx, orderID)
	} else {
		r0 = ret.Get(0).(order.Snapshot)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, orderID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrders_Snapshot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Snapshot'
type MockOrders_Snapshot_Call struct {
	*mock.Call
}

// Snapshot is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID uuid.UUID
func (_e *MockOrders_Expecter) Snapshot(ctx any, orderID any) *MockOrders_Snapshot_Call {
	return &MockOrders_Snapshot_Call{Call: _e.mock.On("Snapshot", ctx, orderID)}
}

func (_c *MockOrders_Snapshot_Call) Run(run func(ctx context.Context, orderID uuid.UUID)) *MockOrders_Snapshot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrders_Snapshot_Call) Return(snapshot order.Snapshot, err error) *MockOrders_Snapshot_Call {
	_c.Call.Return(snapshot, err)
	return _c
}

func (_c *MockOrders_Snapshot_Call) RunAndReturn(run func(ctx context.Context, orderID uuid.UUID) (order.Snapshot, error)) *MockOrders_Snapshot_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockInventory creates a new instance of MockInventory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInventory(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInventory {
	mock := &MockInventory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockInventory is an autogenerated mock type for the Inventory type
type MockInventory struct {
	mock.Mock
}

type MockInventory_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInventory) EXPECT() *MockInventory_Expecter {
	return &MockInventory_Expecter{mock: &_m.Mock}
}

// Deduct provides a mock function for the type MockInventory
func (_mock *MockInventory) Deduct(ctx context.Context, items map[uuid.UUID]int) error {
	ret := _mock.Called(ctx, items)

	if len(ret) == 0 {
		panic("no return value specified for Deduct")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, map[uuid.UUID]int) error); ok {
		r0 = returnFunc(ctx, items)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockInventory_Deduct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Deduct'
type MockInventory_Deduct_Call struct {
	*mock.Call
}

// Deduct is a helper method to define mock.On call
//   - ctx context.Context
//   - items map[uuid.UUID]int
func (_e *MockInventory_Expecter) Deduct(ctx any, items any) *MockInventory_Deduct_Call {
	return &MockInventory_Deduct_Call{Call: _e.mock.On("Deduct", ctx, items)}
}

func (_c *MockInventory_Deduct_Call) Run(run func(ctx context.Context, items map[uuid.UUID]int)) *MockInventory_Deduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 map[uuid.UUID]int
		if args[1] != nil {
			arg1 = args[1].(map[uuid.UUID]int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockInventory_Deduct_Call) Return(err error) *MockInventory_Deduct_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockInventory_Deduct_Call) RunAndReturn(run func(ctx context.Context, items map[uuid.UUID]int) error) *MockInventory_Deduct_Call {
	_c.Call.Return(run)
	return _c
}

// Restore provides a mock function for the type MockInventory
func (_mock *MockInventory) Restore(ctx context.Context, items map[uuid.UUID]int, prior inventory.StockState) error {
	ret := _mock.Called(ctx, items, prior)

	if len(ret) == 0 {
		panic("no return value specified for Restore")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, map[uuid.UUID]int, inventory.StockState) error); ok {
		r0 = returnFunc(ctx, items, prior)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockInventory_Restore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Restore'
type MockInventory_Restore_Call struct {
	*mock.Call
}

// Restore is a helper method to define mock.On call
//   - ctx context.Context
//   - items map[uuid.UUID]int
//   - prior inventory.StockState
func (_e *MockInventory_Expecter) Restore(ctx any, items any, prior any) *MockInventory_Restore_Call {
	return &MockInventory_Restore_Call{Call: _e.mock.On("Restore", ctx, items, prior)}
}

func (_c *MockInventory_Restore_Call) Run(run func(ctx context.Context, items map[uuid.UUID]int, prior inventory.StockState)) *MockInventory_Restore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 map[uuid.UUID]int
		if args[1] != nil {
			arg1 = args[1].(map[uuid.UUID]int)
		}
		var arg2 inventory.StockState
		if args[2] != nil {
			arg2 = args[2].(inventory.StockState)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockInventory_Restore_Call) Return(err error) *MockInventory_Restore_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockInventory_Restore_Call) RunAndReturn(run func(ctx context.Context, items map[uuid.UUID]int, prior inventory.StockState) error) *MockInventory_Restore_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCouponReleaser creates a new instance of MockCouponReleaser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCouponReleaser(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCouponReleaser {
	mock := &MockCouponReleaser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCouponReleaser is an autogenerated mock type for the CouponReleaser type
type MockCouponReleaser struct {
	mock.Mock
}

type MockCouponReleaser_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCouponReleaser) EXPECT() *MockCouponReleaser_Expecter {
	return &MockCouponReleaser_Expecter{mock: &_m.Mock}
}

// Release provides a mock function for the type MockCouponReleaser
func (_mock *MockCouponReleaser) Release(ctx context.Context, orderID uuid.UUID) error {
	ret := _mock.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for Release")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, orderID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCouponReleaser_Release_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Release'
type MockCouponReleaser_Release_Call struct {
	*mock.Call
}

// Release is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID uuid.UUID
func (_e *MockCouponReleaser_Expecter) Release(ctx any, orderID any) *MockCouponReleaser_Release_Call {
	return &MockCouponReleaser_Release_Call{Call: _e.mock.On("Release", ctx, orderID)}
}

func (_c *MockCouponReleaser_Release_Call) Run(run func(ctx context.Context, orderID uuid.UUID)) *MockCouponReleaser_Release_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCouponReleaser_Release_Call) Return(err error) *MockCouponReleaser_Release_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCouponReleaser_Release_Call) RunAndReturn(run func(ctx context.Context, orderID uuid.UUID) error) *MockCouponReleaser_Release_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// ClearPaymentURL provides a mock function for the type MockRepository
func (_mock *MockRepository) ClearPaymentURL(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for ClearPaymentURL")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_ClearPaymentURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClearPaymentURL'
type MockRepository_ClearPaymentURL_Call struct {
	*mock.Call
}

// ClearPaymentURL is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockRepository_Expecter) ClearPaymentURL(ctx any, id any) *MockRepository_ClearPaymentURL_Call {
	return &MockRepository_ClearPaymentURL_Call{Call: _e.mock.On("ClearPaymentURL", ctx, id)}
}

func (_c *MockRepository_ClearPaymentURL_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockRepository_ClearPaymentURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_ClearPaymentURL_Call) Return(err error) *MockRepository_ClearPaymentURL_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_ClearPaymentURL_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *MockRepository_ClearPaymentURL_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockRepository
func (_mock *MockRepository) Create(ctx context.Context, p *domain.Payment) error {
	ret := _mock.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Payment) error); ok {
		r0 = returnFunc(ctx, p)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - p *domain.Payment
func (_e *MockRepository_Expecter) Create(ctx any, p any) *MockRepository_Create_Call {
	return &MockRepository_Create_Call{Call: _e.mock.On("Create", ctx, p)}
}

func (_c *MockRepository_Create_Call) Run(run func(ctx context.Context, p *domain.Payment)) *MockRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Payment
		if args[1] != nil {
			arg1 = args[1].(*domain.Payment)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Create_Call) Return(err error) *MockRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Create_Call) RunAndReturn(run func(ctx context.Context, p *domain.Payment) error) *MockRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetActiveByOrderID provides a mock function for the type MockRepository
func (_mock *MockRepository) GetActiveByOrderID(ctx context.Context, orderID uuid.UUID) (*domain.Payment, error) {
	ret := _mock.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for GetActiveByOrderID")
	}

	var r0 *domain.Payment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Payment, error)); ok {
		return returnFunc(ctx, orderID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Payment); ok {
		r0 = returnFunc(ctx, orderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Payment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, orderID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetActiveByOrderID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActiveByOrderID'
type MockRepository_GetActiveByOrderID_Call struct {
	*mock.Call
}

// GetActiveByOrderID is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID uuid.UUID
func (_e *MockRepository_Expecter) GetActiveByOrderID(ctx any, orderID any) *MockRepository_GetActiveByOrderID_Call {
	return &MockRepository_GetActiveByOrderID_Call{Call: _e.mock.On("GetActiveByOrderID", ctx, orderID)}
}

func (_c *MockRepository_GetActiveByOrderID_Call) Run(run func(ctx context.Context, orderID uuid.UUID)) *MockRepository_GetActiveByOrderID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetActiveByOrderID_Call) Return(payment *domain.Payment, err error) *MockRepository_GetActiveByOrderID_Call {
	_c.Call.Return(payment, err)
	return _c
}

func (_c *MockRepository_GetActiveByOrderID_Call) RunAndReturn(run func(ctx context.Context, orderID uuid.UUID) (*domain.Payment, error)) *MockRepository_GetActiveByOrderID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByGatewayTxnID provides a mock function for the type MockRepository
func (_mock *MockRepository) GetByGatewayTxnID(ctx context.Context, txnID string) (*domain.Payment, error) {
	ret := _mock.Called(ctx, txnID)

	if len(ret) == 0 {
		panic("no return value specified for GetByGatewayTxnID")
	}

	var r0 *domain.Payment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.Payment, error)); ok {
		return returnFunc(ctx, txnID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.Payment); ok {
		r0 = returnFunc(ctx, txnID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Payment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, txnID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetByGatewayTxnID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByGatewayTxnID'
type MockRepository_GetByGatewayTxnID_Call struct {
	*mock.Call
}

// GetByGatewayTxnID is a helper method to define mock.On call
//   - ctx context.Context
//   - txnID string
func (_e *MockRepository_Expecter) GetByGatewayTxnID(ctx any, txnID any) *MockRepository_GetByGatewayTxnID_Call {
	return &MockRepository_GetByGatewayTxnID_Call{Call: _e.mock.On("GetByGatewayTxnID", ctx, txnID)}
}

func (_c *MockRepository_GetByGatewayTxnID_Call) Run(run func(ctx context.Context, txnID string)) *MockRepository_GetByGatewayTxnID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetByGatewayTxnID_Call) Return(payment *domain.Payment, err error) *MockRepository_GetByGatewayTxnID_Call {
	_c.Call.Return(payment, err)
	return _c
}

func (_c *MockRepository_GetByGatewayTxnID_Call) RunAndReturn(run func(ctx context.Context, txnID string) (*domain.Payment, error)) *MockRepository_GetByGatewayTxnID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockRepository
func (_mock *MockRepository) GetByID(ctx context.Context, id uuid.UUID) (*domain.Payment, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Payment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Payment, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Payment); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Payment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockRepository_Expecter) GetByID(ctx any, id any) *MockRepository_GetByID_Call {
	return &MockRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetByID_Call) Return(payment *domain.Payment, err error) *MockRepository_GetByID_Call {
	_c.Call.Return(payment, err)
	return _c
}

func (_c *MockRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*domain.Payment, error)) *MockRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListAdmin provides a mock function for the type MockRepository
func (_mock *MockRepository) ListAdmin(ctx context.Context, params AdminListParams) ([]domain.Payment, int, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for ListAdmin")
	}

	var r0 []domain.Payment
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, AdminListParams) ([]domain.Payment, int, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, AdminListParams) []domain.Payment); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Payment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, AdminListParams) int); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, AdminListParams) error); ok {
		r2 = returnFunc(ctx, params)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockRepository_ListAdmin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAdmin'
type MockRepository_ListAdmin_Call struct {
	*mock.Call
}

// ListAdmin is a helper method to define mock.On call
//   - ctx context.Context
//   - params AdminListParams
func (_e *MockRepository_Expecter) ListAdmin(ctx any, params any) *MockRepository_ListAdmin_Call {
	return &MockRepository_ListAdmin_Call{Call: _e.mock.On("ListAdmin", ctx, params)}
}

func (_c *MockRepository_ListAdmin_Call) Run(run func(ctx context.Context, params AdminListParams)) *MockRepository_ListAdmin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 AdminListParams
		if args[1] != nil {
			arg1 = args[1].(AdminListParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_ListAdmin_Call) Return(payments []domain.Payment, n int, err error) *MockRepository_ListAdmin_Call {
	_c.Call.Return(payments, n, err)
	return _c
}

func (_c *MockRepository_ListAdmin_Call) RunAndReturn(run func(ctx context.Context, params AdminListParams) ([]domain.Payment, int, error)) *MockRepository_ListAdmin_Call {
	_c.Call.Return(run)
	return _c
}

// MarkPaid provides a mock function for the type MockRepository
func (_mock *MockRepository) MarkPaid(ctx context.Context, id uuid.UUID, fromStatuses []domain.Status) error {
	ret := _mock.Called(ctx, id, fromStatuses)

	if len(ret) == 0 {
		panic("no return value specified for MarkPaid")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, []domain.Status) error); ok {
		r0 = returnFunc(ctx, id, fromStatuses)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_MarkPaid_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkPaid'
type MockRepository_MarkPaid_Call struct {
	*mock.Call
}

// MarkPaid is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - fromStatuses []domain.Status
func (_e *MockRepository_Expecter) MarkPaid(ctx any, id any, fromStatuses any) *MockRepository_MarkPaid_Call {
	return &MockRepository_MarkPaid_Call{Call: _e.mock.On("MarkPaid", ctx, id, fromStatuses)}
}

func (_c *MockRepository_MarkPaid_Call) Run(run func(ctx context.Context, id uuid.UUID, fromStatuses []domain.Status)) *MockRepository_MarkPaid_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 []domain.Status
		if args[2] != nil {
			arg2 = args[2].([]domain.Status)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_MarkPaid_Call) Return(err error) *MockRepository_MarkPaid_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_MarkPaid_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, fromStatuses []domain.Status) error) *MockRepository_MarkPaid_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateGateway provides a mock function for the type MockRepository
func (_mock *MockRepository) UpdateGateway(ctx context.Context, id uuid.UUID, txnID string, response GatewayChargeResponse) error {
	ret := _mock.Called(ctx, id, txnID, response)

	if len(ret) == 0 {
		panic("no return value specified for UpdateGateway")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, GatewayChargeResponse) error); ok {
		r0 = returnFunc(ctx, id, txnID, response)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_UpdateGateway_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateGateway'
type MockRepository_UpdateGateway_Call struct {
	*mock.Call
}

// UpdateGateway is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - txnID string
//   - response GatewayChargeResponse
func (_e *MockRepository_Expecter) UpdateGateway(ctx any, id any, txnID any, response any) *MockRepository_UpdateGateway_Call {
	return &MockRepository_UpdateGateway_Call{Call: _e.mock.On("UpdateGateway", ctx, id, txnID, response)}
}

func (_c *MockRepository_UpdateGateway_Call) Run(run func(ctx context.Context, id uuid.UUID, txnID string, response GatewayChargeResponse)) *MockRepository_UpdateGateway_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 GatewayChargeResponse
		if args[3] != nil {
			arg3 = args[3].(GatewayChargeResponse)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRepository_UpdateGateway_Call) Return(err error) *MockRepository_UpdateGateway_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_UpdateGateway_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, txnID string, response GatewayChargeResponse) error) *MockRepository_UpdateGateway_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePaymentURL provides a mock function for the type MockRepository
func (_mock *MockRepository) UpdatePaymentURL(ctx context.Context, id uuid.UUID, paymentURL string) error {
	ret := _mock.Called(ctx, id, paymentURL)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePaymentURL")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = returnFunc(ctx, id, paymentURL)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_UpdatePaymentURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePaymentURL'
type MockRepository_UpdatePaymentURL_Call struct {
	*mock.Call
}

// UpdatePaymentURL is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - paymentURL string
func (_e *MockRepository_Expecter) UpdatePaymentURL(ctx any, id any, paymentURL any) *MockRepository_UpdatePaymentURL_Call {
	return &MockRepository_UpdatePaymentURL_Call{Call: _e.mock.On("UpdatePaymentURL", ctx, id, paymentURL)}
}

func (_c *MockRepository_UpdatePaymentURL_Call) Run(run func(ctx context.Context, id uuid.UUID, paymentURL string)) *MockRepository_UpdatePaymentURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_UpdatePaymentURL_Call) Return(err error) *MockRepository_UpdatePaymentURL_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_UpdatePaymentURL_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, paymentURL string) error) *MockRepository_UpdatePaymentURL_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function for the type MockRepository
func (_mock *MockRepository) UpdateStatus(ctx context.Context, id uuid.UUID, toStatus domain.Status, fromStatuses []domain.Status) error {
	ret := _mock.Called(ctx, id, toStatus, fromStatuses)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, domain.Status, []domain.Status) error); ok {
		r0 = returnFunc(ctx, id, toStatus, fromStatuses)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type MockRepository_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - toStatus domain.Status
//   - fromStatuses []domain.Status
func (_e *MockRepository_Expecter) UpdateStatus(ctx any, id any, toStatus any, fromStatuses any) *MockRepository_UpdateStatus_Call {
	return &MockRepository_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", ctx, id, toStatus, fromStatuses)}
}

func (_c *MockRepository_UpdateStatus_Call) Run(run func(ctx context.Context, id uuid.UUID, toStatus domain.Status, fromStatuses []domain.Status)) *MockRepository_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 domain.Status
		if args[2] != nil {
			arg2 = args[2].(domain.Status)
		}
		var arg3 []domain.Status
		if args[3] != nil {
			arg3 = args[3].([]domain.Status)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRepository_UpdateStatus_Call) Return(err error) *MockRepository_UpdateStatus_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_UpdateStatus_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, toStatus domain.Status, fromStatuses []domain.Status) error) *MockRepository_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}
