all: false
dir: "mocks/{{.SrcPackageName}}"
filename: "mock_{{.InterfaceName}}.go"
force-file-write: true
formatter: goimports
log-level: info
pkgname: "mocks"
template: testify
packages:
  github.com/residwi/go-api-project-template/internal/auth:
    interfaces:
      UserProvider:
  github.com/residwi/go-api-project-template/internal/user:
    interfaces:
      Repository:
  github.com/residwi/go-api-project-template/internal/category:
    interfaces:
      Repository:
      ProductCounter:
  github.com/residwi/go-api-project-template/internal/product:
    interfaces:
      Repository:
      InventoryReader:
      InventoryRegistrar:
  github.com/residwi/go-api-project-template/internal/inventory:
    interfaces:
      Repository:
  github.com/residwi/go-api-project-template/internal/cart:
    interfaces:
      Repository:
      ProductLookup:
  github.com/residwi/go-api-project-template/internal/order:
    interfaces:
      Repository:
      CartProvider:
      InventoryReserver:
      PaymentInitiator:
      PaymentJobCanceller:
      CouponReserver:
      NotificationEnqueuer:
  github.com/residwi/go-api-project-template/internal/payment:
    interfaces:
      Repository:
      OrderUpdater:
      OrderItemsGetter:
      OrderGetter:
      InventoryDeductor:
      InventoryRestorer:
      CouponReleaser:
      Gateway:
  github.com/residwi/go-api-project-template/internal/shipping:
    interfaces:
      Repository:
      OrderProvider:
      OrderUpdater:
  github.com/residwi/go-api-project-template/internal/review:
    interfaces:
      Repository:
      PurchaseVerifier:
  github.com/residwi/go-api-project-template/internal/promotion:
    interfaces:
      Repository:
  github.com/residwi/go-api-project-template/internal/wishlist:
    interfaces:
      Repository:
  github.com/residwi/go-api-project-template/internal/notification:
    interfaces:
      Repository:
  github.com/residwi/go-api-project-template/internal/dashboard:
    interfaces:
      Repository:
  github.com/residwi/go-api-project-template/internal/middleware:
    interfaces:
      TokenValidator:
      UserStatusChecker:
