// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package http

import (
	"context"

	"github.com/google/uuid"
	"github.com/residwi/go-api-project-template/internal/modules/payment/domain"
	"github.com/residwi/go-api-project-template/internal/modules/payment/usecase/query"
	mock "github.com/stretchr/testify/mock"
)

// NewMockPaymentReader creates a new instance of MockPaymentReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPaymentReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPaymentReader {
	mock := &MockPaymentReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPaymentReader is an autogenerated mock type for the PaymentReader type
type MockPaymentReader struct {
	mock.Mock
}

type MockPaymentReader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPaymentReader) EXPECT() *MockPaymentReader_Expecter {
	return &MockPaymentReader_Expecter{mock: &_m.Mock}
}

// GetByID provides a mock function for the type MockPaymentReader
func (_mock *MockPaymentReader) GetByID(ctx context.Context, id uuid.UUID) (*domain.Payment, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Payment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Payment, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Payment); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Payment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPaymentReader_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockPaymentReader_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockPaymentReader_Expecter) GetByID(ctx any, id any) *MockPaymentReader_GetByID_Call {
	return &MockPaymentReader_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockPaymentReader_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockPaymentReader_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPaymentReader_GetByID_Call) Return(payment *domain.Payment, err error) *MockPaymentReader_GetByID_Call {
	_c.Call.Return(payment, err)
	return _c
}

func (_c *MockPaymentReader_GetByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*domain.Payment, error)) *MockPaymentReader_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListAdmin provides a mock function for the type MockPaymentReader
func (_mock *MockPaymentReader) ListAdmin(ctx context.Context, params query.AdminListParams) ([]domain.Payment, int, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for ListAdmin")
	}

	var r0 []domain.Payment
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, query.AdminListParams) ([]domain.Payment, int, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, query.AdminListParams) []domain.Payment); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Payment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, query.AdminListParams) int); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, query.AdminListParams) error); ok {
		r2 = returnFunc(ctx, params)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockPaymentReader_ListAdmin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAdmin'
type MockPaymentReader_ListAdmin_Call struct {
	*mock.Call
}

// ListAdmin is a helper method to define mock.On call
//   - ctx context.Context
//   - params query.AdminListParams
func (_e *MockPaymentReader_Expecter) ListAdmin(ctx any, params any) *MockPaymentReader_ListAdmin_Call {
	return &MockPaymentReader_ListAdmin_Call{Call: _e.mock.On("ListAdmin", ctx, params)}
}

func (_c *MockPaymentReader_ListAdmin_Call) Run(run func(ctx context.Context, params query.AdminListParams)) *MockPaymentReader_ListAdmin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 query.AdminListParams
		if args[1] != nil {
			arg1 = args[1].(query.AdminListParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPaymentReader_ListAdmin_Call) Return(payments []domain.Payment, n int, err error) *MockPaymentReader_ListAdmin_Call {
	_c.Call.Return(payments, n, err)
	return _c
}

func (_c *MockPaymentReader_ListAdmin_Call) RunAndReturn(run func(ctx context.Context, params query.AdminListParams) ([]domain.Payment, int, error)) *MockPaymentReader_ListAdmin_Call {
	_c.Call.Return(run)
	return _c
}
