// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package order

import (
	"context"

	"github.com/google/uuid"
	"github.com/residwi/go-api-project-template/internal/modules/cart/contract"
	contract0 "github.com/residwi/go-api-project-template/internal/modules/inventory/contract"
	contract1 "github.com/residwi/go-api-project-template/internal/modules/payment/contract"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCartProvider creates a new instance of MockCartProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCartProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCartProvider {
	mock := &MockCartProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCartProvider is an autogenerated mock type for the CartProvider type
type MockCartProvider struct {
	mock.Mock
}

type MockCartProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCartProvider) EXPECT() *MockCartProvider_Expecter {
	return &MockCartProvider_Expecter{mock: &_m.Mock}
}

// Clear provides a mock function for the type MockCartProvider
func (_mock *MockCartProvider) Clear(ctx context.Context, userID uuid.UUID) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for Clear")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCartProvider_Clear_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Clear'
type MockCartProvider_Clear_Call struct {
	*mock.Call
}

// Clear is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockCartProvider_Expecter) Clear(ctx any, userID any) *MockCartProvider_Clear_Call {
	return &MockCartProvider_Clear_Call{Call: _e.mock.On("Clear", ctx, userID)}
}

func (_c *MockCartProvider_Clear_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockCartProvider_Clear_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCartProvider_Clear_Call) Return(err error) *MockCartProvider_Clear_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCartProvider_Clear_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) error) *MockCartProvider_Clear_Call {
	_c.Call.Return(run)
	return _c
}

// GetSnapshot provides a mock function for the type MockCartProvider
func (_mock *MockCartProvider) GetSnapshot(ctx context.Context, userID uuid.UUID) (*contract.Cart, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetSnapshot")
	}

	var r0 *contract.Cart
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*contract.Cart, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *contract.Cart); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*contract.Cart)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCartProvider_GetSnapshot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSnapshot'
type MockCartProvider_GetSnapshot_Call struct {
	*mock.Call
}

// GetSnapshot is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockCartProvider_Expecter) GetSnapshot(ctx any, userID any) *MockCartProvider_GetSnapshot_Call {
	return &MockCartProvider_GetSnapshot_Call{Call: _e.mock.On("GetSnapshot", ctx, userID)}
}

func (_c *MockCartProvider_GetSnapshot_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockCartProvider_GetSnapshot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCartProvider_GetSnapshot_Call) Return(cart *contract.Cart, err error) *MockCartProvider_GetSnapshot_Call {
	_c.Call.Return(cart, err)
	return _c
}

func (_c *MockCartProvider_GetSnapshot_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) (*contract.Cart, error)) *MockCartProvider_GetSnapshot_Call {
	_c.Call.Return(run)
	return _c
}

// LockCart provides a mock function for the type MockCartProvider
func (_mock *MockCartProvider) LockCart(ctx context.Context, userID uuid.UUID) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for LockCart")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCartProvider_LockCart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LockCart'
type MockCartProvider_LockCart_Call struct {
	*mock.Call
}

// LockCart is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockCartProvider_Expecter) LockCart(ctx any, userID any) *MockCartProvider_LockCart_Call {
	return &MockCartProvider_LockCart_Call{Call: _e.mock.On("LockCart", ctx, userID)}
}

func (_c *MockCartProvider_LockCart_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockCartProvider_LockCart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCartProvider_LockCart_Call) Return(err error) *MockCartProvider_LockCart_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCartProvider_LockCart_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) error) *MockCartProvider_LockCart_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockInventoryPort creates a new instance of MockInventoryPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInventoryPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInventoryPort {
	mock := &MockInventoryPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockInventoryPort is an autogenerated mock type for the InventoryPort type
type MockInventoryPort struct {
	mock.Mock
}

type MockInventoryPort_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInventoryPort) EXPECT() *MockInventoryPort_Expecter {
	return &MockInventoryPort_Expecter{mock: &_m.Mock}
}

// DeductBatch provides a mock function for the type MockInventoryPort
func (_mock *MockInventoryPort) DeductBatch(ctx context.Context, items map[uuid.UUID]int) error {
	ret := _mock.Called(ctx, items)

	if len(ret) == 0 {
		panic("no return value specified for DeductBatch")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, map[uuid.UUID]int) error); ok {
		r0 = returnFunc(ctx, items)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockInventoryPort_DeductBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeductBatch'
type MockInventoryPort_DeductBatch_Call struct {
	*mock.Call
}

// DeductBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - items map[uuid.UUID]int
func (_e *MockInventoryPort_Expecter) DeductBatch(ctx any, items any) *MockInventoryPort_DeductBatch_Call {
	return &MockInventoryPort_DeductBatch_Call{Call: _e.mock.On("DeductBatch", ctx, items)}
}

func (_c *MockInventoryPort_DeductBatch_Call) Run(run func(ctx context.Context, items map[uuid.UUID]int)) *MockInventoryPort_DeductBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 map[uuid.UUID]int
		if args[1] != nil {
			arg1 = args[1].(map[uuid.UUID]int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockInventoryPort_DeductBatch_Call) Return(err error) *MockInventoryPort_DeductBatch_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockInventoryPort_DeductBatch_Call) RunAndReturn(run func(ctx context.Context, items map[uuid.UUID]int) error) *MockInventoryPort_DeductBatch_Call {
	_c.Call.Return(run)
	return _c
}

// ReserveBatch provides a mock function for the type MockInventoryPort
func (_mock *MockInventoryPort) ReserveBatch(ctx context.Context, items map[uuid.UUID]int) error {
	ret := _mock.Called(ctx, items)

	if len(ret) == 0 {
		panic("no return value specified for ReserveBatch")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, map[uuid.UUID]int) error); ok {
		r0 = returnFunc(ctx, items)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockInventoryPort_ReserveBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReserveBatch'
type MockInventoryPort_ReserveBatch_Call struct {
	*mock.Call
}

// ReserveBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - items map[uuid.UUID]int
func (_e *MockInventoryPort_Expecter) ReserveBatch(ctx any, items any) *MockInventoryPort_ReserveBatch_Call {
	return &MockInventoryPort_ReserveBatch_Call{Call: _e.mock.On("ReserveBatch", ctx, items)}
}

func (_c *MockInventoryPort_ReserveBatch_Call) Run(run func(ctx context.Context, items map[uuid.UUID]int)) *MockInventoryPort_ReserveBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 map[uuid.UUID]int
		if args[1] != nil {
			arg1 = args[1].(map[uuid.UUID]int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockInventoryPort_ReserveBatch_Call) Return(err error) *MockInventoryPort_ReserveBatch_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockInventoryPort_ReserveBatch_Call) RunAndReturn(run func(ctx context.Context, items map[uuid.UUID]int) error) *MockInventoryPort_ReserveBatch_Call {
	_c.Call.Return(run)
	return _c
}

// Restore provides a mock function for the type MockInventoryPort
func (_mock *MockInventoryPort) Restore(ctx context.Context, items map[uuid.UUID]int, prior contract0.StockState) error {
	ret := _mock.Called(ctx, items, prior)

	if len(ret) == 0 {
		panic("no return value specified for Restore")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, map[uuid.UUID]int, contract0.StockState) error); ok {
		r0 = returnFunc(ctx, items, prior)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockInventoryPort_Restore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Restore'
type MockInventoryPort_Restore_Call struct {
	*mock.Call
}

// Restore is a helper method to define mock.On call
//   - ctx context.Context
//   - items map[uuid.UUID]int
//   - prior contract0.StockState
func (_e *MockInventoryPort_Expecter) Restore(ctx any, items any, prior any) *MockInventoryPort_Restore_Call {
	return &MockInventoryPort_Restore_Call{Call: _e.mock.On("Restore", ctx, items, prior)}
}

func (_c *MockInventoryPort_Restore_Call) Run(run func(ctx context.Context, items map[uuid.UUID]int, prior contract0.StockState)) *MockInventoryPort_Restore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 map[uuid.UUID]int
		if args[1] != nil {
			arg1 = args[1].(map[uuid.UUID]int)
		}
		var arg2 contract0.StockState
		if args[2] != nil {
			arg2 = args[2].(contract0.StockState)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockInventoryPort_Restore_Call) Return(err error) *MockInventoryPort_Restore_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockInventoryPort_Restore_Call) RunAndReturn(run func(ctx context.Context, items map[uuid.UUID]int, prior contract0.StockState) error) *MockInventoryPort_Restore_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCouponPort creates a new instance of MockCouponPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCouponPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCouponPort {
	mock := &MockCouponPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCouponPort is an autogenerated mock type for the CouponPort type
type MockCouponPort struct {
	mock.Mock
}

type MockCouponPort_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCouponPort) EXPECT() *MockCouponPort_Expecter {
	return &MockCouponPort_Expecter{mock: &_m.Mock}
}

// Release provides a mock function for the type MockCouponPort
func (_mock *MockCouponPort) Release(ctx context.Context, orderID uuid.UUID) error {
	ret := _mock.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for Release")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, orderID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCouponPort_Release_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Release'
type MockCouponPort_Release_Call struct {
	*mock.Call
}

// Release is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID uuid.UUID
func (_e *MockCouponPort_Expecter) Release(ctx any, orderID any) *MockCouponPort_Release_Call {
	return &MockCouponPort_Release_Call{Call: _e.mock.On("Release", ctx, orderID)}
}

func (_c *MockCouponPort_Release_Call) Run(run func(ctx context.Context, orderID uuid.UUID)) *MockCouponPort_Release_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCouponPort_Release_Call) Return(err error) *MockCouponPort_Release_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCouponPort_Release_Call) RunAndReturn(run func(ctx context.Context, orderID uuid.UUID) error) *MockCouponPort_Release_Call {
	_c.Call.Return(run)
	return _c
}

// Reserve provides a mock function for the type MockCouponPort
func (_mock *MockCouponPort) Reserve(ctx context.Context, code string, userID uuid.UUID, orderID uuid.UUID, orderSubtotal int64) (int64, error) {
	ret := _mock.Called(ctx, code, userID, orderID, orderSubtotal)

	if len(ret) == 0 {
		panic("no return value specified for Reserve")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uuid.UUID, uuid.UUID, int64) (int64, error)); ok {
		return returnFunc(ctx, code, userID, orderID, orderSubtotal)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uuid.UUID, uuid.UUID, int64) int64); ok {
		r0 = returnFunc(ctx, code, userID, orderID, orderSubtotal)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, uuid.UUID, uuid.UUID, int64) error); ok {
		r1 = returnFunc(ctx, code, userID, orderID, orderSubtotal)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCouponPort_Reserve_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reserve'
type MockCouponPort_Reserve_Call struct {
	*mock.Call
}

// Reserve is a helper method to define mock.On call
//   - ctx context.Context
//   - code string
//   - userID uuid.UUID
//   - orderID uuid.UUID
//   - orderSubtotal int64
func (_e *MockCouponPort_Expecter) Reserve(ctx any, code any, userID any, orderID any, orderSubtotal any) *MockCouponPort_Reserve_Call {
	return &MockCouponPort_Reserve_Call{Call: _e.mock.On("Reserve", ctx, code, userID, orderID, orderSubtotal)}
}

func (_c *MockCouponPort_Reserve_Call) Run(run func(ctx context.Context, code string, userID uuid.UUID, orderID uuid.UUID, orderSubtotal int64)) *MockCouponPort_Reserve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 uuid.UUID
		if args[3] != nil {
			arg3 = args[3].(uuid.UUID)
		}
		var arg4 int64
		if args[4] != nil {
			arg4 = args[4].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockCouponPort_Reserve_Call) Return(n int64, err error) *MockCouponPort_Reserve_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockCouponPort_Reserve_Call) RunAndReturn(run func(ctx context.Context, code string, userID uuid.UUID, orderID uuid.UUID, orderSubtotal int64) (int64, error)) *MockCouponPort_Reserve_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockNotificationEnqueuer creates a new instance of MockNotificationEnqueuer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNotificationEnqueuer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNotificationEnqueuer {
	mock := &MockNotificationEnqueuer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockNotificationEnqueuer is an autogenerated mock type for the NotificationEnqueuer type
type MockNotificationEnqueuer struct {
	mock.Mock
}

type MockNotificationEnqueuer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNotificationEnqueuer) EXPECT() *MockNotificationEnqueuer_Expecter {
	return &MockNotificationEnqueuer_Expecter{mock: &_m.Mock}
}

// EnqueueOrderPlaced provides a mock function for the type MockNotificationEnqueuer
func (_mock *MockNotificationEnqueuer) EnqueueOrderPlaced(ctx context.Context, userID uuid.UUID, orderID uuid.UUID) error {
	ret := _mock.Called(ctx, userID, orderID)

	if len(ret) == 0 {
		panic("no return value specified for EnqueueOrderPlaced")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, userID, orderID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNotificationEnqueuer_EnqueueOrderPlaced_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnqueueOrderPlaced'
type MockNotificationEnqueuer_EnqueueOrderPlaced_Call struct {
	*mock.Call
}

// EnqueueOrderPlaced is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - orderID uuid.UUID
func (_e *MockNotificationEnqueuer_Expecter) EnqueueOrderPlaced(ctx any, userID any, orderID any) *MockNotificationEnqueuer_EnqueueOrderPlaced_Call {
	return &MockNotificationEnqueuer_EnqueueOrderPlaced_Call{Call: _e.mock.On("EnqueueOrderPlaced", ctx, userID, orderID)}
}

func (_c *MockNotificationEnqueuer_EnqueueOrderPlaced_Call) Run(run func(ctx context.Context, userID uuid.UUID, orderID uuid.UUID)) *MockNotificationEnqueuer_EnqueueOrderPlaced_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockNotificationEnqueuer_EnqueueOrderPlaced_Call) Return(err error) *MockNotificationEnqueuer_EnqueueOrderPlaced_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNotificationEnqueuer_EnqueueOrderPlaced_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, orderID uuid.UUID) error) *MockNotificationEnqueuer_EnqueueOrderPlaced_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPaymentInitiator creates a new instance of MockPaymentInitiator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPaymentInitiator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPaymentInitiator {
	mock := &MockPaymentInitiator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPaymentInitiator is an autogenerated mock type for the PaymentInitiator type
type MockPaymentInitiator struct {
	mock.Mock
}

type MockPaymentInitiator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPaymentInitiator) EXPECT() *MockPaymentInitiator_Expecter {
	return &MockPaymentInitiator_Expecter{mock: &_m.Mock}
}

// InitiatePayment provides a mock function for the type MockPaymentInitiator
func (_mock *MockPaymentInitiator) InitiatePayment(ctx context.Context, p contract1.ChargeRequest) (contract1.ChargeResult, error) {
	ret := _mock.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for InitiatePayment")
	}

	var r0 contract1.ChargeResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, contract1.ChargeRequest) (contract1.ChargeResult, error)); ok {
		return returnFunc(ctx, p)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, contract1.ChargeRequest) contract1.ChargeResult); ok {
		r0 = returnFunc(ctx, p)
	} else {
		r0 = ret.Get(0).(contract1.ChargeResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, contract1.ChargeRequest) error); ok {
		r1 = returnFunc(ctx, p)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPaymentInitiator_InitiatePayment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InitiatePayment'
type MockPaymentInitiator_InitiatePayment_Call struct {
	*mock.Call
}

// InitiatePayment is a helper method to define mock.On call
//   - ctx context.Context
//   - p contract1.ChargeRequest
func (_e *MockPaymentInitiator_Expecter) InitiatePayment(ctx any, p any) *MockPaymentInitiator_InitiatePayment_Call {
	return &MockPaymentInitiator_InitiatePayment_Call{Call: _e.mock.On("InitiatePayment", ctx, p)}
}

func (_c *MockPaymentInitiator_InitiatePayment_Call) Run(run func(ctx context.Context, p contract1.ChargeRequest)) *MockPaymentInitiator_InitiatePayment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 contract1.ChargeRequest
		if args[1] != nil {
			arg1 = args[1].(contract1.ChargeRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPaymentInitiator_InitiatePayment_Call) Return(chargeResult contract1.ChargeResult, err error) *MockPaymentInitiator_InitiatePayment_Call {
	_c.Call.Return(chargeResult, err)
	return _c
}

func (_c *MockPaymentInitiator_InitiatePayment_Call) RunAndReturn(run func(ctx context.Context, p contract1.ChargeRequest) (contract1.ChargeResult, error)) *MockPaymentInitiator_InitiatePayment_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPaymentJobCanceller creates a new instance of MockPaymentJobCanceller. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPaymentJobCanceller(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPaymentJobCanceller {
	mock := &MockPaymentJobCanceller{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPaymentJobCanceller is an autogenerated mock type for the PaymentJobCanceller type
type MockPaymentJobCanceller struct {
	mock.Mock
}

type MockPaymentJobCanceller_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPaymentJobCanceller) EXPECT() *MockPaymentJobCanceller_Expecter {
	return &MockPaymentJobCanceller_Expecter{mock: &_m.Mock}
}

// CancelJobsByOrderID provides a mock function for the type MockPaymentJobCanceller
func (_mock *MockPaymentJobCanceller) CancelJobsByOrderID(ctx context.Context, orderID uuid.UUID) error {
	ret := _mock.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for CancelJobsByOrderID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, orderID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPaymentJobCanceller_CancelJobsByOrderID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelJobsByOrderID'
type MockPaymentJobCanceller_CancelJobsByOrderID_Call struct {
	*mock.Call
}

// CancelJobsByOrderID is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID uuid.UUID
func (_e *MockPaymentJobCanceller_Expecter) CancelJobsByOrderID(ctx any, orderID any) *MockPaymentJobCanceller_CancelJobsByOrderID_Call {
	return &MockPaymentJobCanceller_CancelJobsByOrderID_Call{Call: _e.mock.On("CancelJobsByOrderID", ctx, orderID)}
}

func (_c *MockPaymentJobCanceller_CancelJobsByOrderID_Call) Run(run func(ctx context.Context, orderID uuid.UUID)) *MockPaymentJobCanceller_CancelJobsByOrderID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPaymentJobCanceller_CancelJobsByOrderID_Call) Return(err error) *MockPaymentJobCanceller_CancelJobsByOrderID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPaymentJobCanceller_CancelJobsByOrderID_Call) RunAndReturn(run func(ctx context.Context, orderID uuid.UUID) error) *MockPaymentJobCanceller_CancelJobsByOrderID_Call {
	_c.Call.Return(run)
	return _c
}
