// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package http

import (
	"context"

	"github.com/google/uuid"
	"github.com/residwi/go-api-project-template/internal/features/inventory/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockInventoryManager creates a new instance of MockInventoryManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInventoryManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInventoryManager {
	mock := &MockInventoryManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockInventoryManager is an autogenerated mock type for the InventoryManager type
type MockInventoryManager struct {
	mock.Mock
}

type MockInventoryManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInventoryManager) EXPECT() *MockInventoryManager_Expecter {
	return &MockInventoryManager_Expecter{mock: &_m.Mock}
}

// Adjust provides a mock function for the type MockInventoryManager
func (_mock *MockInventoryManager) Adjust(ctx context.Context, productID uuid.UUID, newQuantity int) (*domain.Stock, error) {
	ret := _mock.Called(ctx, productID, newQuantity)

	if len(ret) == 0 {
		panic("no return value specified for Adjust")
	}

	var r0 *domain.Stock
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int) (*domain.Stock, error)); ok {
		return returnFunc(ctx, productID, newQuantity)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int) *domain.Stock); ok {
		r0 = returnFunc(ctx, productID, newQuantity)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Stock)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, int) error); ok {
		r1 = returnFunc(ctx, productID, newQuantity)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockInventoryManager_Adjust_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Adjust'
type MockInventoryManager_Adjust_Call struct {
	*mock.Call
}

// Adjust is a helper method to define mock.On call
//   - ctx context.Context
//   - productID uuid.UUID
//   - newQuantity int
func (_e *MockInventoryManager_Expecter) Adjust(ctx any, productID any, newQuantity any) *MockInventoryManager_Adjust_Call {
	return &MockInventoryManager_Adjust_Call{Call: _e.mock.On("Adjust", ctx, productID, newQuantity)}
}

func (_c *MockInventoryManager_Adjust_Call) Run(run func(ctx context.Context, productID uuid.UUID, newQuantity int)) *MockInventoryManager_Adjust_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockInventoryManager_Adjust_Call) Return(stock *domain.Stock, err error) *MockInventoryManager_Adjust_Call {
	_c.Call.Return(stock, err)
	return _c
}

func (_c *MockInventoryManager_Adjust_Call) RunAndReturn(run func(ctx context.Context, productID uuid.UUID, newQuantity int) (*domain.Stock, error)) *MockInventoryManager_Adjust_Call {
	_c.Call.Return(run)
	return _c
}

// GetStock provides a mock function for the type MockInventoryManager
func (_mock *MockInventoryManager) GetStock(ctx context.Context, productID uuid.UUID) (*domain.Stock, error) {
	ret := _mock.Called(ctx, productID)

	if len(ret) == 0 {
		panic("no return value specified for GetStock")
	}

	var r0 *domain.Stock
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Stock, error)); ok {
		return returnFunc(ctx, productID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Stock); ok {
		r0 = returnFunc(ctx, productID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Stock)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, productID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockInventoryManager_GetStock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStock'
type MockInventoryManager_GetStock_Call struct {
	*mock.Call
}

// GetStock is a helper method to define mock.On call
//   - ctx context.Context
//   - productID uuid.UUID
func (_e *MockInventoryManager_Expecter) GetStock(ctx any, productID any) *MockInventoryManager_GetStock_Call {
	return &MockInventoryManager_GetStock_Call{Call: _e.mock.On("GetStock", ctx, productID)}
}

func (_c *MockInventoryManager_GetStock_Call) Run(run func(ctx context.Context, productID uuid.UUID)) *MockInventoryManager_GetStock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockInventoryManager_GetStock_Call) Return(stock *domain.Stock, err error) *MockInventoryManager_GetStock_Call {
	_c.Call.Return(stock, err)
	return _c
}

func (_c *MockInventoryManager_GetStock_Call) RunAndReturn(run func(ctx context.Context, productID uuid.UUID) (*domain.Stock, error)) *MockInventoryManager_GetStock_Call {
	_c.Call.Return(run)
	return _c
}

// Restock provides a mock function for the type MockInventoryManager
func (_mock *MockInventoryManager) Restock(ctx context.Context, productID uuid.UUID, qty int) (*domain.Stock, error) {
	ret := _mock.Called(ctx, productID, qty)

	if len(ret) == 0 {
		panic("no return value specified for Restock")
	}

	var r0 *domain.Stock
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int) (*domain.Stock, error)); ok {
		return returnFunc(ctx, productID, qty)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int) *domain.Stock); ok {
		r0 = returnFunc(ctx, productID, qty)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Stock)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, int) error); ok {
		r1 = returnFunc(ctx, productID, qty)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockInventoryManager_Restock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Restock'
type MockInventoryManager_Restock_Call struct {
	*mock.Call
}

// Restock is a helper method to define mock.On call
//   - ctx context.Context
//   - productID uuid.UUID
//   - qty int
func (_e *MockInventoryManager_Expecter) Restock(ctx any, productID any, qty any) *MockInventoryManager_Restock_Call {
	return &MockInventoryManager_Restock_Call{Call: _e.mock.On("Restock", ctx, productID, qty)}
}

func (_c *MockInventoryManager_Restock_Call) Run(run func(ctx context.Context, productID uuid.UUID, qty int)) *MockInventoryManager_Restock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockInventoryManager_Restock_Call) Return(stock *domain.Stock, err error) *MockInventoryManager_Restock_Call {
	_c.Call.Return(stock, err)
	return _c
}

func (_c *MockInventoryManager_Restock_Call) RunAndReturn(run func(ctx context.Context, productID uuid.UUID, qty int) (*domain.Stock, error)) *MockInventoryManager_Restock_Call {
	_c.Call.Return(run)
	return _c
}
