// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package http

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCommand creates a new instance of MockCommand. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCommand(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCommand {
	mock := &MockCommand{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCommand is an autogenerated mock type for the Command type
type MockCommand struct {
	mock.Mock
}

type MockCommand_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCommand) EXPECT() *MockCommand_Expecter {
	return &MockCommand_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type MockCommand
func (_mock *MockCommand) Execute(ctx context.Context, paymentID uuid.UUID) error {
	ret := _mock.Called(ctx, paymentID)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, paymentID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCommand_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockCommand_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - paymentID uuid.UUID
func (_e *MockCommand_Expecter) Execute(ctx any, paymentID any) *MockCommand_Execute_Call {
	return &MockCommand_Execute_Call{Call: _e.mock.On("Execute", ctx, paymentID)}
}

func (_c *MockCommand_Execute_Call) Run(run func(ctx context.Context, paymentID uuid.UUID)) *MockCommand_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCommand_Execute_Call) Return(err error) *MockCommand_Execute_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCommand_Execute_Call) RunAndReturn(run func(ctx context.Context, paymentID uuid.UUID) error) *MockCommand_Execute_Call {
	_c.Call.Return(run)
	return _c
}
