// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package http

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"

	"github.com/residwi/go-api-project-template/internal/features/notification/domain"
	"github.com/residwi/go-api-project-template/internal/platform/paging"
)

// NewMockNotificationManager creates a new instance of MockNotificationManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNotificationManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNotificationManager {
	mock := &MockNotificationManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockNotificationManager is an autogenerated mock type for the NotificationManager type
type MockNotificationManager struct {
	mock.Mock
}

type MockNotificationManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNotificationManager) EXPECT() *MockNotificationManager_Expecter {
	return &MockNotificationManager_Expecter{mock: &_m.Mock}
}

// CountUnread provides a mock function for the type MockNotificationManager
func (_mock *MockNotificationManager) CountUnread(ctx context.Context, userID uuid.UUID) (int, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for CountUnread")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (int, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) int); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNotificationManager_CountUnread_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountUnread'
type MockNotificationManager_CountUnread_Call struct {
	*mock.Call
}

// CountUnread is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockNotificationManager_Expecter) CountUnread(ctx any, userID any) *MockNotificationManager_CountUnread_Call {
	return &MockNotificationManager_CountUnread_Call{Call: _e.mock.On("CountUnread", ctx, userID)}
}

func (_c *MockNotificationManager_CountUnread_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockNotificationManager_CountUnread_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNotificationManager_CountUnread_Call) Return(n int, err error) *MockNotificationManager_CountUnread_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockNotificationManager_CountUnread_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) (int, error)) *MockNotificationManager_CountUnread_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockNotificationManager
func (_mock *MockNotificationManager) List(ctx context.Context, userID uuid.UUID, cursor paging.CursorPage) ([]domain.Notification, error) {
	ret := _mock.Called(ctx, userID, cursor)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []domain.Notification
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, paging.CursorPage) ([]domain.Notification, error)); ok {
		return returnFunc(ctx, userID, cursor)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, paging.CursorPage) []domain.Notification); ok {
		r0 = returnFunc(ctx, userID, cursor)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Notification)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, paging.CursorPage) error); ok {
		r1 = returnFunc(ctx, userID, cursor)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNotificationManager_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockNotificationManager_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - cursor paging.CursorPage
func (_e *MockNotificationManager_Expecter) List(ctx any, userID any, cursor any) *MockNotificationManager_List_Call {
	return &MockNotificationManager_List_Call{Call: _e.mock.On("List", ctx, userID, cursor)}
}

func (_c *MockNotificationManager_List_Call) Run(run func(ctx context.Context, userID uuid.UUID, cursor paging.CursorPage)) *MockNotificationManager_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 paging.CursorPage
		if args[2] != nil {
			arg2 = args[2].(paging.CursorPage)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockNotificationManager_List_Call) Return(notifications []domain.Notification, err error) *MockNotificationManager_List_Call {
	_c.Call.Return(notifications, err)
	return _c
}

func (_c *MockNotificationManager_List_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, cursor paging.CursorPage) ([]domain.Notification, error)) *MockNotificationManager_List_Call {
	_c.Call.Return(run)
	return _c
}

// MarkAllRead provides a mock function for the type MockNotificationManager
func (_mock *MockNotificationManager) MarkAllRead(ctx context.Context, userID uuid.UUID) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for MarkAllRead")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNotificationManager_MarkAllRead_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkAllRead'
type MockNotificationManager_MarkAllRead_Call struct {
	*mock.Call
}

// MarkAllRead is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockNotificationManager_Expecter) MarkAllRead(ctx any, userID any) *MockNotificationManager_MarkAllRead_Call {
	return &MockNotificationManager_MarkAllRead_Call{Call: _e.mock.On("MarkAllRead", ctx, userID)}
}

func (_c *MockNotificationManager_MarkAllRead_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockNotificationManager_MarkAllRead_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNotificationManager_MarkAllRead_Call) Return(err error) *MockNotificationManager_MarkAllRead_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNotificationManager_MarkAllRead_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) error) *MockNotificationManager_MarkAllRead_Call {
	_c.Call.Return(run)
	return _c
}

// MarkRead provides a mock function for the type MockNotificationManager
func (_mock *MockNotificationManager) MarkRead(ctx context.Context, userID uuid.UUID, id uuid.UUID) error {
	ret := _mock.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for MarkRead")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, userID, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNotificationManager_MarkRead_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkRead'
type MockNotificationManager_MarkRead_Call struct {
	*mock.Call
}

// MarkRead is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - id uuid.UUID
func (_e *MockNotificationManager_Expecter) MarkRead(ctx any, userID any, id any) *MockNotificationManager_MarkRead_Call {
	return &MockNotificationManager_MarkRead_Call{Call: _e.mock.On("MarkRead", ctx, userID, id)}
}

func (_c *MockNotificationManager_MarkRead_Call) Run(run func(ctx context.Context, userID uuid.UUID, id uuid.UUID)) *MockNotificationManager_MarkRead_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockNotificationManager_MarkRead_Call) Return(err error) *MockNotificationManager_MarkRead_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNotificationManager_MarkRead_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, id uuid.UUID) error) *MockNotificationManager_MarkRead_Call {
	_c.Call.Return(run)
	return _c
}
