// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package http

import (
	"context"

	"github.com/google/uuid"
	"github.com/residwi/go-api-project-template/internal/modules/product/domain"
	"github.com/residwi/go-api-project-template/internal/modules/product/usecase/query"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAdminProductReader creates a new instance of MockAdminProductReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAdminProductReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAdminProductReader {
	mock := &MockAdminProductReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAdminProductReader is an autogenerated mock type for the AdminProductReader type
type MockAdminProductReader struct {
	mock.Mock
}

type MockAdminProductReader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAdminProductReader) EXPECT() *MockAdminProductReader_Expecter {
	return &MockAdminProductReader_Expecter{mock: &_m.Mock}
}

// GetByID provides a mock function for the type MockAdminProductReader
func (_mock *MockAdminProductReader) GetByID(ctx context.Context, id uuid.UUID) (*domain.Product, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Product
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Product, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Product); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Product)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAdminProductReader_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockAdminProductReader_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockAdminProductReader_Expecter) GetByID(ctx any, id any) *MockAdminProductReader_GetByID_Call {
	return &MockAdminProductReader_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockAdminProductReader_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockAdminProductReader_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAdminProductReader_GetByID_Call) Return(product *domain.Product, err error) *MockAdminProductReader_GetByID_Call {
	_c.Call.Return(product, err)
	return _c
}

func (_c *MockAdminProductReader_GetByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*domain.Product, error)) *MockAdminProductReader_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListAdmin provides a mock function for the type MockAdminProductReader
func (_mock *MockAdminProductReader) ListAdmin(ctx context.Context, params query.AdminListParams) ([]domain.Product, int, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for ListAdmin")
	}

	var r0 []domain.Product
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, query.AdminListParams) ([]domain.Product, int, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, query.AdminListParams) []domain.Product); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Product)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, query.AdminListParams) int); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, query.AdminListParams) error); ok {
		r2 = returnFunc(ctx, params)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockAdminProductReader_ListAdmin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAdmin'
type MockAdminProductReader_ListAdmin_Call struct {
	*mock.Call
}

// ListAdmin is a helper method to define mock.On call
//   - ctx context.Context
//   - params query.AdminListParams
func (_e *MockAdminProductReader_Expecter) ListAdmin(ctx any, params any) *MockAdminProductReader_ListAdmin_Call {
	return &MockAdminProductReader_ListAdmin_Call{Call: _e.mock.On("ListAdmin", ctx, params)}
}

func (_c *MockAdminProductReader_ListAdmin_Call) Run(run func(ctx context.Context, params query.AdminListParams)) *MockAdminProductReader_ListAdmin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 query.AdminListParams
		if args[1] != nil {
			arg1 = args[1].(query.AdminListParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAdminProductReader_ListAdmin_Call) Return(products []domain.Product, n int, err error) *MockAdminProductReader_ListAdmin_Call {
	_c.Call.Return(products, n, err)
	return _c
}

func (_c *MockAdminProductReader_ListAdmin_Call) RunAndReturn(run func(ctx context.Context, params query.AdminListParams) ([]domain.Product, int, error)) *MockAdminProductReader_ListAdmin_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockProductReader creates a new instance of MockProductReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProductReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProductReader {
	mock := &MockProductReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProductReader is an autogenerated mock type for the ProductReader type
type MockProductReader struct {
	mock.Mock
}

type MockProductReader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProductReader) EXPECT() *MockProductReader_Expecter {
	return &MockProductReader_Expecter{mock: &_m.Mock}
}

// GetBySlug provides a mock function for the type MockProductReader
func (_mock *MockProductReader) GetBySlug(ctx context.Context, slug string) (*domain.Product, error) {
	ret := _mock.Called(ctx, slug)

	if len(ret) == 0 {
		panic("no return value specified for GetBySlug")
	}

	var r0 *domain.Product
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.Product, error)); ok {
		return returnFunc(ctx, slug)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.Product); ok {
		r0 = returnFunc(ctx, slug)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Product)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, slug)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProductReader_GetBySlug_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBySlug'
type MockProductReader_GetBySlug_Call struct {
	*mock.Call
}

// GetBySlug is a helper method to define mock.On call
//   - ctx context.Context
//   - slug string
func (_e *MockProductReader_Expecter) GetBySlug(ctx any, slug any) *MockProductReader_GetBySlug_Call {
	return &MockProductReader_GetBySlug_Call{Call: _e.mock.On("GetBySlug", ctx, slug)}
}

func (_c *MockProductReader_GetBySlug_Call) Run(run func(ctx context.Context, slug string)) *MockProductReader_GetBySlug_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProductReader_GetBySlug_Call) Return(product *domain.Product, err error) *MockProductReader_GetBySlug_Call {
	_c.Call.Return(product, err)
	return _c
}

func (_c *MockProductReader_GetBySlug_Call) RunAndReturn(run func(ctx context.Context, slug string) (*domain.Product, error)) *MockProductReader_GetBySlug_Call {
	_c.Call.Return(run)
	return _c
}

// ListPublished provides a mock function for the type MockProductReader
func (_mock *MockProductReader) ListPublished(ctx context.Context, params query.PublishedListParams) ([]domain.Product, string, bool, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for ListPublished")
	}

	var r0 []domain.Product
	var r1 string
	var r2 bool
	var r3 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, query.PublishedListParams) ([]domain.Product, string, bool, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, query.PublishedListParams) []domain.Product); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Product)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, query.PublishedListParams) string); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, query.PublishedListParams) bool); ok {
		r2 = returnFunc(ctx, params)
	} else {
		r2 = ret.Get(2).(bool)
	}
	if returnFunc, ok := ret.Get(3).(func(context.Context, query.PublishedListParams) error); ok {
		r3 = returnFunc(ctx, params)
	} else {
		r3 = ret.Error(3)
	}
	return r0, r1, r2, r3
}

// MockProductReader_ListPublished_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPublished'
type MockProductReader_ListPublished_Call struct {
	*mock.Call
}

// ListPublished is a helper method to define mock.On call
//   - ctx context.Context
//   - params query.PublishedListParams
func (_e *MockProductReader_Expecter) ListPublished(ctx any, params any) *MockProductReader_ListPublished_Call {
	return &MockProductReader_ListPublished_Call{Call: _e.mock.On("ListPublished", ctx, params)}
}

func (_c *MockProductReader_ListPublished_Call) Run(run func(ctx context.Context, params query.PublishedListParams)) *MockProductReader_ListPublished_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 query.PublishedListParams
		if args[1] != nil {
			arg1 = args[1].(query.PublishedListParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProductReader_ListPublished_Call) Return(products []domain.Product, s string, b bool, err error) *MockProductReader_ListPublished_Call {
	_c.Call.Return(products, s, b, err)
	return _c
}

func (_c *MockProductReader_ListPublished_Call) RunAndReturn(run func(ctx context.Context, params query.PublishedListParams) ([]domain.Product, string, bool, error)) *MockProductReader_ListPublished_Call {
	_c.Call.Return(run)
	return _c
}
