// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package jobs

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockStaleSweeper creates a new instance of MockStaleSweeper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStaleSweeper(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStaleSweeper {
	mock := &MockStaleSweeper{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStaleSweeper is an autogenerated mock type for the StaleSweeper type
type MockStaleSweeper struct {
	mock.Mock
}

type MockStaleSweeper_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStaleSweeper) EXPECT() *MockStaleSweeper_Expecter {
	return &MockStaleSweeper_Expecter{mock: &_m.Mock}
}

// ExpireStale provides a mock function for the type MockStaleSweeper
func (_mock *MockStaleSweeper) ExpireStale(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ExpireStale")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStaleSweeper_ExpireStale_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExpireStale'
type MockStaleSweeper_ExpireStale_Call struct {
	*mock.Call
}

// ExpireStale is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStaleSweeper_Expecter) ExpireStale(ctx any) *MockStaleSweeper_ExpireStale_Call {
	return &MockStaleSweeper_ExpireStale_Call{Call: _e.mock.On("ExpireStale", ctx)}
}

func (_c *MockStaleSweeper_ExpireStale_Call) Run(run func(ctx context.Context)) *MockStaleSweeper_ExpireStale_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStaleSweeper_ExpireStale_Call) Return(err error) *MockStaleSweeper_ExpireStale_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStaleSweeper_ExpireStale_Call) RunAndReturn(run func(ctx context.Context) error) *MockStaleSweeper_ExpireStale_Call {
	_c.Call.Return(run)
	return _c
}

// RecoverStale provides a mock function for the type MockStaleSweeper
func (_mock *MockStaleSweeper) RecoverStale(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for RecoverStale")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStaleSweeper_RecoverStale_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecoverStale'
type MockStaleSweeper_RecoverStale_Call struct {
	*mock.Call
}

// RecoverStale is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStaleSweeper_Expecter) RecoverStale(ctx any) *MockStaleSweeper_RecoverStale_Call {
	return &MockStaleSweeper_RecoverStale_Call{Call: _e.mock.On("RecoverStale", ctx)}
}

func (_c *MockStaleSweeper_RecoverStale_Call) Run(run func(ctx context.Context)) *MockStaleSweeper_RecoverStale_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStaleSweeper_RecoverStale_Call) Return(err error) *MockStaleSweeper_RecoverStale_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStaleSweeper_RecoverStale_Call) RunAndReturn(run func(ctx context.Context) error) *MockStaleSweeper_RecoverStale_Call {
	_c.Call.Return(run)
	return _c
}
