// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package jobs

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/residwi/go-api-project-template/internal/modules/payment/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockChargeProcessor creates a new instance of MockChargeProcessor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChargeProcessor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChargeProcessor {
	mock := &MockChargeProcessor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockChargeProcessor is an autogenerated mock type for the ChargeProcessor type
type MockChargeProcessor struct {
	mock.Mock
}

type MockChargeProcessor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChargeProcessor) EXPECT() *MockChargeProcessor_Expecter {
	return &MockChargeProcessor_Expecter{mock: &_m.Mock}
}

// ProcessCharge provides a mock function for the type MockChargeProcessor
func (_mock *MockChargeProcessor) ProcessCharge(ctx context.Context, job domain.Job) error {
	ret := _mock.Called(ctx, job)

	if len(ret) == 0 {
		panic("no return value specified for ProcessCharge")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Job) error); ok {
		r0 = returnFunc(ctx, job)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockChargeProcessor_ProcessCharge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProcessCharge'
type MockChargeProcessor_ProcessCharge_Call struct {
	*mock.Call
}

// ProcessCharge is a helper method to define mock.On call
//   - ctx context.Context
//   - job domain.Job
func (_e *MockChargeProcessor_Expecter) ProcessCharge(ctx any, job any) *MockChargeProcessor_ProcessCharge_Call {
	return &MockChargeProcessor_ProcessCharge_Call{Call: _e.mock.On("ProcessCharge", ctx, job)}
}

func (_c *MockChargeProcessor_ProcessCharge_Call) Run(run func(ctx context.Context, job domain.Job)) *MockChargeProcessor_ProcessCharge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Job
		if args[1] != nil {
			arg1 = args[1].(domain.Job)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockChargeProcessor_ProcessCharge_Call) Return(err error) *MockChargeProcessor_ProcessCharge_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockChargeProcessor_ProcessCharge_Call) RunAndReturn(run func(ctx context.Context, job domain.Job) error) *MockChargeProcessor_ProcessCharge_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRefundProcessor creates a new instance of MockRefundProcessor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRefundProcessor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRefundProcessor {
	mock := &MockRefundProcessor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRefundProcessor is an autogenerated mock type for the RefundProcessor type
type MockRefundProcessor struct {
	mock.Mock
}

type MockRefundProcessor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRefundProcessor) EXPECT() *MockRefundProcessor_Expecter {
	return &MockRefundProcessor_Expecter{mock: &_m.Mock}
}

// ProcessRefund provides a mock function for the type MockRefundProcessor
func (_mock *MockRefundProcessor) ProcessRefund(ctx context.Context, job domain.Job) error {
	ret := _mock.Called(ctx, job)

	if len(ret) == 0 {
		panic("no return value specified for ProcessRefund")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Job) error); ok {
		r0 = returnFunc(ctx, job)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRefundProcessor_ProcessRefund_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProcessRefund'
type MockRefundProcessor_ProcessRefund_Call struct {
	*mock.Call
}

// ProcessRefund is a helper method to define mock.On call
//   - ctx context.Context
//   - job domain.Job
func (_e *MockRefundProcessor_Expecter) ProcessRefund(ctx any, job any) *MockRefundProcessor_ProcessRefund_Call {
	return &MockRefundProcessor_ProcessRefund_Call{Call: _e.mock.On("ProcessRefund", ctx, job)}
}

func (_c *MockRefundProcessor_ProcessRefund_Call) Run(run func(ctx context.Context, job domain.Job)) *MockRefundProcessor_ProcessRefund_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Job
		if args[1] != nil {
			arg1 = args[1].(domain.Job)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRefundProcessor_ProcessRefund_Call) Return(err error) *MockRefundProcessor_ProcessRefund_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRefundProcessor_ProcessRefund_Call) RunAndReturn(run func(ctx context.Context, job domain.Job) error) *MockRefundProcessor_ProcessRefund_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// CancelJobsByOrderID provides a mock function for the type MockRepository
func (_mock *MockRepository) CancelJobsByOrderID(ctx context.Context, orderID uuid.UUID) error {
	ret := _mock.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for CancelJobsByOrderID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, orderID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_CancelJobsByOrderID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelJobsByOrderID'
type MockRepository_CancelJobsByOrderID_Call struct {
	*mock.Call
}

// CancelJobsByOrderID is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID uuid.UUID
func (_e *MockRepository_Expecter) CancelJobsByOrderID(ctx any, orderID any) *MockRepository_CancelJobsByOrderID_Call {
	return &MockRepository_CancelJobsByOrderID_Call{Call: _e.mock.On("CancelJobsByOrderID", ctx, orderID)}
}

func (_c *MockRepository_CancelJobsByOrderID_Call) Run(run func(ctx context.Context, orderID uuid.UUID)) *MockRepository_CancelJobsByOrderID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_CancelJobsByOrderID_Call) Return(err error) *MockRepository_CancelJobsByOrderID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_CancelJobsByOrderID_Call) RunAndReturn(run func(ctx context.Context, orderID uuid.UUID) error) *MockRepository_CancelJobsByOrderID_Call {
	_c.Call.Return(run)
	return _c
}

// Claim provides a mock function for the type MockRepository
func (_mock *MockRepository) Claim(ctx context.Context, batchSize int, leaseDuration time.Duration) ([]domain.Job, error) {
	ret := _mock.Called(ctx, batchSize, leaseDuration)

	if len(ret) == 0 {
		panic("no return value specified for Claim")
	}

	var r0 []domain.Job
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, time.Duration) ([]domain.Job, error)); ok {
		return returnFunc(ctx, batchSize, leaseDuration)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, time.Duration) []domain.Job); ok {
		r0 = returnFunc(ctx, batchSize, leaseDuration)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Job)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, time.Duration) error); ok {
		r1 = returnFunc(ctx, batchSize, leaseDuration)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_Claim_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Claim'
type MockRepository_Claim_Call struct {
	*mock.Call
}

// Claim is a helper method to define mock.On call
//   - ctx context.Context
//   - batchSize int
//   - leaseDuration time.Duration
func (_e *MockRepository_Expecter) Claim(ctx any, batchSize any, leaseDuration any) *MockRepository_Claim_Call {
	return &MockRepository_Claim_Call{Call: _e.mock.On("Claim", ctx, batchSize, leaseDuration)}
}

func (_c *MockRepository_Claim_Call) Run(run func(ctx context.Context, batchSize int, leaseDuration time.Duration)) *MockRepository_Claim_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 time.Duration
		if args[2] != nil {
			arg2 = args[2].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_Claim_Call) Return(jobs []domain.Job, err error) *MockRepository_Claim_Call {
	_c.Call.Return(jobs, err)
	return _c
}

func (_c *MockRepository_Claim_Call) RunAndReturn(run func(ctx context.Context, batchSize int, leaseDuration time.Duration) ([]domain.Job, error)) *MockRepository_Claim_Call {
	_c.Call.Return(run)
	return _c
}

// CreateJob provides a mock function for the type MockRepository
func (_mock *MockRepository) CreateJob(ctx context.Context, job *domain.Job) error {
	ret := _mock.Called(ctx, job)

	if len(ret) == 0 {
		panic("no return value specified for CreateJob")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Job) error); ok {
		r0 = returnFunc(ctx, job)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_CreateJob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateJob'
type MockRepository_CreateJob_Call struct {
	*mock.Call
}

// CreateJob is a helper method to define mock.On call
//   - ctx context.Context
//   - job *domain.Job
func (_e *MockRepository_Expecter) CreateJob(ctx any, job any) *MockRepository_CreateJob_Call {
	return &MockRepository_CreateJob_Call{Call: _e.mock.On("CreateJob", ctx, job)}
}

func (_c *MockRepository_CreateJob_Call) Run(run func(ctx context.Context, job *domain.Job)) *MockRepository_CreateJob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Job
		if args[1] != nil {
			arg1 = args[1].(*domain.Job)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_CreateJob_Call) Return(err error) *MockRepository_CreateJob_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_CreateJob_Call) RunAndReturn(run func(ctx context.Context, job *domain.Job) error) *MockRepository_CreateJob_Call {
	_c.Call.Return(run)
	return _c
}

// MarkJobCompleted provides a mock function for the type MockRepository
func (_mock *MockRepository) MarkJobCompleted(ctx context.Context, jobID uuid.UUID) error {
	ret := _mock.Called(ctx, jobID)

	if len(ret) == 0 {
		panic("no return value specified for MarkJobCompleted")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, jobID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_MarkJobCompleted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkJobCompleted'
type MockRepository_MarkJobCompleted_Call struct {
	*mock.Call
}

// MarkJobCompleted is a helper method to define mock.On call
//   - ctx context.Context
//   - jobID uuid.UUID
func (_e *MockRepository_Expecter) MarkJobCompleted(ctx any, jobID any) *MockRepository_MarkJobCompleted_Call {
	return &MockRepository_MarkJobCompleted_Call{Call: _e.mock.On("MarkJobCompleted", ctx, jobID)}
}

func (_c *MockRepository_MarkJobCompleted_Call) Run(run func(ctx context.Context, jobID uuid.UUID)) *MockRepository_MarkJobCompleted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_MarkJobCompleted_Call) Return(err error) *MockRepository_MarkJobCompleted_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_MarkJobCompleted_Call) RunAndReturn(run func(ctx context.Context, jobID uuid.UUID) error) *MockRepository_MarkJobCompleted_Call {
	_c.Call.Return(run)
	return _c
}

// MarkJobCompletedByPaymentID provides a mock function for the type MockRepository
func (_mock *MockRepository) MarkJobCompletedByPaymentID(ctx context.Context, paymentID uuid.UUID, action domain.JobAction) error {
	ret := _mock.Called(ctx, paymentID, action)

	if len(ret) == 0 {
		panic("no return value specified for MarkJobCompletedByPaymentID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, domain.JobAction) error); ok {
		r0 = returnFunc(ctx, paymentID, action)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_MarkJobCompletedByPaymentID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkJobCompletedByPaymentID'
type MockRepository_MarkJobCompletedByPaymentID_Call struct {
	*mock.Call
}

// MarkJobCompletedByPaymentID is a helper method to define mock.On call
//   - ctx context.Context
//   - paymentID uuid.UUID
//   - action domain.JobAction
func (_e *MockRepository_Expecter) MarkJobCompletedByPaymentID(ctx any, paymentID any, action any) *MockRepository_MarkJobCompletedByPaymentID_Call {
	return &MockRepository_MarkJobCompletedByPaymentID_Call{Call: _e.mock.On("MarkJobCompletedByPaymentID", ctx, paymentID, action)}
}

func (_c *MockRepository_MarkJobCompletedByPaymentID_Call) Run(run func(ctx context.Context, paymentID uuid.UUID, action domain.JobAction)) *MockRepository_MarkJobCompletedByPaymentID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 domain.JobAction
		if args[2] != nil {
			arg2 = args[2].(domain.JobAction)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_MarkJobCompletedByPaymentID_Call) Return(err error) *MockRepository_MarkJobCompletedByPaymentID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_MarkJobCompletedByPaymentID_Call) RunAndReturn(run func(ctx context.Context, paymentID uuid.UUID, action domain.JobAction) error) *MockRepository_MarkJobCompletedByPaymentID_Call {
	_c.Call.Return(run)
	return _c
}

// Prune provides a mock function for the type MockRepository
func (_mock *MockRepository) Prune(ctx context.Context, olderThan time.Duration, limit int) (int, error) {
	ret := _mock.Called(ctx, olderThan, limit)

	if len(ret) == 0 {
		panic("no return value specified for Prune")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Duration, int) (int, error)); ok {
		return returnFunc(ctx, olderThan, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Duration, int) int); ok {
		r0 = returnFunc(ctx, olderThan, limit)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, time.Duration, int) error); ok {
		r1 = returnFunc(ctx, olderThan, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_Prune_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Prune'
type MockRepository_Prune_Call struct {
	*mock.Call
}

// Prune is a helper method to define mock.On call
//   - ctx context.Context
//   - olderThan time.Duration
//   - limit int
func (_e *MockRepository_Expecter) Prune(ctx any, olderThan any, limit any) *MockRepository_Prune_Call {
	return &MockRepository_Prune_Call{Call: _e.mock.On("Prune", ctx, olderThan, limit)}
}

func (_c *MockRepository_Prune_Call) Run(run func(ctx context.Context, olderThan time.Duration, limit int)) *MockRepository_Prune_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Duration
		if args[1] != nil {
			arg1 = args[1].(time.Duration)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_Prune_Call) Return(n int, err error) *MockRepository_Prune_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockRepository_Prune_Call) RunAndReturn(run func(ctx context.Context, olderThan time.Duration, limit int) (int, error)) *MockRepository_Prune_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateJob provides a mock function for the type MockRepository
func (_mock *MockRepository) UpdateJob(ctx context.Context, job *domain.Job) error {
	ret := _mock.Called(ctx, job)

	if len(ret) == 0 {
		panic("no return value specified for UpdateJob")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Job) error); ok {
		r0 = returnFunc(ctx, job)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_UpdateJob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateJob'
type MockRepository_UpdateJob_Call struct {
	*mock.Call
}

// UpdateJob is a helper method to define mock.On call
//   - ctx context.Context
//   - job *domain.Job
func (_e *MockRepository_Expecter) UpdateJob(ctx any, job any) *MockRepository_UpdateJob_Call {
	return &MockRepository_UpdateJob_Call{Call: _e.mock.On("UpdateJob", ctx, job)}
}

func (_c *MockRepository_UpdateJob_Call) Run(run func(ctx context.Context, job *domain.Job)) *MockRepository_UpdateJob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Job
		if args[1] != nil {
			arg1 = args[1].(*domain.Job)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_UpdateJob_Call) Return(err error) *MockRepository_UpdateJob_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_UpdateJob_Call) RunAndReturn(run func(ctx context.Context, job *domain.Job) error) *MockRepository_UpdateJob_Call {
	_c.Call.Return(run)
	return _c
}
