// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package http

import (
	"context"

	"github.com/google/uuid"
	"github.com/residwi/go-api-project-template/internal/modules/shipping/create"
	"github.com/residwi/go-api-project-template/internal/modules/shipping/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockShipmentCreator creates a new instance of MockShipmentCreator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockShipmentCreator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockShipmentCreator {
	mock := &MockShipmentCreator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockShipmentCreator is an autogenerated mock type for the ShipmentCreator type
type MockShipmentCreator struct {
	mock.Mock
}

type MockShipmentCreator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockShipmentCreator) EXPECT() *MockShipmentCreator_Expecter {
	return &MockShipmentCreator_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type MockShipmentCreator
func (_mock *MockShipmentCreator) Execute(ctx context.Context, orderID uuid.UUID, p create.Params) (*domain.Shipment, error) {
	ret := _mock.Called(ctx, orderID, p)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *domain.Shipment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, create.Params) (*domain.Shipment, error)); ok {
		return returnFunc(ctx, orderID, p)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, create.Params) *domain.Shipment); ok {
		r0 = returnFunc(ctx, orderID, p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Shipment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, create.Params) error); ok {
		r1 = returnFunc(ctx, orderID, p)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockShipmentCreator_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockShipmentCreator_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID uuid.UUID
//   - p create.Params
func (_e *MockShipmentCreator_Expecter) Execute(ctx any, orderID any, p any) *MockShipmentCreator_Execute_Call {
	return &MockShipmentCreator_Execute_Call{Call: _e.mock.On("Execute", ctx, orderID, p)}
}

func (_c *MockShipmentCreator_Execute_Call) Run(run func(ctx context.Context, orderID uuid.UUID, p create.Params)) *MockShipmentCreator_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 create.Params
		if args[2] != nil {
			arg2 = args[2].(create.Params)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockShipmentCreator_Execute_Call) Return(shipment *domain.Shipment, err error) *MockShipmentCreator_Execute_Call {
	_c.Call.Return(shipment, err)
	return _c
}

func (_c *MockShipmentCreator_Execute_Call) RunAndReturn(run func(ctx context.Context, orderID uuid.UUID, p create.Params) (*domain.Shipment, error)) *MockShipmentCreator_Execute_Call {
	_c.Call.Return(run)
	return _c
}
