// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package query

import (
	"context"

	"github.com/residwi/go-api-project-template/internal/modules/promotion/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// ListAdmin provides a mock function for the type MockRepository
func (_mock *MockRepository) ListAdmin(ctx context.Context, params Params) ([]domain.Promotion, int, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for ListAdmin")
	}

	var r0 []domain.Promotion
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, Params) ([]domain.Promotion, int, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, Params) []domain.Promotion); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Promotion)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, Params) int); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, Params) error); ok {
		r2 = returnFunc(ctx, params)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockRepository_ListAdmin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAdmin'
type MockRepository_ListAdmin_Call struct {
	*mock.Call
}

// ListAdmin is a helper method to define mock.On call
//   - ctx context.Context
//   - params Params
func (_e *MockRepository_Expecter) ListAdmin(ctx any, params any) *MockRepository_ListAdmin_Call {
	return &MockRepository_ListAdmin_Call{Call: _e.mock.On("ListAdmin", ctx, params)}
}

func (_c *MockRepository_ListAdmin_Call) Run(run func(ctx context.Context, params Params)) *MockRepository_ListAdmin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 Params
		if args[1] != nil {
			arg1 = args[1].(Params)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_ListAdmin_Call) Return(promotions []domain.Promotion, n int, err error) *MockRepository_ListAdmin_Call {
	_c.Call.Return(promotions, n, err)
	return _c
}

func (_c *MockRepository_ListAdmin_Call) RunAndReturn(run func(ctx context.Context, params Params) ([]domain.Promotion, int, error)) *MockRepository_ListAdmin_Call {
	_c.Call.Return(run)
	return _c
}
