// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package http

import (
	"context"

	"github.com/google/uuid"
	"github.com/residwi/go-api-project-template/internal/modules/checkout"
	"github.com/residwi/go-api-project-template/internal/modules/order/domain"
	"github.com/residwi/go-api-project-template/internal/modules/payment/contract"
	mock "github.com/stretchr/testify/mock"
)

// NewMockOrderCanceller creates a new instance of MockOrderCanceller. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderCanceller(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderCanceller {
	mock := &MockOrderCanceller{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOrderCanceller is an autogenerated mock type for the OrderCanceller type
type MockOrderCanceller struct {
	mock.Mock
}

type MockOrderCanceller_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderCanceller) EXPECT() *MockOrderCanceller_Expecter {
	return &MockOrderCanceller_Expecter{mock: &_m.Mock}
}

// CancelOrder provides a mock function for the type MockOrderCanceller
func (_mock *MockOrderCanceller) CancelOrder(ctx context.Context, userID uuid.UUID, orderID uuid.UUID) error {
	ret := _mock.Called(ctx, userID, orderID)

	if len(ret) == 0 {
		panic("no return value specified for CancelOrder")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, userID, orderID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOrderCanceller_CancelOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelOrder'
type MockOrderCanceller_CancelOrder_Call struct {
	*mock.Call
}

// CancelOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - orderID uuid.UUID
func (_e *MockOrderCanceller_Expecter) CancelOrder(ctx any, userID any, orderID any) *MockOrderCanceller_CancelOrder_Call {
	return &MockOrderCanceller_CancelOrder_Call{Call: _e.mock.On("CancelOrder", ctx, userID, orderID)}
}

func (_c *MockOrderCanceller_CancelOrder_Call) Run(run func(ctx context.Context, userID uuid.UUID, orderID uuid.UUID)) *MockOrderCanceller_CancelOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockOrderCanceller_CancelOrder_Call) Return(err error) *MockOrderCanceller_CancelOrder_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOrderCanceller_CancelOrder_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, orderID uuid.UUID) error) *MockOrderCanceller_CancelOrder_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOrderPlacer creates a new instance of MockOrderPlacer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderPlacer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderPlacer {
	mock := &MockOrderPlacer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOrderPlacer is an autogenerated mock type for the OrderPlacer type
type MockOrderPlacer struct {
	mock.Mock
}

type MockOrderPlacer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderPlacer) EXPECT() *MockOrderPlacer_Expecter {
	return &MockOrderPlacer_Expecter{mock: &_m.Mock}
}

// PlaceOrder provides a mock function for the type MockOrderPlacer
func (_mock *MockOrderPlacer) PlaceOrder(ctx context.Context, userID uuid.UUID, in checkout.PlaceOrderInput) (*domain.Order, error) {
	ret := _mock.Called(ctx, userID, in)

	if len(ret) == 0 {
		panic("no return value specified for PlaceOrder")
	}

	var r0 *domain.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, checkout.PlaceOrderInput) (*domain.Order, error)); ok {
		return returnFunc(ctx, userID, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, checkout.PlaceOrderInput) *domain.Order); ok {
		r0 = returnFunc(ctx, userID, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, checkout.PlaceOrderInput) error); ok {
		r1 = returnFunc(ctx, userID, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderPlacer_PlaceOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PlaceOrder'
type MockOrderPlacer_PlaceOrder_Call struct {
	*mock.Call
}

// PlaceOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - in checkout.PlaceOrderInput
func (_e *MockOrderPlacer_Expecter) PlaceOrder(ctx any, userID any, in any) *MockOrderPlacer_PlaceOrder_Call {
	return &MockOrderPlacer_PlaceOrder_Call{Call: _e.mock.On("PlaceOrder", ctx, userID, in)}
}

func (_c *MockOrderPlacer_PlaceOrder_Call) Run(run func(ctx context.Context, userID uuid.UUID, in checkout.PlaceOrderInput)) *MockOrderPlacer_PlaceOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 checkout.PlaceOrderInput
		if args[2] != nil {
			arg2 = args[2].(checkout.PlaceOrderInput)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockOrderPlacer_PlaceOrder_Call) Return(order *domain.Order, err error) *MockOrderPlacer_PlaceOrder_Call {
	_c.Call.Return(order, err)
	return _c
}

func (_c *MockOrderPlacer_PlaceOrder_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, in checkout.PlaceOrderInput) (*domain.Order, error)) *MockOrderPlacer_PlaceOrder_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPaymentRetrier creates a new instance of MockPaymentRetrier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPaymentRetrier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPaymentRetrier {
	mock := &MockPaymentRetrier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPaymentRetrier is an autogenerated mock type for the PaymentRetrier type
type MockPaymentRetrier struct {
	mock.Mock
}

type MockPaymentRetrier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPaymentRetrier) EXPECT() *MockPaymentRetrier_Expecter {
	return &MockPaymentRetrier_Expecter{mock: &_m.Mock}
}

// RetryPayment provides a mock function for the type MockPaymentRetrier
func (_mock *MockPaymentRetrier) RetryPayment(ctx context.Context, userID uuid.UUID, orderID uuid.UUID, paymentMethodID string) (contract.ChargeResult, error) {
	ret := _mock.Called(ctx, userID, orderID, paymentMethodID)

	if len(ret) == 0 {
		panic("no return value specified for RetryPayment")
	}

	var r0 contract.ChargeResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string) (contract.ChargeResult, error)); ok {
		return returnFunc(ctx, userID, orderID, paymentMethodID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string) contract.ChargeResult); ok {
		r0 = returnFunc(ctx, userID, orderID, paymentMethodID)
	} else {
		r0 = ret.Get(0).(contract.ChargeResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, string) error); ok {
		r1 = returnFunc(ctx, userID, orderID, paymentMethodID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPaymentRetrier_RetryPayment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RetryPayment'
type MockPaymentRetrier_RetryPayment_Call struct {
	*mock.Call
}

// RetryPayment is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - orderID uuid.UUID
//   - paymentMethodID string
func (_e *MockPaymentRetrier_Expecter) RetryPayment(ctx any, userID any, orderID any, paymentMethodID any) *MockPaymentRetrier_RetryPayment_Call {
	return &MockPaymentRetrier_RetryPayment_Call{Call: _e.mock.On("RetryPayment", ctx, userID, orderID, paymentMethodID)}
}

func (_c *MockPaymentRetrier_RetryPayment_Call) Run(run func(ctx context.Context, userID uuid.UUID, orderID uuid.UUID, paymentMethodID string)) *MockPaymentRetrier_RetryPayment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockPaymentRetrier_RetryPayment_Call) Return(chargeResult contract.ChargeResult, err error) *MockPaymentRetrier_RetryPayment_Call {
	_c.Call.Return(chargeResult, err)
	return _c
}

func (_c *MockPaymentRetrier_RetryPayment_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, orderID uuid.UUID, paymentMethodID string) (contract.ChargeResult, error)) *MockPaymentRetrier_RetryPayment_Call {
	_c.Call.Return(run)
	return _c
}
