// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package http

import (
	"context"

	"github.com/residwi/go-api-project-template/internal/modules/category/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCategoryReader creates a new instance of MockCategoryReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCategoryReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCategoryReader {
	mock := &MockCategoryReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCategoryReader is an autogenerated mock type for the CategoryReader type
type MockCategoryReader struct {
	mock.Mock
}

type MockCategoryReader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCategoryReader) EXPECT() *MockCategoryReader_Expecter {
	return &MockCategoryReader_Expecter{mock: &_m.Mock}
}

// GetBySlug provides a mock function for the type MockCategoryReader
func (_mock *MockCategoryReader) GetBySlug(ctx context.Context, slug string) (*domain.Category, error) {
	ret := _mock.Called(ctx, slug)

	if len(ret) == 0 {
		panic("no return value specified for GetBySlug")
	}

	var r0 *domain.Category
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.Category, error)); ok {
		return returnFunc(ctx, slug)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.Category); ok {
		r0 = returnFunc(ctx, slug)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Category)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, slug)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCategoryReader_GetBySlug_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBySlug'
type MockCategoryReader_GetBySlug_Call struct {
	*mock.Call
}

// GetBySlug is a helper method to define mock.On call
//   - ctx context.Context
//   - slug string
func (_e *MockCategoryReader_Expecter) GetBySlug(ctx any, slug any) *MockCategoryReader_GetBySlug_Call {
	return &MockCategoryReader_GetBySlug_Call{Call: _e.mock.On("GetBySlug", ctx, slug)}
}

func (_c *MockCategoryReader_GetBySlug_Call) Run(run func(ctx context.Context, slug string)) *MockCategoryReader_GetBySlug_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCategoryReader_GetBySlug_Call) Return(category *domain.Category, err error) *MockCategoryReader_GetBySlug_Call {
	_c.Call.Return(category, err)
	return _c
}

func (_c *MockCategoryReader_GetBySlug_Call) RunAndReturn(run func(ctx context.Context, slug string) (*domain.Category, error)) *MockCategoryReader_GetBySlug_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockCategoryReader
func (_mock *MockCategoryReader) List(ctx context.Context) ([]domain.Category, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []domain.Category
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]domain.Category, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []domain.Category); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Category)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCategoryReader_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockCategoryReader_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockCategoryReader_Expecter) List(ctx any) *MockCategoryReader_List_Call {
	return &MockCategoryReader_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockCategoryReader_List_Call) Run(run func(ctx context.Context)) *MockCategoryReader_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCategoryReader_List_Call) Return(categorys []domain.Category, err error) *MockCategoryReader_List_Call {
	_c.Call.Return(categorys, err)
	return _c
}

func (_c *MockCategoryReader_List_Call) RunAndReturn(run func(ctx context.Context) ([]domain.Category, error)) *MockCategoryReader_List_Call {
	_c.Call.Return(run)
	return _c
}
