// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/residwi/go-api-project-template/internal/platform/payment"
	mock "github.com/stretchr/testify/mock"
)

// NewMockGateway creates a new instance of MockGateway. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGateway(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGateway {
	mock := &MockGateway{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGateway is an autogenerated mock type for the Gateway type
type MockGateway struct {
	mock.Mock
}

type MockGateway_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGateway) EXPECT() *MockGateway_Expecter {
	return &MockGateway_Expecter{mock: &_m.Mock}
}

// Charge provides a mock function for the type MockGateway
func (_mock *MockGateway) Charge(ctx context.Context, req payment.ChargeRequest) (payment.ChargeResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Charge")
	}

	var r0 payment.ChargeResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, payment.ChargeRequest) (payment.ChargeResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, payment.ChargeRequest) payment.ChargeResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Get(0).(payment.ChargeResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, payment.ChargeRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGateway_Charge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Charge'
type MockGateway_Charge_Call struct {
	*mock.Call
}

// Charge is a helper method to define mock.On call
//   - ctx context.Context
//   - req payment.ChargeRequest
func (_e *MockGateway_Expecter) Charge(ctx interface{}, req interface{}) *MockGateway_Charge_Call {
	return &MockGateway_Charge_Call{Call: _e.mock.On("Charge", ctx, req)}
}

func (_c *MockGateway_Charge_Call) Run(run func(ctx context.Context, req payment.ChargeRequest)) *MockGateway_Charge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 payment.ChargeRequest
		if args[1] != nil {
			arg1 = args[1].(payment.ChargeRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGateway_Charge_Call) Return(chargeResponse payment.ChargeResponse, err error) *MockGateway_Charge_Call {
	_c.Call.Return(chargeResponse, err)
	return _c
}

func (_c *MockGateway_Charge_Call) RunAndReturn(run func(ctx context.Context, req payment.ChargeRequest) (payment.ChargeResponse, error)) *MockGateway_Charge_Call {
	_c.Call.Return(run)
	return _c
}

// Refund provides a mock function for the type MockGateway
func (_mock *MockGateway) Refund(ctx context.Context, req payment.RefundRequest) (payment.RefundResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Refund")
	}

	var r0 payment.RefundResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, payment.RefundRequest) (payment.RefundResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, payment.RefundRequest) payment.RefundResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Get(0).(payment.RefundResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, payment.RefundRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGateway_Refund_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Refund'
type MockGateway_Refund_Call struct {
	*mock.Call
}

// Refund is a helper method to define mock.On call
//   - ctx context.Context
//   - req payment.RefundRequest
func (_e *MockGateway_Expecter) Refund(ctx interface{}, req interface{}) *MockGateway_Refund_Call {
	return &MockGateway_Refund_Call{Call: _e.mock.On("Refund", ctx, req)}
}

func (_c *MockGateway_Refund_Call) Run(run func(ctx context.Context, req payment.RefundRequest)) *MockGateway_Refund_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 payment.RefundRequest
		if args[1] != nil {
			arg1 = args[1].(payment.RefundRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGateway_Refund_Call) Return(refundResponse payment.RefundResponse, err error) *MockGateway_Refund_Call {
	_c.Call.Return(refundResponse, err)
	return _c
}

func (_c *MockGateway_Refund_Call) RunAndReturn(run func(ctx context.Context, req payment.RefundRequest) (payment.RefundResponse, error)) *MockGateway_Refund_Call {
	_c.Call.Return(run)
	return _c
}
