// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/residwi/go-api-project-template/internal/features/payment"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// CancelJobsByOrderID provides a mock function for the type MockRepository
func (_mock *MockRepository) CancelJobsByOrderID(ctx context.Context, orderID uuid.UUID) error {
	ret := _mock.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for CancelJobsByOrderID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, orderID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_CancelJobsByOrderID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelJobsByOrderID'
type MockRepository_CancelJobsByOrderID_Call struct {
	*mock.Call
}

// CancelJobsByOrderID is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID uuid.UUID
func (_e *MockRepository_Expecter) CancelJobsByOrderID(ctx interface{}, orderID interface{}) *MockRepository_CancelJobsByOrderID_Call {
	return &MockRepository_CancelJobsByOrderID_Call{Call: _e.mock.On("CancelJobsByOrderID", ctx, orderID)}
}

func (_c *MockRepository_CancelJobsByOrderID_Call) Run(run func(ctx context.Context, orderID uuid.UUID)) *MockRepository_CancelJobsByOrderID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_CancelJobsByOrderID_Call) Return(err error) *MockRepository_CancelJobsByOrderID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_CancelJobsByOrderID_Call) RunAndReturn(run func(ctx context.Context, orderID uuid.UUID) error) *MockRepository_CancelJobsByOrderID_Call {
	_c.Call.Return(run)
	return _c
}

// ClaimPendingJobs provides a mock function for the type MockRepository
func (_mock *MockRepository) ClaimPendingJobs(ctx context.Context, batchSize int, leaseDuration time.Duration) ([]payment.Job, error) {
	ret := _mock.Called(ctx, batchSize, leaseDuration)

	if len(ret) == 0 {
		panic("no return value specified for ClaimPendingJobs")
	}

	var r0 []payment.Job
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, time.Duration) ([]payment.Job, error)); ok {
		return returnFunc(ctx, batchSize, leaseDuration)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, time.Duration) []payment.Job); ok {
		r0 = returnFunc(ctx, batchSize, leaseDuration)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]payment.Job)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, time.Duration) error); ok {
		r1 = returnFunc(ctx, batchSize, leaseDuration)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_ClaimPendingJobs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClaimPendingJobs'
type MockRepository_ClaimPendingJobs_Call struct {
	*mock.Call
}

// ClaimPendingJobs is a helper method to define mock.On call
//   - ctx context.Context
//   - batchSize int
//   - leaseDuration time.Duration
func (_e *MockRepository_Expecter) ClaimPendingJobs(ctx interface{}, batchSize interface{}, leaseDuration interface{}) *MockRepository_ClaimPendingJobs_Call {
	return &MockRepository_ClaimPendingJobs_Call{Call: _e.mock.On("ClaimPendingJobs", ctx, batchSize, leaseDuration)}
}

func (_c *MockRepository_ClaimPendingJobs_Call) Run(run func(ctx context.Context, batchSize int, leaseDuration time.Duration)) *MockRepository_ClaimPendingJobs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 time.Duration
		if args[2] != nil {
			arg2 = args[2].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_ClaimPendingJobs_Call) Return(paymentJobs []payment.Job, err error) *MockRepository_ClaimPendingJobs_Call {
	_c.Call.Return(paymentJobs, err)
	return _c
}

func (_c *MockRepository_ClaimPendingJobs_Call) RunAndReturn(run func(ctx context.Context, batchSize int, leaseDuration time.Duration) ([]payment.Job, error)) *MockRepository_ClaimPendingJobs_Call {
	_c.Call.Return(run)
	return _c
}

// ClearPaymentURL provides a mock function for the type MockRepository
func (_mock *MockRepository) ClearPaymentURL(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for ClearPaymentURL")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_ClearPaymentURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClearPaymentURL'
type MockRepository_ClearPaymentURL_Call struct {
	*mock.Call
}

// ClearPaymentURL is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockRepository_Expecter) ClearPaymentURL(ctx interface{}, id interface{}) *MockRepository_ClearPaymentURL_Call {
	return &MockRepository_ClearPaymentURL_Call{Call: _e.mock.On("ClearPaymentURL", ctx, id)}
}

func (_c *MockRepository_ClearPaymentURL_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockRepository_ClearPaymentURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_ClearPaymentURL_Call) Return(err error) *MockRepository_ClearPaymentURL_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_ClearPaymentURL_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *MockRepository_ClearPaymentURL_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockRepository
func (_mock *MockRepository) Create(ctx context.Context, p *payment.Payment) error {
	ret := _mock.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *payment.Payment) error); ok {
		r0 = returnFunc(ctx, p)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - p *payment.Payment
func (_e *MockRepository_Expecter) Create(ctx interface{}, p interface{}) *MockRepository_Create_Call {
	return &MockRepository_Create_Call{Call: _e.mock.On("Create", ctx, p)}
}

func (_c *MockRepository_Create_Call) Run(run func(ctx context.Context, p *payment.Payment)) *MockRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *payment.Payment
		if args[1] != nil {
			arg1 = args[1].(*payment.Payment)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Create_Call) Return(err error) *MockRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Create_Call) RunAndReturn(run func(ctx context.Context, p *payment.Payment) error) *MockRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateJob provides a mock function for the type MockRepository
func (_mock *MockRepository) CreateJob(ctx context.Context, job *payment.Job) error {
	ret := _mock.Called(ctx, job)

	if len(ret) == 0 {
		panic("no return value specified for CreateJob")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *payment.Job) error); ok {
		r0 = returnFunc(ctx, job)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_CreateJob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateJob'
type MockRepository_CreateJob_Call struct {
	*mock.Call
}

// CreateJob is a helper method to define mock.On call
//   - ctx context.Context
//   - job *payment.Job
func (_e *MockRepository_Expecter) CreateJob(ctx interface{}, job interface{}) *MockRepository_CreateJob_Call {
	return &MockRepository_CreateJob_Call{Call: _e.mock.On("CreateJob", ctx, job)}
}

func (_c *MockRepository_CreateJob_Call) Run(run func(ctx context.Context, job *payment.Job)) *MockRepository_CreateJob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *payment.Job
		if args[1] != nil {
			arg1 = args[1].(*payment.Job)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_CreateJob_Call) Return(err error) *MockRepository_CreateJob_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_CreateJob_Call) RunAndReturn(run func(ctx context.Context, job *payment.Job) error) *MockRepository_CreateJob_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteOldCompletedJobs provides a mock function for the type MockRepository
func (_mock *MockRepository) DeleteOldCompletedJobs(ctx context.Context, olderThan time.Duration, limit int) (int, error) {
	ret := _mock.Called(ctx, olderThan, limit)

	if len(ret) == 0 {
		panic("no return value specified for DeleteOldCompletedJobs")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Duration, int) (int, error)); ok {
		return returnFunc(ctx, olderThan, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Duration, int) int); ok {
		r0 = returnFunc(ctx, olderThan, limit)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, time.Duration, int) error); ok {
		r1 = returnFunc(ctx, olderThan, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_DeleteOldCompletedJobs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteOldCompletedJobs'
type MockRepository_DeleteOldCompletedJobs_Call struct {
	*mock.Call
}

// DeleteOldCompletedJobs is a helper method to define mock.On call
//   - ctx context.Context
//   - olderThan time.Duration
//   - limit int
func (_e *MockRepository_Expecter) DeleteOldCompletedJobs(ctx interface{}, olderThan interface{}, limit interface{}) *MockRepository_DeleteOldCompletedJobs_Call {
	return &MockRepository_DeleteOldCompletedJobs_Call{Call: _e.mock.On("DeleteOldCompletedJobs", ctx, olderThan, limit)}
}

func (_c *MockRepository_DeleteOldCompletedJobs_Call) Run(run func(ctx context.Context, olderThan time.Duration, limit int)) *MockRepository_DeleteOldCompletedJobs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Duration
		if args[1] != nil {
			arg1 = args[1].(time.Duration)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_DeleteOldCompletedJobs_Call) Return(n int, err error) *MockRepository_DeleteOldCompletedJobs_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockRepository_DeleteOldCompletedJobs_Call) RunAndReturn(run func(ctx context.Context, olderThan time.Duration, limit int) (int, error)) *MockRepository_DeleteOldCompletedJobs_Call {
	_c.Call.Return(run)
	return _c
}

// GetActiveByOrderID provides a mock function for the type MockRepository
func (_mock *MockRepository) GetActiveByOrderID(ctx context.Context, orderID uuid.UUID) (*payment.Payment, error) {
	ret := _mock.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for GetActiveByOrderID")
	}

	var r0 *payment.Payment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*payment.Payment, error)); ok {
		return returnFunc(ctx, orderID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *payment.Payment); ok {
		r0 = returnFunc(ctx, orderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*payment.Payment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, orderID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetActiveByOrderID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActiveByOrderID'
type MockRepository_GetActiveByOrderID_Call struct {
	*mock.Call
}

// GetActiveByOrderID is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID uuid.UUID
func (_e *MockRepository_Expecter) GetActiveByOrderID(ctx interface{}, orderID interface{}) *MockRepository_GetActiveByOrderID_Call {
	return &MockRepository_GetActiveByOrderID_Call{Call: _e.mock.On("GetActiveByOrderID", ctx, orderID)}
}

func (_c *MockRepository_GetActiveByOrderID_Call) Run(run func(ctx context.Context, orderID uuid.UUID)) *MockRepository_GetActiveByOrderID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetActiveByOrderID_Call) Return(payment1 *payment.Payment, err error) *MockRepository_GetActiveByOrderID_Call {
	_c.Call.Return(payment1, err)
	return _c
}

func (_c *MockRepository_GetActiveByOrderID_Call) RunAndReturn(run func(ctx context.Context, orderID uuid.UUID) (*payment.Payment, error)) *MockRepository_GetActiveByOrderID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByGatewayTxnID provides a mock function for the type MockRepository
func (_mock *MockRepository) GetByGatewayTxnID(ctx context.Context, txnID string) (*payment.Payment, error) {
	ret := _mock.Called(ctx, txnID)

	if len(ret) == 0 {
		panic("no return value specified for GetByGatewayTxnID")
	}

	var r0 *payment.Payment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*payment.Payment, error)); ok {
		return returnFunc(ctx, txnID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *payment.Payment); ok {
		r0 = returnFunc(ctx, txnID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*payment.Payment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, txnID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetByGatewayTxnID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByGatewayTxnID'
type MockRepository_GetByGatewayTxnID_Call struct {
	*mock.Call
}

// GetByGatewayTxnID is a helper method to define mock.On call
//   - ctx context.Context
//   - txnID string
func (_e *MockRepository_Expecter) GetByGatewayTxnID(ctx interface{}, txnID interface{}) *MockRepository_GetByGatewayTxnID_Call {
	return &MockRepository_GetByGatewayTxnID_Call{Call: _e.mock.On("GetByGatewayTxnID", ctx, txnID)}
}

func (_c *MockRepository_GetByGatewayTxnID_Call) Run(run func(ctx context.Context, txnID string)) *MockRepository_GetByGatewayTxnID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetByGatewayTxnID_Call) Return(payment1 *payment.Payment, err error) *MockRepository_GetByGatewayTxnID_Call {
	_c.Call.Return(payment1, err)
	return _c
}

func (_c *MockRepository_GetByGatewayTxnID_Call) RunAndReturn(run func(ctx context.Context, txnID string) (*payment.Payment, error)) *MockRepository_GetByGatewayTxnID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockRepository
func (_mock *MockRepository) GetByID(ctx context.Context, id uuid.UUID) (*payment.Payment, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *payment.Payment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*payment.Payment, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *payment.Payment); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*payment.Payment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockRepository_GetByID_Call {
	return &MockRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetByID_Call) Return(payment1 *payment.Payment, err error) *MockRepository_GetByID_Call {
	_c.Call.Return(payment1, err)
	return _c
}

func (_c *MockRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*payment.Payment, error)) *MockRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListAdmin provides a mock function for the type MockRepository
func (_mock *MockRepository) ListAdmin(ctx context.Context, params payment.AdminListParams) ([]payment.Payment, int, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for ListAdmin")
	}

	var r0 []payment.Payment
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, payment.AdminListParams) ([]payment.Payment, int, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, payment.AdminListParams) []payment.Payment); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]payment.Payment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, payment.AdminListParams) int); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, payment.AdminListParams) error); ok {
		r2 = returnFunc(ctx, params)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockRepository_ListAdmin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAdmin'
type MockRepository_ListAdmin_Call struct {
	*mock.Call
}

// ListAdmin is a helper method to define mock.On call
//   - ctx context.Context
//   - params payment.AdminListParams
func (_e *MockRepository_Expecter) ListAdmin(ctx interface{}, params interface{}) *MockRepository_ListAdmin_Call {
	return &MockRepository_ListAdmin_Call{Call: _e.mock.On("ListAdmin", ctx, params)}
}

func (_c *MockRepository_ListAdmin_Call) Run(run func(ctx context.Context, params payment.AdminListParams)) *MockRepository_ListAdmin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 payment.AdminListParams
		if args[1] != nil {
			arg1 = args[1].(payment.AdminListParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_ListAdmin_Call) Return(payments []payment.Payment, n int, err error) *MockRepository_ListAdmin_Call {
	_c.Call.Return(payments, n, err)
	return _c
}

func (_c *MockRepository_ListAdmin_Call) RunAndReturn(run func(ctx context.Context, params payment.AdminListParams) ([]payment.Payment, int, error)) *MockRepository_ListAdmin_Call {
	_c.Call.Return(run)
	return _c
}

// ListByOrderID provides a mock function for the type MockRepository
func (_mock *MockRepository) ListByOrderID(ctx context.Context, orderID uuid.UUID) ([]payment.Payment, error) {
	ret := _mock.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for ListByOrderID")
	}

	var r0 []payment.Payment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]payment.Payment, error)); ok {
		return returnFunc(ctx, orderID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []payment.Payment); ok {
		r0 = returnFunc(ctx, orderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]payment.Payment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, orderID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_ListByOrderID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByOrderID'
type MockRepository_ListByOrderID_Call struct {
	*mock.Call
}

// ListByOrderID is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID uuid.UUID
func (_e *MockRepository_Expecter) ListByOrderID(ctx interface{}, orderID interface{}) *MockRepository_ListByOrderID_Call {
	return &MockRepository_ListByOrderID_Call{Call: _e.mock.On("ListByOrderID", ctx, orderID)}
}

func (_c *MockRepository_ListByOrderID_Call) Run(run func(ctx context.Context, orderID uuid.UUID)) *MockRepository_ListByOrderID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_ListByOrderID_Call) Return(payments []payment.Payment, err error) *MockRepository_ListByOrderID_Call {
	_c.Call.Return(payments, err)
	return _c
}

func (_c *MockRepository_ListByOrderID_Call) RunAndReturn(run func(ctx context.Context, orderID uuid.UUID) ([]payment.Payment, error)) *MockRepository_ListByOrderID_Call {
	_c.Call.Return(run)
	return _c
}

// MarkJobCompleted provides a mock function for the type MockRepository
func (_mock *MockRepository) MarkJobCompleted(ctx context.Context, jobID uuid.UUID) error {
	ret := _mock.Called(ctx, jobID)

	if len(ret) == 0 {
		panic("no return value specified for MarkJobCompleted")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, jobID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_MarkJobCompleted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkJobCompleted'
type MockRepository_MarkJobCompleted_Call struct {
	*mock.Call
}

// MarkJobCompleted is a helper method to define mock.On call
//   - ctx context.Context
//   - jobID uuid.UUID
func (_e *MockRepository_Expecter) MarkJobCompleted(ctx interface{}, jobID interface{}) *MockRepository_MarkJobCompleted_Call {
	return &MockRepository_MarkJobCompleted_Call{Call: _e.mock.On("MarkJobCompleted", ctx, jobID)}
}

func (_c *MockRepository_MarkJobCompleted_Call) Run(run func(ctx context.Context, jobID uuid.UUID)) *MockRepository_MarkJobCompleted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_MarkJobCompleted_Call) Return(err error) *MockRepository_MarkJobCompleted_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_MarkJobCompleted_Call) RunAndReturn(run func(ctx context.Context, jobID uuid.UUID) error) *MockRepository_MarkJobCompleted_Call {
	_c.Call.Return(run)
	return _c
}

// MarkJobCompletedByPaymentID provides a mock function for the type MockRepository
func (_mock *MockRepository) MarkJobCompletedByPaymentID(ctx context.Context, paymentID uuid.UUID, action payment.JobAction) error {
	ret := _mock.Called(ctx, paymentID, action)

	if len(ret) == 0 {
		panic("no return value specified for MarkJobCompletedByPaymentID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, payment.JobAction) error); ok {
		r0 = returnFunc(ctx, paymentID, action)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_MarkJobCompletedByPaymentID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkJobCompletedByPaymentID'
type MockRepository_MarkJobCompletedByPaymentID_Call struct {
	*mock.Call
}

// MarkJobCompletedByPaymentID is a helper method to define mock.On call
//   - ctx context.Context
//   - paymentID uuid.UUID
//   - action payment.JobAction
func (_e *MockRepository_Expecter) MarkJobCompletedByPaymentID(ctx interface{}, paymentID interface{}, action interface{}) *MockRepository_MarkJobCompletedByPaymentID_Call {
	return &MockRepository_MarkJobCompletedByPaymentID_Call{Call: _e.mock.On("MarkJobCompletedByPaymentID", ctx, paymentID, action)}
}

func (_c *MockRepository_MarkJobCompletedByPaymentID_Call) Run(run func(ctx context.Context, paymentID uuid.UUID, action payment.JobAction)) *MockRepository_MarkJobCompletedByPaymentID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 payment.JobAction
		if args[2] != nil {
			arg2 = args[2].(payment.JobAction)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_MarkJobCompletedByPaymentID_Call) Return(err error) *MockRepository_MarkJobCompletedByPaymentID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_MarkJobCompletedByPaymentID_Call) RunAndReturn(run func(ctx context.Context, paymentID uuid.UUID, action payment.JobAction) error) *MockRepository_MarkJobCompletedByPaymentID_Call {
	_c.Call.Return(run)
	return _c
}

// MarkPaid provides a mock function for the type MockRepository
func (_mock *MockRepository) MarkPaid(ctx context.Context, id uuid.UUID, fromStatuses []payment.Status) error {
	ret := _mock.Called(ctx, id, fromStatuses)

	if len(ret) == 0 {
		panic("no return value specified for MarkPaid")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, []payment.Status) error); ok {
		r0 = returnFunc(ctx, id, fromStatuses)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_MarkPaid_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkPaid'
type MockRepository_MarkPaid_Call struct {
	*mock.Call
}

// MarkPaid is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - fromStatuses []payment.Status
func (_e *MockRepository_Expecter) MarkPaid(ctx interface{}, id interface{}, fromStatuses interface{}) *MockRepository_MarkPaid_Call {
	return &MockRepository_MarkPaid_Call{Call: _e.mock.On("MarkPaid", ctx, id, fromStatuses)}
}

func (_c *MockRepository_MarkPaid_Call) Run(run func(ctx context.Context, id uuid.UUID, fromStatuses []payment.Status)) *MockRepository_MarkPaid_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 []payment.Status
		if args[2] != nil {
			arg2 = args[2].([]payment.Status)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_MarkPaid_Call) Return(err error) *MockRepository_MarkPaid_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_MarkPaid_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, fromStatuses []payment.Status) error) *MockRepository_MarkPaid_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateGateway provides a mock function for the type MockRepository
func (_mock *MockRepository) UpdateGateway(ctx context.Context, id uuid.UUID, txnID string, response []byte) error {
	ret := _mock.Called(ctx, id, txnID, response)

	if len(ret) == 0 {
		panic("no return value specified for UpdateGateway")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, []byte) error); ok {
		r0 = returnFunc(ctx, id, txnID, response)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_UpdateGateway_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateGateway'
type MockRepository_UpdateGateway_Call struct {
	*mock.Call
}

// UpdateGateway is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - txnID string
//   - response []byte
func (_e *MockRepository_Expecter) UpdateGateway(ctx interface{}, id interface{}, txnID interface{}, response interface{}) *MockRepository_UpdateGateway_Call {
	return &MockRepository_UpdateGateway_Call{Call: _e.mock.On("UpdateGateway", ctx, id, txnID, response)}
}

func (_c *MockRepository_UpdateGateway_Call) Run(run func(ctx context.Context, id uuid.UUID, txnID string, response []byte)) *MockRepository_UpdateGateway_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []byte
		if args[3] != nil {
			arg3 = args[3].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRepository_UpdateGateway_Call) Return(err error) *MockRepository_UpdateGateway_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_UpdateGateway_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, txnID string, response []byte) error) *MockRepository_UpdateGateway_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateJob provides a mock function for the type MockRepository
func (_mock *MockRepository) UpdateJob(ctx context.Context, job *payment.Job) error {
	ret := _mock.Called(ctx, job)

	if len(ret) == 0 {
		panic("no return value specified for UpdateJob")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *payment.Job) error); ok {
		r0 = returnFunc(ctx, job)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_UpdateJob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateJob'
type MockRepository_UpdateJob_Call struct {
	*mock.Call
}

// UpdateJob is a helper method to define mock.On call
//   - ctx context.Context
//   - job *payment.Job
func (_e *MockRepository_Expecter) UpdateJob(ctx interface{}, job interface{}) *MockRepository_UpdateJob_Call {
	return &MockRepository_UpdateJob_Call{Call: _e.mock.On("UpdateJob", ctx, job)}
}

func (_c *MockRepository_UpdateJob_Call) Run(run func(ctx context.Context, job *payment.Job)) *MockRepository_UpdateJob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *payment.Job
		if args[1] != nil {
			arg1 = args[1].(*payment.Job)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_UpdateJob_Call) Return(err error) *MockRepository_UpdateJob_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_UpdateJob_Call) RunAndReturn(run func(ctx context.Context, job *payment.Job) error) *MockRepository_UpdateJob_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePaymentURL provides a mock function for the type MockRepository
func (_mock *MockRepository) UpdatePaymentURL(ctx context.Context, id uuid.UUID, paymentURL string) error {
	ret := _mock.Called(ctx, id, paymentURL)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePaymentURL")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = returnFunc(ctx, id, paymentURL)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_UpdatePaymentURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePaymentURL'
type MockRepository_UpdatePaymentURL_Call struct {
	*mock.Call
}

// UpdatePaymentURL is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - paymentURL string
func (_e *MockRepository_Expecter) UpdatePaymentURL(ctx interface{}, id interface{}, paymentURL interface{}) *MockRepository_UpdatePaymentURL_Call {
	return &MockRepository_UpdatePaymentURL_Call{Call: _e.mock.On("UpdatePaymentURL", ctx, id, paymentURL)}
}

func (_c *MockRepository_UpdatePaymentURL_Call) Run(run func(ctx context.Context, id uuid.UUID, paymentURL string)) *MockRepository_UpdatePaymentURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_UpdatePaymentURL_Call) Return(err error) *MockRepository_UpdatePaymentURL_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_UpdatePaymentURL_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, paymentURL string) error) *MockRepository_UpdatePaymentURL_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function for the type MockRepository
func (_mock *MockRepository) UpdateStatus(ctx context.Context, id uuid.UUID, toStatus payment.Status, fromStatuses []payment.Status) error {
	ret := _mock.Called(ctx, id, toStatus, fromStatuses)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, payment.Status, []payment.Status) error); ok {
		r0 = returnFunc(ctx, id, toStatus, fromStatuses)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type MockRepository_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - toStatus payment.Status
//   - fromStatuses []payment.Status
func (_e *MockRepository_Expecter) UpdateStatus(ctx interface{}, id interface{}, toStatus interface{}, fromStatuses interface{}) *MockRepository_UpdateStatus_Call {
	return &MockRepository_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", ctx, id, toStatus, fromStatuses)}
}

func (_c *MockRepository_UpdateStatus_Call) Run(run func(ctx context.Context, id uuid.UUID, toStatus payment.Status, fromStatuses []payment.Status)) *MockRepository_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 payment.Status
		if args[2] != nil {
			arg2 = args[2].(payment.Status)
		}
		var arg3 []payment.Status
		if args[3] != nil {
			arg3 = args[3].([]payment.Status)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRepository_UpdateStatus_Call) Return(err error) *MockRepository_UpdateStatus_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_UpdateStatus_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, toStatus payment.Status, fromStatuses []payment.Status) error) *MockRepository_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}
