// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockInventoryReleaser creates a new instance of MockInventoryReleaser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInventoryReleaser(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInventoryReleaser {
	mock := &MockInventoryReleaser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockInventoryReleaser is an autogenerated mock type for the InventoryReleaser type
type MockInventoryReleaser struct {
	mock.Mock
}

type MockInventoryReleaser_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInventoryReleaser) EXPECT() *MockInventoryReleaser_Expecter {
	return &MockInventoryReleaser_Expecter{mock: &_m.Mock}
}

// Release provides a mock function for the type MockInventoryReleaser
func (_mock *MockInventoryReleaser) Release(ctx context.Context, productID uuid.UUID, qty int) error {
	ret := _mock.Called(ctx, productID, qty)

	if len(ret) == 0 {
		panic("no return value specified for Release")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int) error); ok {
		r0 = returnFunc(ctx, productID, qty)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockInventoryReleaser_Release_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Release'
type MockInventoryReleaser_Release_Call struct {
	*mock.Call
}

// Release is a helper method to define mock.On call
//   - ctx context.Context
//   - productID uuid.UUID
//   - qty int
func (_e *MockInventoryReleaser_Expecter) Release(ctx interface{}, productID interface{}, qty interface{}) *MockInventoryReleaser_Release_Call {
	return &MockInventoryReleaser_Release_Call{Call: _e.mock.On("Release", ctx, productID, qty)}
}

func (_c *MockInventoryReleaser_Release_Call) Run(run func(ctx context.Context, productID uuid.UUID, qty int)) *MockInventoryReleaser_Release_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockInventoryReleaser_Release_Call) Return(err error) *MockInventoryReleaser_Release_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockInventoryReleaser_Release_Call) RunAndReturn(run func(ctx context.Context, productID uuid.UUID, qty int) error) *MockInventoryReleaser_Release_Call {
	_c.Call.Return(run)
	return _c
}
