// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/residwi/go-api-project-template/internal/features/payment"
	mock "github.com/stretchr/testify/mock"
)

// NewMockInventoryRestorer creates a new instance of MockInventoryRestorer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInventoryRestorer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInventoryRestorer {
	mock := &MockInventoryRestorer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockInventoryRestorer is an autogenerated mock type for the InventoryRestorer type
type MockInventoryRestorer struct {
	mock.Mock
}

type MockInventoryRestorer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInventoryRestorer) EXPECT() *MockInventoryRestorer_Expecter {
	return &MockInventoryRestorer_Expecter{mock: &_m.Mock}
}

// Restore provides a mock function for the type MockInventoryRestorer
func (_mock *MockInventoryRestorer) Restore(ctx context.Context, items []payment.InventoryChange, wasDeducted bool) error {
	ret := _mock.Called(ctx, items, wasDeducted)

	if len(ret) == 0 {
		panic("no return value specified for Restore")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []payment.InventoryChange, bool) error); ok {
		r0 = returnFunc(ctx, items, wasDeducted)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockInventoryRestorer_Restore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Restore'
type MockInventoryRestorer_Restore_Call struct {
	*mock.Call
}

// Restore is a helper method to define mock.On call
//   - ctx context.Context
//   - items []payment.InventoryChange
//   - wasDeducted bool
func (_e *MockInventoryRestorer_Expecter) Restore(ctx interface{}, items interface{}, wasDeducted interface{}) *MockInventoryRestorer_Restore_Call {
	return &MockInventoryRestorer_Restore_Call{Call: _e.mock.On("Restore", ctx, items, wasDeducted)}
}

func (_c *MockInventoryRestorer_Restore_Call) Run(run func(ctx context.Context, items []payment.InventoryChange, wasDeducted bool)) *MockInventoryRestorer_Restore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []payment.InventoryChange
		if args[1] != nil {
			arg1 = args[1].([]payment.InventoryChange)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockInventoryRestorer_Restore_Call) Return(err error) *MockInventoryRestorer_Restore_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockInventoryRestorer_Restore_Call) RunAndReturn(run func(ctx context.Context, items []payment.InventoryChange, wasDeducted bool) error) *MockInventoryRestorer_Restore_Call {
	_c.Call.Return(run)
	return _c
}
