// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package http

import (
	"context"

	"github.com/google/uuid"
	"github.com/residwi/go-api-project-template/internal/modules/shipping/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockShipmentReader creates a new instance of MockShipmentReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockShipmentReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockShipmentReader {
	mock := &MockShipmentReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockShipmentReader is an autogenerated mock type for the ShipmentReader type
type MockShipmentReader struct {
	mock.Mock
}

type MockShipmentReader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockShipmentReader) EXPECT() *MockShipmentReader_Expecter {
	return &MockShipmentReader_Expecter{mock: &_m.Mock}
}

// GetByOrderIDForUser provides a mock function for the type MockShipmentReader
func (_mock *MockShipmentReader) GetByOrderIDForUser(ctx context.Context, userID uuid.UUID, orderID uuid.UUID) (*domain.Shipment, error) {
	ret := _mock.Called(ctx, userID, orderID)

	if len(ret) == 0 {
		panic("no return value specified for GetByOrderIDForUser")
	}

	var r0 *domain.Shipment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*domain.Shipment, error)); ok {
		return returnFunc(ctx, userID, orderID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *domain.Shipment); ok {
		r0 = returnFunc(ctx, userID, orderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Shipment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID, orderID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockShipmentReader_GetByOrderIDForUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByOrderIDForUser'
type MockShipmentReader_GetByOrderIDForUser_Call struct {
	*mock.Call
}

// GetByOrderIDForUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - orderID uuid.UUID
func (_e *MockShipmentReader_Expecter) GetByOrderIDForUser(ctx any, userID any, orderID any) *MockShipmentReader_GetByOrderIDForUser_Call {
	return &MockShipmentReader_GetByOrderIDForUser_Call{Call: _e.mock.On("GetByOrderIDForUser", ctx, userID, orderID)}
}

func (_c *MockShipmentReader_GetByOrderIDForUser_Call) Run(run func(ctx context.Context, userID uuid.UUID, orderID uuid.UUID)) *MockShipmentReader_GetByOrderIDForUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockShipmentReader_GetByOrderIDForUser_Call) Return(shipment *domain.Shipment, err error) *MockShipmentReader_GetByOrderIDForUser_Call {
	_c.Call.Return(shipment, err)
	return _c
}

func (_c *MockShipmentReader_GetByOrderIDForUser_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, orderID uuid.UUID) (*domain.Shipment, error)) *MockShipmentReader_GetByOrderIDForUser_Call {
	_c.Call.Return(run)
	return _c
}
