// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package jobs

import (
	"context"

	"github.com/residwi/go-api-project-template/internal/modules/payment/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockChargeProcessor creates a new instance of MockChargeProcessor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChargeProcessor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChargeProcessor {
	mock := &MockChargeProcessor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockChargeProcessor is an autogenerated mock type for the ChargeProcessor type
type MockChargeProcessor struct {
	mock.Mock
}

type MockChargeProcessor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChargeProcessor) EXPECT() *MockChargeProcessor_Expecter {
	return &MockChargeProcessor_Expecter{mock: &_m.Mock}
}

// RunChargeJob provides a mock function for the type MockChargeProcessor
func (_mock *MockChargeProcessor) RunChargeJob(ctx context.Context, job domain.Job) error {
	ret := _mock.Called(ctx, job)

	if len(ret) == 0 {
		panic("no return value specified for RunChargeJob")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Job) error); ok {
		r0 = returnFunc(ctx, job)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockChargeProcessor_RunChargeJob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunChargeJob'
type MockChargeProcessor_RunChargeJob_Call struct {
	*mock.Call
}

// RunChargeJob is a helper method to define mock.On call
//   - ctx context.Context
//   - job domain.Job
func (_e *MockChargeProcessor_Expecter) RunChargeJob(ctx any, job any) *MockChargeProcessor_RunChargeJob_Call {
	return &MockChargeProcessor_RunChargeJob_Call{Call: _e.mock.On("RunChargeJob", ctx, job)}
}

func (_c *MockChargeProcessor_RunChargeJob_Call) Run(run func(ctx context.Context, job domain.Job)) *MockChargeProcessor_RunChargeJob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Job
		if args[1] != nil {
			arg1 = args[1].(domain.Job)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockChargeProcessor_RunChargeJob_Call) Return(err error) *MockChargeProcessor_RunChargeJob_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockChargeProcessor_RunChargeJob_Call) RunAndReturn(run func(ctx context.Context, job domain.Job) error) *MockChargeProcessor_RunChargeJob_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRefundProcessor creates a new instance of MockRefundProcessor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRefundProcessor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRefundProcessor {
	mock := &MockRefundProcessor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRefundProcessor is an autogenerated mock type for the RefundProcessor type
type MockRefundProcessor struct {
	mock.Mock
}

type MockRefundProcessor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRefundProcessor) EXPECT() *MockRefundProcessor_Expecter {
	return &MockRefundProcessor_Expecter{mock: &_m.Mock}
}

// RunRefundJob provides a mock function for the type MockRefundProcessor
func (_mock *MockRefundProcessor) RunRefundJob(ctx context.Context, job domain.Job) error {
	ret := _mock.Called(ctx, job)

	if len(ret) == 0 {
		panic("no return value specified for RunRefundJob")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Job) error); ok {
		r0 = returnFunc(ctx, job)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRefundProcessor_RunRefundJob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunRefundJob'
type MockRefundProcessor_RunRefundJob_Call struct {
	*mock.Call
}

// RunRefundJob is a helper method to define mock.On call
//   - ctx context.Context
//   - job domain.Job
func (_e *MockRefundProcessor_Expecter) RunRefundJob(ctx any, job any) *MockRefundProcessor_RunRefundJob_Call {
	return &MockRefundProcessor_RunRefundJob_Call{Call: _e.mock.On("RunRefundJob", ctx, job)}
}

func (_c *MockRefundProcessor_RunRefundJob_Call) Run(run func(ctx context.Context, job domain.Job)) *MockRefundProcessor_RunRefundJob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Job
		if args[1] != nil {
			arg1 = args[1].(domain.Job)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRefundProcessor_RunRefundJob_Call) Return(err error) *MockRefundProcessor_RunRefundJob_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRefundProcessor_RunRefundJob_Call) RunAndReturn(run func(ctx context.Context, job domain.Job) error) *MockRefundProcessor_RunRefundJob_Call {
	_c.Call.Return(run)
	return _c
}
