// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package http

import (
	"context"

	"github.com/google/uuid"
	"github.com/residwi/go-api-project-template/internal/modules/cart/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCartReader creates a new instance of MockCartReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCartReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCartReader {
	mock := &MockCartReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCartReader is an autogenerated mock type for the CartReader type
type MockCartReader struct {
	mock.Mock
}

type MockCartReader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCartReader) EXPECT() *MockCartReader_Expecter {
	return &MockCartReader_Expecter{mock: &_m.Mock}
}

// GetCart provides a mock function for the type MockCartReader
func (_mock *MockCartReader) GetCart(ctx context.Context, userID uuid.UUID) (*domain.Cart, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetCart")
	}

	var r0 *domain.Cart
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Cart, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Cart); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Cart)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCartReader_GetCart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCart'
type MockCartReader_GetCart_Call struct {
	*mock.Call
}

// GetCart is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockCartReader_Expecter) GetCart(ctx any, userID any) *MockCartReader_GetCart_Call {
	return &MockCartReader_GetCart_Call{Call: _e.mock.On("GetCart", ctx, userID)}
}

func (_c *MockCartReader_GetCart_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockCartReader_GetCart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCartReader_GetCart_Call) Return(cart *domain.Cart, err error) *MockCartReader_GetCart_Call {
	_c.Call.Return(cart, err)
	return _c
}

func (_c *MockCartReader_GetCart_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) (*domain.Cart, error)) *MockCartReader_GetCart_Call {
	_c.Call.Return(run)
	return _c
}
