// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package payment

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/residwi/go-api-project-template/internal/modules/inventory"
	"github.com/residwi/go-api-project-template/internal/modules/order/contract"
	"github.com/residwi/go-api-project-template/internal/modules/payment/domain"
	"github.com/residwi/go-api-project-template/internal/modules/payment/gateway"
	mock "github.com/stretchr/testify/mock"
)

// NewMockJobRepository creates a new instance of MockJobRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJobRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJobRepository {
	mock := &MockJobRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockJobRepository is an autogenerated mock type for the JobRepository type
type MockJobRepository struct {
	mock.Mock
}

type MockJobRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJobRepository) EXPECT() *MockJobRepository_Expecter {
	return &MockJobRepository_Expecter{mock: &_m.Mock}
}

// CancelJobsByOrderID provides a mock function for the type MockJobRepository
func (_mock *MockJobRepository) CancelJobsByOrderID(ctx context.Context, orderID uuid.UUID) error {
	ret := _mock.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for CancelJobsByOrderID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, orderID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockJobRepository_CancelJobsByOrderID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelJobsByOrderID'
type MockJobRepository_CancelJobsByOrderID_Call struct {
	*mock.Call
}

// CancelJobsByOrderID is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID uuid.UUID
func (_e *MockJobRepository_Expecter) CancelJobsByOrderID(ctx any, orderID any) *MockJobRepository_CancelJobsByOrderID_Call {
	return &MockJobRepository_CancelJobsByOrderID_Call{Call: _e.mock.On("CancelJobsByOrderID", ctx, orderID)}
}

func (_c *MockJobRepository_CancelJobsByOrderID_Call) Run(run func(ctx context.Context, orderID uuid.UUID)) *MockJobRepository_CancelJobsByOrderID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockJobRepository_CancelJobsByOrderID_Call) Return(err error) *MockJobRepository_CancelJobsByOrderID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockJobRepository_CancelJobsByOrderID_Call) RunAndReturn(run func(ctx context.Context, orderID uuid.UUID) error) *MockJobRepository_CancelJobsByOrderID_Call {
	_c.Call.Return(run)
	return _c
}

// Claim provides a mock function for the type MockJobRepository
func (_mock *MockJobRepository) Claim(ctx context.Context, batchSize int, leaseDuration time.Duration) ([]domain.Job, error) {
	ret := _mock.Called(ctx, batchSize, leaseDuration)

	if len(ret) == 0 {
		panic("no return value specified for Claim")
	}

	var r0 []domain.Job
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, time.Duration) ([]domain.Job, error)); ok {
		return returnFunc(ctx, batchSize, leaseDuration)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, time.Duration) []domain.Job); ok {
		r0 = returnFunc(ctx, batchSize, leaseDuration)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Job)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, time.Duration) error); ok {
		r1 = returnFunc(ctx, batchSize, leaseDuration)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJobRepository_Claim_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Claim'
type MockJobRepository_Claim_Call struct {
	*mock.Call
}

// Claim is a helper method to define mock.On call
//   - ctx context.Context
//   - batchSize int
//   - leaseDuration time.Duration
func (_e *MockJobRepository_Expecter) Claim(ctx any, batchSize any, leaseDuration any) *MockJobRepository_Claim_Call {
	return &MockJobRepository_Claim_Call{Call: _e.mock.On("Claim", ctx, batchSize, leaseDuration)}
}

func (_c *MockJobRepository_Claim_Call) Run(run func(ctx context.Context, batchSize int, leaseDuration time.Duration)) *MockJobRepository_Claim_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 time.Duration
		if args[2] != nil {
			arg2 = args[2].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockJobRepository_Claim_Call) Return(jobs []domain.Job, err error) *MockJobRepository_Claim_Call {
	_c.Call.Return(jobs, err)
	return _c
}

func (_c *MockJobRepository_Claim_Call) RunAndReturn(run func(ctx context.Context, batchSize int, leaseDuration time.Duration) ([]domain.Job, error)) *MockJobRepository_Claim_Call {
	_c.Call.Return(run)
	return _c
}

// CreateJob provides a mock function for the type MockJobRepository
func (_mock *MockJobRepository) CreateJob(ctx context.Context, job *domain.Job) error {
	ret := _mock.Called(ctx, job)

	if len(ret) == 0 {
		panic("no return value specified for CreateJob")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Job) error); ok {
		r0 = returnFunc(ctx, job)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockJobRepository_CreateJob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateJob'
type MockJobRepository_CreateJob_Call struct {
	*mock.Call
}

// CreateJob is a helper method to define mock.On call
//   - ctx context.Context
//   - job *domain.Job
func (_e *MockJobRepository_Expecter) CreateJob(ctx any, job any) *MockJobRepository_CreateJob_Call {
	return &MockJobRepository_CreateJob_Call{Call: _e.mock.On("CreateJob", ctx, job)}
}

func (_c *MockJobRepository_CreateJob_Call) Run(run func(ctx context.Context, job *domain.Job)) *MockJobRepository_CreateJob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Job
		if args[1] != nil {
			arg1 = args[1].(*domain.Job)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockJobRepository_CreateJob_Call) Return(err error) *MockJobRepository_CreateJob_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockJobRepository_CreateJob_Call) RunAndReturn(run func(ctx context.Context, job *domain.Job) error) *MockJobRepository_CreateJob_Call {
	_c.Call.Return(run)
	return _c
}

// MarkJobCompleted provides a mock function for the type MockJobRepository
func (_mock *MockJobRepository) MarkJobCompleted(ctx context.Context, jobID uuid.UUID) error {
	ret := _mock.Called(ctx, jobID)

	if len(ret) == 0 {
		panic("no return value specified for MarkJobCompleted")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, jobID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockJobRepository_MarkJobCompleted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkJobCompleted'
type MockJobRepository_MarkJobCompleted_Call struct {
	*mock.Call
}

// MarkJobCompleted is a helper method to define mock.On call
//   - ctx context.Context
//   - jobID uuid.UUID
func (_e *MockJobRepository_Expecter) MarkJobCompleted(ctx any, jobID any) *MockJobRepository_MarkJobCompleted_Call {
	return &MockJobRepository_MarkJobCompleted_Call{Call: _e.mock.On("MarkJobCompleted", ctx, jobID)}
}

func (_c *MockJobRepository_MarkJobCompleted_Call) Run(run func(ctx context.Context, jobID uuid.UUID)) *MockJobRepository_MarkJobCompleted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockJobRepository_MarkJobCompleted_Call) Return(err error) *MockJobRepository_MarkJobCompleted_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockJobRepository_MarkJobCompleted_Call) RunAndReturn(run func(ctx context.Context, jobID uuid.UUID) error) *MockJobRepository_MarkJobCompleted_Call {
	_c.Call.Return(run)
	return _c
}

// MarkJobCompletedByPaymentID provides a mock function for the type MockJobRepository
func (_mock *MockJobRepository) MarkJobCompletedByPaymentID(ctx context.Context, paymentID uuid.UUID, action domain.JobAction) error {
	ret := _mock.Called(ctx, paymentID, action)

	if len(ret) == 0 {
		panic("no return value specified for MarkJobCompletedByPaymentID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, domain.JobAction) error); ok {
		r0 = returnFunc(ctx, paymentID, action)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockJobRepository_MarkJobCompletedByPaymentID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkJobCompletedByPaymentID'
type MockJobRepository_MarkJobCompletedByPaymentID_Call struct {
	*mock.Call
}

// MarkJobCompletedByPaymentID is a helper method to define mock.On call
//   - ctx context.Context
//   - paymentID uuid.UUID
//   - action domain.JobAction
func (_e *MockJobRepository_Expecter) MarkJobCompletedByPaymentID(ctx any, paymentID any, action any) *MockJobRepository_MarkJobCompletedByPaymentID_Call {
	return &MockJobRepository_MarkJobCompletedByPaymentID_Call{Call: _e.mock.On("MarkJobCompletedByPaymentID", ctx, paymentID, action)}
}

func (_c *MockJobRepository_MarkJobCompletedByPaymentID_Call) Run(run func(ctx context.Context, paymentID uuid.UUID, action domain.JobAction)) *MockJobRepository_MarkJobCompletedByPaymentID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 domain.JobAction
		if args[2] != nil {
			arg2 = args[2].(domain.JobAction)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockJobRepository_MarkJobCompletedByPaymentID_Call) Return(err error) *MockJobRepository_MarkJobCompletedByPaymentID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockJobRepository_MarkJobCompletedByPaymentID_Call) RunAndReturn(run func(ctx context.Context, paymentID uuid.UUID, action domain.JobAction) error) *MockJobRepository_MarkJobCompletedByPaymentID_Call {
	_c.Call.Return(run)
	return _c
}

// Prune provides a mock function for the type MockJobRepository
func (_mock *MockJobRepository) Prune(ctx context.Context, olderThan time.Duration, limit int) (int, error) {
	ret := _mock.Called(ctx, olderThan, limit)

	if len(ret) == 0 {
		panic("no return value specified for Prune")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Duration, int) (int, error)); ok {
		return returnFunc(ctx, olderThan, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Duration, int) int); ok {
		r0 = returnFunc(ctx, olderThan, limit)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, time.Duration, int) error); ok {
		r1 = returnFunc(ctx, olderThan, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJobRepository_Prune_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Prune'
type MockJobRepository_Prune_Call struct {
	*mock.Call
}

// Prune is a helper method to define mock.On call
//   - ctx context.Context
//   - olderThan time.Duration
//   - limit int
func (_e *MockJobRepository_Expecter) Prune(ctx any, olderThan any, limit any) *MockJobRepository_Prune_Call {
	return &MockJobRepository_Prune_Call{Call: _e.mock.On("Prune", ctx, olderThan, limit)}
}

func (_c *MockJobRepository_Prune_Call) Run(run func(ctx context.Context, olderThan time.Duration, limit int)) *MockJobRepository_Prune_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Duration
		if args[1] != nil {
			arg1 = args[1].(time.Duration)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockJobRepository_Prune_Call) Return(n int, err error) *MockJobRepository_Prune_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockJobRepository_Prune_Call) RunAndReturn(run func(ctx context.Context, olderThan time.Duration, limit int) (int, error)) *MockJobRepository_Prune_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateJob provides a mock function for the type MockJobRepository
func (_mock *MockJobRepository) UpdateJob(ctx context.Context, job *domain.Job) error {
	ret := _mock.Called(ctx, job)

	if len(ret) == 0 {
		panic("no return value specified for UpdateJob")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Job) error); ok {
		r0 = returnFunc(ctx, job)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockJobRepository_UpdateJob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateJob'
type MockJobRepository_UpdateJob_Call struct {
	*mock.Call
}

// UpdateJob is a helper method to define mock.On call
//   - ctx context.Context
//   - job *domain.Job
func (_e *MockJobRepository_Expecter) UpdateJob(ctx any, job any) *MockJobRepository_UpdateJob_Call {
	return &MockJobRepository_UpdateJob_Call{Call: _e.mock.On("UpdateJob", ctx, job)}
}

func (_c *MockJobRepository_UpdateJob_Call) Run(run func(ctx context.Context, job *domain.Job)) *MockJobRepository_UpdateJob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Job
		if args[1] != nil {
			arg1 = args[1].(*domain.Job)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockJobRepository_UpdateJob_Call) Return(err error) *MockJobRepository_UpdateJob_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockJobRepository_UpdateJob_Call) RunAndReturn(run func(ctx context.Context, job *domain.Job) error) *MockJobRepository_UpdateJob_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGateway creates a new instance of MockGateway. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGateway(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGateway {
	mock := &MockGateway{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGateway is an autogenerated mock type for the Gateway type
type MockGateway struct {
	mock.Mock
}

type MockGateway_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGateway) EXPECT() *MockGateway_Expecter {
	return &MockGateway_Expecter{mock: &_m.Mock}
}

// Charge provides a mock function for the type MockGateway
func (_mock *MockGateway) Charge(ctx context.Context, req gateway.ChargeRequest) (gateway.ChargeResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Charge")
	}

	var r0 gateway.ChargeResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, gateway.ChargeRequest) (gateway.ChargeResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, gateway.ChargeRequest) gateway.ChargeResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Get(0).(gateway.ChargeResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, gateway.ChargeRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGateway_Charge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Charge'
type MockGateway_Charge_Call struct {
	*mock.Call
}

// Charge is a helper method to define mock.On call
//   - ctx context.Context
//   - req gateway.ChargeRequest
func (_e *MockGateway_Expecter) Charge(ctx any, req any) *MockGateway_Charge_Call {
	return &MockGateway_Charge_Call{Call: _e.mock.On("Charge", ctx, req)}
}

func (_c *MockGateway_Charge_Call) Run(run func(ctx context.Context, req gateway.ChargeRequest)) *MockGateway_Charge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 gateway.ChargeRequest
		if args[1] != nil {
			arg1 = args[1].(gateway.ChargeRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGateway_Charge_Call) Return(chargeResponse gateway.ChargeResponse, err error) *MockGateway_Charge_Call {
	_c.Call.Return(chargeResponse, err)
	return _c
}

func (_c *MockGateway_Charge_Call) RunAndReturn(run func(ctx context.Context, req gateway.ChargeRequest) (gateway.ChargeResponse, error)) *MockGateway_Charge_Call {
	_c.Call.Return(run)
	return _c
}

// Refund provides a mock function for the type MockGateway
func (_mock *MockGateway) Refund(ctx context.Context, req gateway.RefundRequest) (gateway.RefundResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Refund")
	}

	var r0 gateway.RefundResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, gateway.RefundRequest) (gateway.RefundResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, gateway.RefundRequest) gateway.RefundResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Get(0).(gateway.RefundResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, gateway.RefundRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGateway_Refund_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Refund'
type MockGateway_Refund_Call struct {
	*mock.Call
}

// Refund is a helper method to define mock.On call
//   - ctx context.Context
//   - req gateway.RefundRequest
func (_e *MockGateway_Expecter) Refund(ctx any, req any) *MockGateway_Refund_Call {
	return &MockGateway_Refund_Call{Call: _e.mock.On("Refund", ctx, req)}
}

func (_c *MockGateway_Refund_Call) Run(run func(ctx context.Context, req gateway.RefundRequest)) *MockGateway_Refund_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 gateway.RefundRequest
		if args[1] != nil {
			arg1 = args[1].(gateway.RefundRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGateway_Refund_Call) Return(refundResponse gateway.RefundResponse, err error) *MockGateway_Refund_Call {
	_c.Call.Return(refundResponse, err)
	return _c
}

func (_c *MockGateway_Refund_Call) RunAndReturn(run func(ctx context.Context, req gateway.RefundRequest) (gateway.RefundResponse, error)) *MockGateway_Refund_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOrderTransition creates a new instance of MockOrderTransition. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderTransition(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderTransition {
	mock := &MockOrderTransition{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOrderTransition is an autogenerated mock type for the OrderTransition type
type MockOrderTransition struct {
	mock.Mock
}

type MockOrderTransition_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderTransition) EXPECT() *MockOrderTransition_Expecter {
	return &MockOrderTransition_Expecter{mock: &_m.Mock}
}

// MarkAwaitingPayment provides a mock function for the type MockOrderTransition
func (_mock *MockOrderTransition) MarkAwaitingPayment(ctx context.Context, orderID uuid.UUID) error {
	ret := _mock.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for MarkAwaitingPayment")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, orderID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOrderTransition_MarkAwaitingPayment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkAwaitingPayment'
type MockOrderTransition_MarkAwaitingPayment_Call struct {
	*mock.Call
}

// MarkAwaitingPayment is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID uuid.UUID
func (_e *MockOrderTransition_Expecter) MarkAwaitingPayment(ctx any, orderID any) *MockOrderTransition_MarkAwaitingPayment_Call {
	return &MockOrderTransition_MarkAwaitingPayment_Call{Call: _e.mock.On("MarkAwaitingPayment", ctx, orderID)}
}

func (_c *MockOrderTransition_MarkAwaitingPayment_Call) Run(run func(ctx context.Context, orderID uuid.UUID)) *MockOrderTransition_MarkAwaitingPayment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderTransition_MarkAwaitingPayment_Call) Return(err error) *MockOrderTransition_MarkAwaitingPayment_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOrderTransition_MarkAwaitingPayment_Call) RunAndReturn(run func(ctx context.Context, orderID uuid.UUID) error) *MockOrderTransition_MarkAwaitingPayment_Call {
	_c.Call.Return(run)
	return _c
}

// MarkFulfillmentFailedAfterCharge provides a mock function for the type MockOrderTransition
func (_mock *MockOrderTransition) MarkFulfillmentFailedAfterCharge(ctx context.Context, orderID uuid.UUID) error {
	ret := _mock.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for MarkFulfillmentFailedAfterCharge")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, orderID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOrderTransition_MarkFulfillmentFailedAfterCharge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkFulfillmentFailedAfterCharge'
type MockOrderTransition_MarkFulfillmentFailedAfterCharge_Call struct {
	*mock.Call
}

// MarkFulfillmentFailedAfterCharge is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID uuid.UUID
func (_e *MockOrderTransition_Expecter) MarkFulfillmentFailedAfterCharge(ctx any, orderID any) *MockOrderTransition_MarkFulfillmentFailedAfterCharge_Call {
	return &MockOrderTransition_MarkFulfillmentFailedAfterCharge_Call{Call: _e.mock.On("MarkFulfillmentFailedAfterCharge", ctx, orderID)}
}

func (_c *MockOrderTransition_MarkFulfillmentFailedAfterCharge_Call) Run(run func(ctx context.Context, orderID uuid.UUID)) *MockOrderTransition_MarkFulfillmentFailedAfterCharge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderTransition_MarkFulfillmentFailedAfterCharge_Call) Return(err error) *MockOrderTransition_MarkFulfillmentFailedAfterCharge_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOrderTransition_MarkFulfillmentFailedAfterCharge_Call) RunAndReturn(run func(ctx context.Context, orderID uuid.UUID) error) *MockOrderTransition_MarkFulfillmentFailedAfterCharge_Call {
	_c.Call.Return(run)
	return _c
}

// MarkFulfillmentFailedCompensating provides a mock function for the type MockOrderTransition
func (_mock *MockOrderTransition) MarkFulfillmentFailedCompensating(ctx context.Context, orderID uuid.UUID) error {
	ret := _mock.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for MarkFulfillmentFailedCompensating")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, orderID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOrderTransition_MarkFulfillmentFailedCompensating_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkFulfillmentFailedCompensating'
type MockOrderTransition_MarkFulfillmentFailedCompensating_Call struct {
	*mock.Call
}

// MarkFulfillmentFailedCompensating is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID uuid.UUID
func (_e *MockOrderTransition_Expecter) MarkFulfillmentFailedCompensating(ctx any, orderID any) *MockOrderTransition_MarkFulfillmentFailedCompensating_Call {
	return &MockOrderTransition_MarkFulfillmentFailedCompensating_Call{Call: _e.mock.On("MarkFulfillmentFailedCompensating", ctx, orderID)}
}

func (_c *MockOrderTransition_MarkFulfillmentFailedCompensating_Call) Run(run func(ctx context.Context, orderID uuid.UUID)) *MockOrderTransition_MarkFulfillmentFailedCompensating_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderTransition_MarkFulfillmentFailedCompensating_Call) Return(err error) *MockOrderTransition_MarkFulfillmentFailedCompensating_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOrderTransition_MarkFulfillmentFailedCompensating_Call) RunAndReturn(run func(ctx context.Context, orderID uuid.UUID) error) *MockOrderTransition_MarkFulfillmentFailedCompensating_Call {
	_c.Call.Return(run)
	return _c
}

// MarkPaid provides a mock function for the type MockOrderTransition
func (_mock *MockOrderTransition) MarkPaid(ctx context.Context, orderID uuid.UUID) error {
	ret := _mock.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for MarkPaid")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, orderID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOrderTransition_MarkPaid_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkPaid'
type MockOrderTransition_MarkPaid_Call struct {
	*mock.Call
}

// MarkPaid is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID uuid.UUID
func (_e *MockOrderTransition_Expecter) MarkPaid(ctx any, orderID any) *MockOrderTransition_MarkPaid_Call {
	return &MockOrderTransition_MarkPaid_Call{Call: _e.mock.On("MarkPaid", ctx, orderID)}
}

func (_c *MockOrderTransition_MarkPaid_Call) Run(run func(ctx context.Context, orderID uuid.UUID)) *MockOrderTransition_MarkPaid_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderTransition_MarkPaid_Call) Return(err error) *MockOrderTransition_MarkPaid_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOrderTransition_MarkPaid_Call) RunAndReturn(run func(ctx context.Context, orderID uuid.UUID) error) *MockOrderTransition_MarkPaid_Call {
	_c.Call.Return(run)
	return _c
}

// MarkPaymentProcessing provides a mock function for the type MockOrderTransition
func (_mock *MockOrderTransition) MarkPaymentProcessing(ctx context.Context, orderID uuid.UUID) error {
	ret := _mock.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for MarkPaymentProcessing")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, orderID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOrderTransition_MarkPaymentProcessing_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkPaymentProcessing'
type MockOrderTransition_MarkPaymentProcessing_Call struct {
	*mock.Call
}

// MarkPaymentProcessing is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID uuid.UUID
func (_e *MockOrderTransition_Expecter) MarkPaymentProcessing(ctx any, orderID any) *MockOrderTransition_MarkPaymentProcessing_Call {
	return &MockOrderTransition_MarkPaymentProcessing_Call{Call: _e.mock.On("MarkPaymentProcessing", ctx, orderID)}
}

func (_c *MockOrderTransition_MarkPaymentProcessing_Call) Run(run func(ctx context.Context, orderID uuid.UUID)) *MockOrderTransition_MarkPaymentProcessing_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderTransition_MarkPaymentProcessing_Call) Return(err error) *MockOrderTransition_MarkPaymentProcessing_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOrderTransition_MarkPaymentProcessing_Call) RunAndReturn(run func(ctx context.Context, orderID uuid.UUID) error) *MockOrderTransition_MarkPaymentProcessing_Call {
	_c.Call.Return(run)
	return _c
}

// MarkRefunded provides a mock function for the type MockOrderTransition
func (_mock *MockOrderTransition) MarkRefunded(ctx context.Context, orderID uuid.UUID) error {
	ret := _mock.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for MarkRefunded")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, orderID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOrderTransition_MarkRefunded_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkRefunded'
type MockOrderTransition_MarkRefunded_Call struct {
	*mock.Call
}

// MarkRefunded is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID uuid.UUID
func (_e *MockOrderTransition_Expecter) MarkRefunded(ctx any, orderID any) *MockOrderTransition_MarkRefunded_Call {
	return &MockOrderTransition_MarkRefunded_Call{Call: _e.mock.On("MarkRefunded", ctx, orderID)}
}

func (_c *MockOrderTransition_MarkRefunded_Call) Run(run func(ctx context.Context, orderID uuid.UUID)) *MockOrderTransition_MarkRefunded_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderTransition_MarkRefunded_Call) Return(err error) *MockOrderTransition_MarkRefunded_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOrderTransition_MarkRefunded_Call) RunAndReturn(run func(ctx context.Context, orderID uuid.UUID) error) *MockOrderTransition_MarkRefunded_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOrderCanceller creates a new instance of MockOrderCanceller. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderCanceller(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderCanceller {
	mock := &MockOrderCanceller{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOrderCanceller is an autogenerated mock type for the OrderCanceller type
type MockOrderCanceller struct {
	mock.Mock
}

type MockOrderCanceller_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderCanceller) EXPECT() *MockOrderCanceller_Expecter {
	return &MockOrderCanceller_Expecter{mock: &_m.Mock}
}

// CancelUnpaid provides a mock function for the type MockOrderCanceller
func (_mock *MockOrderCanceller) CancelUnpaid(ctx context.Context, orderID uuid.UUID) error {
	ret := _mock.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for CancelUnpaid")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, orderID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOrderCanceller_CancelUnpaid_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelUnpaid'
type MockOrderCanceller_CancelUnpaid_Call struct {
	*mock.Call
}

// CancelUnpaid is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID uuid.UUID
func (_e *MockOrderCanceller_Expecter) CancelUnpaid(ctx any, orderID any) *MockOrderCanceller_CancelUnpaid_Call {
	return &MockOrderCanceller_CancelUnpaid_Call{Call: _e.mock.On("CancelUnpaid", ctx, orderID)}
}

func (_c *MockOrderCanceller_CancelUnpaid_Call) Run(run func(ctx context.Context, orderID uuid.UUID)) *MockOrderCanceller_CancelUnpaid_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderCanceller_CancelUnpaid_Call) Return(err error) *MockOrderCanceller_CancelUnpaid_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOrderCanceller_CancelUnpaid_Call) RunAndReturn(run func(ctx context.Context, orderID uuid.UUID) error) *MockOrderCanceller_CancelUnpaid_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOrderReader creates a new instance of MockOrderReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderReader {
	mock := &MockOrderReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOrderReader is an autogenerated mock type for the OrderReader type
type MockOrderReader struct {
	mock.Mock
}

type MockOrderReader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderReader) EXPECT() *MockOrderReader_Expecter {
	return &MockOrderReader_Expecter{mock: &_m.Mock}
}

// GetSnapshot provides a mock function for the type MockOrderReader
func (_mock *MockOrderReader) GetSnapshot(ctx context.Context, orderID uuid.UUID) (contract.Order, error) {
	ret := _mock.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for GetSnapshot")
	}

	var r0 contract.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (contract.Order, error)); ok {
		return returnFunc(ctx, orderID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) contract.Order); ok {
		r0 = returnFunc(ctx, orderID)
	} else {
		r0 = ret.Get(0).(contract.Order)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, orderID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderReader_GetSnapshot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSnapshot'
type MockOrderReader_GetSnapshot_Call struct {
	*mock.Call
}

// GetSnapshot is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID uuid.UUID
func (_e *MockOrderReader_Expecter) GetSnapshot(ctx any, orderID any) *MockOrderReader_GetSnapshot_Call {
	return &MockOrderReader_GetSnapshot_Call{Call: _e.mock.On("GetSnapshot", ctx, orderID)}
}

func (_c *MockOrderReader_GetSnapshot_Call) Run(run func(ctx context.Context, orderID uuid.UUID)) *MockOrderReader_GetSnapshot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderReader_GetSnapshot_Call) Return(order contract.Order, err error) *MockOrderReader_GetSnapshot_Call {
	_c.Call.Return(order, err)
	return _c
}

func (_c *MockOrderReader_GetSnapshot_Call) RunAndReturn(run func(ctx context.Context, orderID uuid.UUID) (contract.Order, error)) *MockOrderReader_GetSnapshot_Call {
	_c.Call.Return(run)
	return _c
}

// ListItemQuantities provides a mock function for the type MockOrderReader
func (_mock *MockOrderReader) ListItemQuantities(ctx context.Context, orderID uuid.UUID) (map[uuid.UUID]int, error) {
	ret := _mock.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for ListItemQuantities")
	}

	var r0 map[uuid.UUID]int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (map[uuid.UUID]int, error)); ok {
		return returnFunc(ctx, orderID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) map[uuid.UUID]int); ok {
		r0 = returnFunc(ctx, orderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[uuid.UUID]int)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, orderID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderReader_ListItemQuantities_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListItemQuantities'
type MockOrderReader_ListItemQuantities_Call struct {
	*mock.Call
}

// ListItemQuantities is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID uuid.UUID
func (_e *MockOrderReader_Expecter) ListItemQuantities(ctx any, orderID any) *MockOrderReader_ListItemQuantities_Call {
	return &MockOrderReader_ListItemQuantities_Call{Call: _e.mock.On("ListItemQuantities", ctx, orderID)}
}

func (_c *MockOrderReader_ListItemQuantities_Call) Run(run func(ctx context.Context, orderID uuid.UUID)) *MockOrderReader_ListItemQuantities_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderReader_ListItemQuantities_Call) Return(uUIDToInt map[uuid.UUID]int, err error) *MockOrderReader_ListItemQuantities_Call {
	_c.Call.Return(uUIDToInt, err)
	return _c
}

func (_c *MockOrderReader_ListItemQuantities_Call) RunAndReturn(run func(ctx context.Context, orderID uuid.UUID) (map[uuid.UUID]int, error)) *MockOrderReader_ListItemQuantities_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockInventoryDeductor creates a new instance of MockInventoryDeductor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInventoryDeductor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInventoryDeductor {
	mock := &MockInventoryDeductor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockInventoryDeductor is an autogenerated mock type for the InventoryDeductor type
type MockInventoryDeductor struct {
	mock.Mock
}

type MockInventoryDeductor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInventoryDeductor) EXPECT() *MockInventoryDeductor_Expecter {
	return &MockInventoryDeductor_Expecter{mock: &_m.Mock}
}

// Deduct provides a mock function for the type MockInventoryDeductor
func (_mock *MockInventoryDeductor) Deduct(ctx context.Context, items map[uuid.UUID]int) error {
	ret := _mock.Called(ctx, items)

	if len(ret) == 0 {
		panic("no return value specified for Deduct")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, map[uuid.UUID]int) error); ok {
		r0 = returnFunc(ctx, items)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockInventoryDeductor_Deduct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Deduct'
type MockInventoryDeductor_Deduct_Call struct {
	*mock.Call
}

// Deduct is a helper method to define mock.On call
//   - ctx context.Context
//   - items map[uuid.UUID]int
func (_e *MockInventoryDeductor_Expecter) Deduct(ctx any, items any) *MockInventoryDeductor_Deduct_Call {
	return &MockInventoryDeductor_Deduct_Call{Call: _e.mock.On("Deduct", ctx, items)}
}

func (_c *MockInventoryDeductor_Deduct_Call) Run(run func(ctx context.Context, items map[uuid.UUID]int)) *MockInventoryDeductor_Deduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 map[uuid.UUID]int
		if args[1] != nil {
			arg1 = args[1].(map[uuid.UUID]int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockInventoryDeductor_Deduct_Call) Return(err error) *MockInventoryDeductor_Deduct_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockInventoryDeductor_Deduct_Call) RunAndReturn(run func(ctx context.Context, items map[uuid.UUID]int) error) *MockInventoryDeductor_Deduct_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockInventoryRestorer creates a new instance of MockInventoryRestorer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInventoryRestorer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInventoryRestorer {
	mock := &MockInventoryRestorer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockInventoryRestorer is an autogenerated mock type for the InventoryRestorer type
type MockInventoryRestorer struct {
	mock.Mock
}

type MockInventoryRestorer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInventoryRestorer) EXPECT() *MockInventoryRestorer_Expecter {
	return &MockInventoryRestorer_Expecter{mock: &_m.Mock}
}

// Restore provides a mock function for the type MockInventoryRestorer
func (_mock *MockInventoryRestorer) Restore(ctx context.Context, items map[uuid.UUID]int, prior inventory.StockState) error {
	ret := _mock.Called(ctx, items, prior)

	if len(ret) == 0 {
		panic("no return value specified for Restore")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, map[uuid.UUID]int, inventory.StockState) error); ok {
		r0 = returnFunc(ctx, items, prior)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockInventoryRestorer_Restore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Restore'
type MockInventoryRestorer_Restore_Call struct {
	*mock.Call
}

// Restore is a helper method to define mock.On call
//   - ctx context.Context
//   - items map[uuid.UUID]int
//   - prior inventory.StockState
func (_e *MockInventoryRestorer_Expecter) Restore(ctx any, items any, prior any) *MockInventoryRestorer_Restore_Call {
	return &MockInventoryRestorer_Restore_Call{Call: _e.mock.On("Restore", ctx, items, prior)}
}

func (_c *MockInventoryRestorer_Restore_Call) Run(run func(ctx context.Context, items map[uuid.UUID]int, prior inventory.StockState)) *MockInventoryRestorer_Restore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 map[uuid.UUID]int
		if args[1] != nil {
			arg1 = args[1].(map[uuid.UUID]int)
		}
		var arg2 inventory.StockState
		if args[2] != nil {
			arg2 = args[2].(inventory.StockState)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockInventoryRestorer_Restore_Call) Return(err error) *MockInventoryRestorer_Restore_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockInventoryRestorer_Restore_Call) RunAndReturn(run func(ctx context.Context, items map[uuid.UUID]int, prior inventory.StockState) error) *MockInventoryRestorer_Restore_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCouponPort creates a new instance of MockCouponPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCouponPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCouponPort {
	mock := &MockCouponPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCouponPort is an autogenerated mock type for the CouponPort type
type MockCouponPort struct {
	mock.Mock
}

type MockCouponPort_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCouponPort) EXPECT() *MockCouponPort_Expecter {
	return &MockCouponPort_Expecter{mock: &_m.Mock}
}

// Release provides a mock function for the type MockCouponPort
func (_mock *MockCouponPort) Release(ctx context.Context, orderID uuid.UUID) error {
	ret := _mock.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for Release")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, orderID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCouponPort_Release_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Release'
type MockCouponPort_Release_Call struct {
	*mock.Call
}

// Release is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID uuid.UUID
func (_e *MockCouponPort_Expecter) Release(ctx any, orderID any) *MockCouponPort_Release_Call {
	return &MockCouponPort_Release_Call{Call: _e.mock.On("Release", ctx, orderID)}
}

func (_c *MockCouponPort_Release_Call) Run(run func(ctx context.Context, orderID uuid.UUID)) *MockCouponPort_Release_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCouponPort_Release_Call) Return(err error) *MockCouponPort_Release_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCouponPort_Release_Call) RunAndReturn(run func(ctx context.Context, orderID uuid.UUID) error) *MockCouponPort_Release_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// ClearPaymentURL provides a mock function for the type MockRepository
func (_mock *MockRepository) ClearPaymentURL(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for ClearPaymentURL")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_ClearPaymentURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClearPaymentURL'
type MockRepository_ClearPaymentURL_Call struct {
	*mock.Call
}

// ClearPaymentURL is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockRepository_Expecter) ClearPaymentURL(ctx any, id any) *MockRepository_ClearPaymentURL_Call {
	return &MockRepository_ClearPaymentURL_Call{Call: _e.mock.On("ClearPaymentURL", ctx, id)}
}

func (_c *MockRepository_ClearPaymentURL_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockRepository_ClearPaymentURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_ClearPaymentURL_Call) Return(err error) *MockRepository_ClearPaymentURL_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_ClearPaymentURL_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *MockRepository_ClearPaymentURL_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockRepository
func (_mock *MockRepository) Create(ctx context.Context, p *domain.Payment) error {
	ret := _mock.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Payment) error); ok {
		r0 = returnFunc(ctx, p)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - p *domain.Payment
func (_e *MockRepository_Expecter) Create(ctx any, p any) *MockRepository_Create_Call {
	return &MockRepository_Create_Call{Call: _e.mock.On("Create", ctx, p)}
}

func (_c *MockRepository_Create_Call) Run(run func(ctx context.Context, p *domain.Payment)) *MockRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Payment
		if args[1] != nil {
			arg1 = args[1].(*domain.Payment)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Create_Call) Return(err error) *MockRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Create_Call) RunAndReturn(run func(ctx context.Context, p *domain.Payment) error) *MockRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetActiveByOrderID provides a mock function for the type MockRepository
func (_mock *MockRepository) GetActiveByOrderID(ctx context.Context, orderID uuid.UUID) (*domain.Payment, error) {
	ret := _mock.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for GetActiveByOrderID")
	}

	var r0 *domain.Payment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Payment, error)); ok {
		return returnFunc(ctx, orderID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Payment); ok {
		r0 = returnFunc(ctx, orderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Payment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, orderID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetActiveByOrderID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActiveByOrderID'
type MockRepository_GetActiveByOrderID_Call struct {
	*mock.Call
}

// GetActiveByOrderID is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID uuid.UUID
func (_e *MockRepository_Expecter) GetActiveByOrderID(ctx any, orderID any) *MockRepository_GetActiveByOrderID_Call {
	return &MockRepository_GetActiveByOrderID_Call{Call: _e.mock.On("GetActiveByOrderID", ctx, orderID)}
}

func (_c *MockRepository_GetActiveByOrderID_Call) Run(run func(ctx context.Context, orderID uuid.UUID)) *MockRepository_GetActiveByOrderID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetActiveByOrderID_Call) Return(payment *domain.Payment, err error) *MockRepository_GetActiveByOrderID_Call {
	_c.Call.Return(payment, err)
	return _c
}

func (_c *MockRepository_GetActiveByOrderID_Call) RunAndReturn(run func(ctx context.Context, orderID uuid.UUID) (*domain.Payment, error)) *MockRepository_GetActiveByOrderID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByGatewayTxnID provides a mock function for the type MockRepository
func (_mock *MockRepository) GetByGatewayTxnID(ctx context.Context, txnID string) (*domain.Payment, error) {
	ret := _mock.Called(ctx, txnID)

	if len(ret) == 0 {
		panic("no return value specified for GetByGatewayTxnID")
	}

	var r0 *domain.Payment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.Payment, error)); ok {
		return returnFunc(ctx, txnID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.Payment); ok {
		r0 = returnFunc(ctx, txnID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Payment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, txnID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetByGatewayTxnID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByGatewayTxnID'
type MockRepository_GetByGatewayTxnID_Call struct {
	*mock.Call
}

// GetByGatewayTxnID is a helper method to define mock.On call
//   - ctx context.Context
//   - txnID string
func (_e *MockRepository_Expecter) GetByGatewayTxnID(ctx any, txnID any) *MockRepository_GetByGatewayTxnID_Call {
	return &MockRepository_GetByGatewayTxnID_Call{Call: _e.mock.On("GetByGatewayTxnID", ctx, txnID)}
}

func (_c *MockRepository_GetByGatewayTxnID_Call) Run(run func(ctx context.Context, txnID string)) *MockRepository_GetByGatewayTxnID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetByGatewayTxnID_Call) Return(payment *domain.Payment, err error) *MockRepository_GetByGatewayTxnID_Call {
	_c.Call.Return(payment, err)
	return _c
}

func (_c *MockRepository_GetByGatewayTxnID_Call) RunAndReturn(run func(ctx context.Context, txnID string) (*domain.Payment, error)) *MockRepository_GetByGatewayTxnID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockRepository
func (_mock *MockRepository) GetByID(ctx context.Context, id uuid.UUID) (*domain.Payment, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Payment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Payment, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Payment); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Payment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockRepository_Expecter) GetByID(ctx any, id any) *MockRepository_GetByID_Call {
	return &MockRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetByID_Call) Return(payment *domain.Payment, err error) *MockRepository_GetByID_Call {
	_c.Call.Return(payment, err)
	return _c
}

func (_c *MockRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*domain.Payment, error)) *MockRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListAdmin provides a mock function for the type MockRepository
func (_mock *MockRepository) ListAdmin(ctx context.Context, params AdminListParams) ([]domain.Payment, int, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for ListAdmin")
	}

	var r0 []domain.Payment
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, AdminListParams) ([]domain.Payment, int, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, AdminListParams) []domain.Payment); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Payment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, AdminListParams) int); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, AdminListParams) error); ok {
		r2 = returnFunc(ctx, params)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockRepository_ListAdmin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAdmin'
type MockRepository_ListAdmin_Call struct {
	*mock.Call
}

// ListAdmin is a helper method to define mock.On call
//   - ctx context.Context
//   - params AdminListParams
func (_e *MockRepository_Expecter) ListAdmin(ctx any, params any) *MockRepository_ListAdmin_Call {
	return &MockRepository_ListAdmin_Call{Call: _e.mock.On("ListAdmin", ctx, params)}
}

func (_c *MockRepository_ListAdmin_Call) Run(run func(ctx context.Context, params AdminListParams)) *MockRepository_ListAdmin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 AdminListParams
		if args[1] != nil {
			arg1 = args[1].(AdminListParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_ListAdmin_Call) Return(payments []domain.Payment, n int, err error) *MockRepository_ListAdmin_Call {
	_c.Call.Return(payments, n, err)
	return _c
}

func (_c *MockRepository_ListAdmin_Call) RunAndReturn(run func(ctx context.Context, params AdminListParams) ([]domain.Payment, int, error)) *MockRepository_ListAdmin_Call {
	_c.Call.Return(run)
	return _c
}

// MarkPaid provides a mock function for the type MockRepository
func (_mock *MockRepository) MarkPaid(ctx context.Context, id uuid.UUID, fromStatuses []domain.Status) error {
	ret := _mock.Called(ctx, id, fromStatuses)

	if len(ret) == 0 {
		panic("no return value specified for MarkPaid")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, []domain.Status) error); ok {
		r0 = returnFunc(ctx, id, fromStatuses)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_MarkPaid_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkPaid'
type MockRepository_MarkPaid_Call struct {
	*mock.Call
}

// MarkPaid is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - fromStatuses []domain.Status
func (_e *MockRepository_Expecter) MarkPaid(ctx any, id any, fromStatuses any) *MockRepository_MarkPaid_Call {
	return &MockRepository_MarkPaid_Call{Call: _e.mock.On("MarkPaid", ctx, id, fromStatuses)}
}

func (_c *MockRepository_MarkPaid_Call) Run(run func(ctx context.Context, id uuid.UUID, fromStatuses []domain.Status)) *MockRepository_MarkPaid_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 []domain.Status
		if args[2] != nil {
			arg2 = args[2].([]domain.Status)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_MarkPaid_Call) Return(err error) *MockRepository_MarkPaid_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_MarkPaid_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, fromStatuses []domain.Status) error) *MockRepository_MarkPaid_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateGateway provides a mock function for the type MockRepository
func (_mock *MockRepository) UpdateGateway(ctx context.Context, id uuid.UUID, txnID string, response []byte) error {
	ret := _mock.Called(ctx, id, txnID, response)

	if len(ret) == 0 {
		panic("no return value specified for UpdateGateway")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, []byte) error); ok {
		r0 = returnFunc(ctx, id, txnID, response)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_UpdateGateway_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateGateway'
type MockRepository_UpdateGateway_Call struct {
	*mock.Call
}

// UpdateGateway is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - txnID string
//   - response []byte
func (_e *MockRepository_Expecter) UpdateGateway(ctx any, id any, txnID any, response any) *MockRepository_UpdateGateway_Call {
	return &MockRepository_UpdateGateway_Call{Call: _e.mock.On("UpdateGateway", ctx, id, txnID, response)}
}

func (_c *MockRepository_UpdateGateway_Call) Run(run func(ctx context.Context, id uuid.UUID, txnID string, response []byte)) *MockRepository_UpdateGateway_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []byte
		if args[3] != nil {
			arg3 = args[3].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRepository_UpdateGateway_Call) Return(err error) *MockRepository_UpdateGateway_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_UpdateGateway_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, txnID string, response []byte) error) *MockRepository_UpdateGateway_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePaymentURL provides a mock function for the type MockRepository
func (_mock *MockRepository) UpdatePaymentURL(ctx context.Context, id uuid.UUID, paymentURL string) error {
	ret := _mock.Called(ctx, id, paymentURL)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePaymentURL")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = returnFunc(ctx, id, paymentURL)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_UpdatePaymentURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePaymentURL'
type MockRepository_UpdatePaymentURL_Call struct {
	*mock.Call
}

// UpdatePaymentURL is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - paymentURL string
func (_e *MockRepository_Expecter) UpdatePaymentURL(ctx any, id any, paymentURL any) *MockRepository_UpdatePaymentURL_Call {
	return &MockRepository_UpdatePaymentURL_Call{Call: _e.mock.On("UpdatePaymentURL", ctx, id, paymentURL)}
}

func (_c *MockRepository_UpdatePaymentURL_Call) Run(run func(ctx context.Context, id uuid.UUID, paymentURL string)) *MockRepository_UpdatePaymentURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_UpdatePaymentURL_Call) Return(err error) *MockRepository_UpdatePaymentURL_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_UpdatePaymentURL_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, paymentURL string) error) *MockRepository_UpdatePaymentURL_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function for the type MockRepository
func (_mock *MockRepository) UpdateStatus(ctx context.Context, id uuid.UUID, toStatus domain.Status, fromStatuses []domain.Status) error {
	ret := _mock.Called(ctx, id, toStatus, fromStatuses)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, domain.Status, []domain.Status) error); ok {
		r0 = returnFunc(ctx, id, toStatus, fromStatuses)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type MockRepository_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - toStatus domain.Status
//   - fromStatuses []domain.Status
func (_e *MockRepository_Expecter) UpdateStatus(ctx any, id any, toStatus any, fromStatuses any) *MockRepository_UpdateStatus_Call {
	return &MockRepository_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", ctx, id, toStatus, fromStatuses)}
}

func (_c *MockRepository_UpdateStatus_Call) Run(run func(ctx context.Context, id uuid.UUID, toStatus domain.Status, fromStatuses []domain.Status)) *MockRepository_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 domain.Status
		if args[2] != nil {
			arg2 = args[2].(domain.Status)
		}
		var arg3 []domain.Status
		if args[3] != nil {
			arg3 = args[3].([]domain.Status)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRepository_UpdateStatus_Call) Return(err error) *MockRepository_UpdateStatus_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_UpdateStatus_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, toStatus domain.Status, fromStatuses []domain.Status) error) *MockRepository_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}
