// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package http

import (
	"context"

	"github.com/google/uuid"
	"github.com/residwi/go-api-project-template/internal/modules/inventory/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAdjuster creates a new instance of MockAdjuster. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAdjuster(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAdjuster {
	mock := &MockAdjuster{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAdjuster is an autogenerated mock type for the Adjuster type
type MockAdjuster struct {
	mock.Mock
}

type MockAdjuster_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAdjuster) EXPECT() *MockAdjuster_Expecter {
	return &MockAdjuster_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type MockAdjuster
func (_mock *MockAdjuster) Execute(ctx context.Context, productID uuid.UUID, newQuantity int) (*domain.Stock, error) {
	ret := _mock.Called(ctx, productID, newQuantity)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *domain.Stock
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int) (*domain.Stock, error)); ok {
		return returnFunc(ctx, productID, newQuantity)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int) *domain.Stock); ok {
		r0 = returnFunc(ctx, productID, newQuantity)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Stock)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, int) error); ok {
		r1 = returnFunc(ctx, productID, newQuantity)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAdjuster_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockAdjuster_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - productID uuid.UUID
//   - newQuantity int
func (_e *MockAdjuster_Expecter) Execute(ctx any, productID any, newQuantity any) *MockAdjuster_Execute_Call {
	return &MockAdjuster_Execute_Call{Call: _e.mock.On("Execute", ctx, productID, newQuantity)}
}

func (_c *MockAdjuster_Execute_Call) Run(run func(ctx context.Context, productID uuid.UUID, newQuantity int)) *MockAdjuster_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAdjuster_Execute_Call) Return(stock *domain.Stock, err error) *MockAdjuster_Execute_Call {
	_c.Call.Return(stock, err)
	return _c
}

func (_c *MockAdjuster_Execute_Call) RunAndReturn(run func(ctx context.Context, productID uuid.UUID, newQuantity int) (*domain.Stock, error)) *MockAdjuster_Execute_Call {
	_c.Call.Return(run)
	return _c
}
