// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package jobs

import (
	"context"
	"time"

	"github.com/residwi/go-api-project-template/internal/modules/notification/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// Claim provides a mock function for the type MockRepository
func (_mock *MockRepository) Claim(ctx context.Context, batch int, lease time.Duration) ([]domain.Job, error) {
	ret := _mock.Called(ctx, batch, lease)

	if len(ret) == 0 {
		panic("no return value specified for Claim")
	}

	var r0 []domain.Job
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, time.Duration) ([]domain.Job, error)); ok {
		return returnFunc(ctx, batch, lease)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, time.Duration) []domain.Job); ok {
		r0 = returnFunc(ctx, batch, lease)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Job)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, time.Duration) error); ok {
		r1 = returnFunc(ctx, batch, lease)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_Claim_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Claim'
type MockRepository_Claim_Call struct {
	*mock.Call
}

// Claim is a helper method to define mock.On call
//   - ctx context.Context
//   - batch int
//   - lease time.Duration
func (_e *MockRepository_Expecter) Claim(ctx any, batch any, lease any) *MockRepository_Claim_Call {
	return &MockRepository_Claim_Call{Call: _e.mock.On("Claim", ctx, batch, lease)}
}

func (_c *MockRepository_Claim_Call) Run(run func(ctx context.Context, batch int, lease time.Duration)) *MockRepository_Claim_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 time.Duration
		if args[2] != nil {
			arg2 = args[2].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_Claim_Call) Return(jobs []domain.Job, err error) *MockRepository_Claim_Call {
	_c.Call.Return(jobs, err)
	return _c
}

func (_c *MockRepository_Claim_Call) RunAndReturn(run func(ctx context.Context, batch int, lease time.Duration) ([]domain.Job, error)) *MockRepository_Claim_Call {
	_c.Call.Return(run)
	return _c
}

// CreateAndComplete provides a mock function for the type MockRepository
func (_mock *MockRepository) CreateAndComplete(ctx context.Context, n *domain.Notification, job *domain.Job) error {
	ret := _mock.Called(ctx, n, job)

	if len(ret) == 0 {
		panic("no return value specified for CreateAndComplete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Notification, *domain.Job) error); ok {
		r0 = returnFunc(ctx, n, job)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_CreateAndComplete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAndComplete'
type MockRepository_CreateAndComplete_Call struct {
	*mock.Call
}

// CreateAndComplete is a helper method to define mock.On call
//   - ctx context.Context
//   - n *domain.Notification
//   - job *domain.Job
func (_e *MockRepository_Expecter) CreateAndComplete(ctx any, n any, job any) *MockRepository_CreateAndComplete_Call {
	return &MockRepository_CreateAndComplete_Call{Call: _e.mock.On("CreateAndComplete", ctx, n, job)}
}

func (_c *MockRepository_CreateAndComplete_Call) Run(run func(ctx context.Context, n *domain.Notification, job *domain.Job)) *MockRepository_CreateAndComplete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Notification
		if args[1] != nil {
			arg1 = args[1].(*domain.Notification)
		}
		var arg2 *domain.Job
		if args[2] != nil {
			arg2 = args[2].(*domain.Job)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_CreateAndComplete_Call) Return(err error) *MockRepository_CreateAndComplete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_CreateAndComplete_Call) RunAndReturn(run func(ctx context.Context, n *domain.Notification, job *domain.Job) error) *MockRepository_CreateAndComplete_Call {
	_c.Call.Return(run)
	return _c
}

// CreateJob provides a mock function for the type MockRepository
func (_mock *MockRepository) CreateJob(ctx context.Context, job *domain.Job) error {
	ret := _mock.Called(ctx, job)

	if len(ret) == 0 {
		panic("no return value specified for CreateJob")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Job) error); ok {
		r0 = returnFunc(ctx, job)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_CreateJob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateJob'
type MockRepository_CreateJob_Call struct {
	*mock.Call
}

// CreateJob is a helper method to define mock.On call
//   - ctx context.Context
//   - job *domain.Job
func (_e *MockRepository_Expecter) CreateJob(ctx any, job any) *MockRepository_CreateJob_Call {
	return &MockRepository_CreateJob_Call{Call: _e.mock.On("CreateJob", ctx, job)}
}

func (_c *MockRepository_CreateJob_Call) Run(run func(ctx context.Context, job *domain.Job)) *MockRepository_CreateJob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Job
		if args[1] != nil {
			arg1 = args[1].(*domain.Job)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_CreateJob_Call) Return(err error) *MockRepository_CreateJob_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_CreateJob_Call) RunAndReturn(run func(ctx context.Context, job *domain.Job) error) *MockRepository_CreateJob_Call {
	_c.Call.Return(run)
	return _c
}

// Prune provides a mock function for the type MockRepository
func (_mock *MockRepository) Prune(ctx context.Context, age time.Duration, limit int) (int, error) {
	ret := _mock.Called(ctx, age, limit)

	if len(ret) == 0 {
		panic("no return value specified for Prune")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Duration, int) (int, error)); ok {
		return returnFunc(ctx, age, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Duration, int) int); ok {
		r0 = returnFunc(ctx, age, limit)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, time.Duration, int) error); ok {
		r1 = returnFunc(ctx, age, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_Prune_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Prune'
type MockRepository_Prune_Call struct {
	*mock.Call
}

// Prune is a helper method to define mock.On call
//   - ctx context.Context
//   - age time.Duration
//   - limit int
func (_e *MockRepository_Expecter) Prune(ctx any, age any, limit any) *MockRepository_Prune_Call {
	return &MockRepository_Prune_Call{Call: _e.mock.On("Prune", ctx, age, limit)}
}

func (_c *MockRepository_Prune_Call) Run(run func(ctx context.Context, age time.Duration, limit int)) *MockRepository_Prune_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Duration
		if args[1] != nil {
			arg1 = args[1].(time.Duration)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_Prune_Call) Return(n int, err error) *MockRepository_Prune_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockRepository_Prune_Call) RunAndReturn(run func(ctx context.Context, age time.Duration, limit int) (int, error)) *MockRepository_Prune_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateJob provides a mock function for the type MockRepository
func (_mock *MockRepository) UpdateJob(ctx context.Context, job *domain.Job) error {
	ret := _mock.Called(ctx, job)

	if len(ret) == 0 {
		panic("no return value specified for UpdateJob")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Job) error); ok {
		r0 = returnFunc(ctx, job)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_UpdateJob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateJob'
type MockRepository_UpdateJob_Call struct {
	*mock.Call
}

// UpdateJob is a helper method to define mock.On call
//   - ctx context.Context
//   - job *domain.Job
func (_e *MockRepository_Expecter) UpdateJob(ctx any, job any) *MockRepository_UpdateJob_Call {
	return &MockRepository_UpdateJob_Call{Call: _e.mock.On("UpdateJob", ctx, job)}
}

func (_c *MockRepository_UpdateJob_Call) Run(run func(ctx context.Context, job *domain.Job)) *MockRepository_UpdateJob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Job
		if args[1] != nil {
			arg1 = args[1].(*domain.Job)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_UpdateJob_Call) Return(err error) *MockRepository_UpdateJob_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_UpdateJob_Call) RunAndReturn(run func(ctx context.Context, job *domain.Job) error) *MockRepository_UpdateJob_Call {
	_c.Call.Return(run)
	return _c
}
