// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package review

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"

	"github.com/residwi/go-api-project-template/internal/modules/review/domain"
	"github.com/residwi/go-api-project-template/internal/platform/paging"
)

// NewMockPurchaseVerifier creates a new instance of MockPurchaseVerifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPurchaseVerifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPurchaseVerifier {
	mock := &MockPurchaseVerifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPurchaseVerifier is an autogenerated mock type for the PurchaseVerifier type
type MockPurchaseVerifier struct {
	mock.Mock
}

type MockPurchaseVerifier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPurchaseVerifier) EXPECT() *MockPurchaseVerifier_Expecter {
	return &MockPurchaseVerifier_Expecter{mock: &_m.Mock}
}

// HasDeliveredOrder provides a mock function for the type MockPurchaseVerifier
func (_mock *MockPurchaseVerifier) HasDeliveredOrder(ctx context.Context, userID uuid.UUID, orderID uuid.UUID, productID uuid.UUID) (bool, error) {
	ret := _mock.Called(ctx, userID, orderID, productID)

	if len(ret) == 0 {
		panic("no return value specified for HasDeliveredOrder")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) (bool, error)); ok {
		return returnFunc(ctx, userID, orderID, productID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) bool); ok {
		r0 = returnFunc(ctx, userID, orderID, productID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID, orderID, productID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPurchaseVerifier_HasDeliveredOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasDeliveredOrder'
type MockPurchaseVerifier_HasDeliveredOrder_Call struct {
	*mock.Call
}

// HasDeliveredOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - orderID uuid.UUID
//   - productID uuid.UUID
func (_e *MockPurchaseVerifier_Expecter) HasDeliveredOrder(ctx any, userID any, orderID any, productID any) *MockPurchaseVerifier_HasDeliveredOrder_Call {
	return &MockPurchaseVerifier_HasDeliveredOrder_Call{Call: _e.mock.On("HasDeliveredOrder", ctx, userID, orderID, productID)}
}

func (_c *MockPurchaseVerifier_HasDeliveredOrder_Call) Run(run func(ctx context.Context, userID uuid.UUID, orderID uuid.UUID, productID uuid.UUID)) *MockPurchaseVerifier_HasDeliveredOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 uuid.UUID
		if args[3] != nil {
			arg3 = args[3].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockPurchaseVerifier_HasDeliveredOrder_Call) Return(b bool, err error) *MockPurchaseVerifier_HasDeliveredOrder_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockPurchaseVerifier_HasDeliveredOrder_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, orderID uuid.UUID, productID uuid.UUID) (bool, error)) *MockPurchaseVerifier_HasDeliveredOrder_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockRepository
func (_mock *MockRepository) Create(ctx context.Context, rv *domain.Review) error {
	ret := _mock.Called(ctx, rv)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Review) error); ok {
		r0 = returnFunc(ctx, rv)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - rv *domain.Review
func (_e *MockRepository_Expecter) Create(ctx any, rv any) *MockRepository_Create_Call {
	return &MockRepository_Create_Call{Call: _e.mock.On("Create", ctx, rv)}
}

func (_c *MockRepository_Create_Call) Run(run func(ctx context.Context, rv *domain.Review)) *MockRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Review
		if args[1] != nil {
			arg1 = args[1].(*domain.Review)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Create_Call) Return(err error) *MockRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Create_Call) RunAndReturn(run func(ctx context.Context, rv *domain.Review) error) *MockRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockRepository
func (_mock *MockRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockRepository_Expecter) Delete(ctx any, id any) *MockRepository_Delete_Call {
	return &MockRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Delete_Call) Return(err error) *MockRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *MockRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetStats provides a mock function for the type MockRepository
func (_mock *MockRepository) GetStats(ctx context.Context, productID uuid.UUID) (domain.Stats, error) {
	ret := _mock.Called(ctx, productID)

	if len(ret) == 0 {
		panic("no return value specified for GetStats")
	}

	var r0 domain.Stats
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (domain.Stats, error)); ok {
		return returnFunc(ctx, productID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) domain.Stats); ok {
		r0 = returnFunc(ctx, productID)
	} else {
		r0 = ret.Get(0).(domain.Stats)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, productID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStats'
type MockRepository_GetStats_Call struct {
	*mock.Call
}

// GetStats is a helper method to define mock.On call
//   - ctx context.Context
//   - productID uuid.UUID
func (_e *MockRepository_Expecter) GetStats(ctx any, productID any) *MockRepository_GetStats_Call {
	return &MockRepository_GetStats_Call{Call: _e.mock.On("GetStats", ctx, productID)}
}

func (_c *MockRepository_GetStats_Call) Run(run func(ctx context.Context, productID uuid.UUID)) *MockRepository_GetStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetStats_Call) Return(stats domain.Stats, err error) *MockRepository_GetStats_Call {
	_c.Call.Return(stats, err)
	return _c
}

func (_c *MockRepository_GetStats_Call) RunAndReturn(run func(ctx context.Context, productID uuid.UUID) (domain.Stats, error)) *MockRepository_GetStats_Call {
	_c.Call.Return(run)
	return _c
}

// HasUserReviewed provides a mock function for the type MockRepository
func (_mock *MockRepository) HasUserReviewed(ctx context.Context, userID uuid.UUID, productID uuid.UUID) (bool, error) {
	ret := _mock.Called(ctx, userID, productID)

	if len(ret) == 0 {
		panic("no return value specified for HasUserReviewed")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (bool, error)); ok {
		return returnFunc(ctx, userID, productID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) bool); ok {
		r0 = returnFunc(ctx, userID, productID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID, productID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_HasUserReviewed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasUserReviewed'
type MockRepository_HasUserReviewed_Call struct {
	*mock.Call
}

// HasUserReviewed is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - productID uuid.UUID
func (_e *MockRepository_Expecter) HasUserReviewed(ctx any, userID any, productID any) *MockRepository_HasUserReviewed_Call {
	return &MockRepository_HasUserReviewed_Call{Call: _e.mock.On("HasUserReviewed", ctx, userID, productID)}
}

func (_c *MockRepository_HasUserReviewed_Call) Run(run func(ctx context.Context, userID uuid.UUID, productID uuid.UUID)) *MockRepository_HasUserReviewed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_HasUserReviewed_Call) Return(b bool, err error) *MockRepository_HasUserReviewed_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockRepository_HasUserReviewed_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, productID uuid.UUID) (bool, error)) *MockRepository_HasUserReviewed_Call {
	_c.Call.Return(run)
	return _c
}

// ListByProduct provides a mock function for the type MockRepository
func (_mock *MockRepository) ListByProduct(ctx context.Context, productID uuid.UUID, cursor paging.CursorPage) ([]domain.Review, error) {
	ret := _mock.Called(ctx, productID, cursor)

	if len(ret) == 0 {
		panic("no return value specified for ListByProduct")
	}

	var r0 []domain.Review
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, paging.CursorPage) ([]domain.Review, error)); ok {
		return returnFunc(ctx, productID, cursor)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, paging.CursorPage) []domain.Review); ok {
		r0 = returnFunc(ctx, productID, cursor)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Review)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, paging.CursorPage) error); ok {
		r1 = returnFunc(ctx, productID, cursor)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_ListByProduct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByProduct'
type MockRepository_ListByProduct_Call struct {
	*mock.Call
}

// ListByProduct is a helper method to define mock.On call
//   - ctx context.Context
//   - productID uuid.UUID
//   - cursor paging.CursorPage
func (_e *MockRepository_Expecter) ListByProduct(ctx any, productID any, cursor any) *MockRepository_ListByProduct_Call {
	return &MockRepository_ListByProduct_Call{Call: _e.mock.On("ListByProduct", ctx, productID, cursor)}
}

func (_c *MockRepository_ListByProduct_Call) Run(run func(ctx context.Context, productID uuid.UUID, cursor paging.CursorPage)) *MockRepository_ListByProduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 paging.CursorPage
		if args[2] != nil {
			arg2 = args[2].(paging.CursorPage)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_ListByProduct_Call) Return(reviews []domain.Review, err error) *MockRepository_ListByProduct_Call {
	_c.Call.Return(reviews, err)
	return _c
}

func (_c *MockRepository_ListByProduct_Call) RunAndReturn(run func(ctx context.Context, productID uuid.UUID, cursor paging.CursorPage) ([]domain.Review, error)) *MockRepository_ListByProduct_Call {
	_c.Call.Return(run)
	return _c
}
