// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package request

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockValidator creates a new instance of MockValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockValidator {
	mock := &MockValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockValidator is an autogenerated mock type for the Validator type
type MockValidator struct {
	mock.Mock
}

type MockValidator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockValidator) EXPECT() *MockValidator_Expecter {
	return &MockValidator_Expecter{mock: &_m.Mock}
}

// Validate provides a mock function for the type MockValidator
func (_mock *MockValidator) Validate(s any) map[string]any {
	ret := _mock.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for Validate")
	}

	var r0 map[string]any
	if returnFunc, ok := ret.Get(0).(func(any) map[string]any); ok {
		r0 = returnFunc(s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]any)
		}
	}
	return r0
}

// MockValidator_Validate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Validate'
type MockValidator_Validate_Call struct {
	*mock.Call
}

// Validate is a helper method to define mock.On call
//   - s any
func (_e *MockValidator_Expecter) Validate(s any) *MockValidator_Validate_Call {
	return &MockValidator_Validate_Call{Call: _e.mock.On("Validate", s)}
}

func (_c *MockValidator_Validate_Call) Run(run func(s any)) *MockValidator_Validate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 any
		if args[0] != nil {
			arg0 = args[0].(any)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockValidator_Validate_Call) Return(stringToV map[string]any) *MockValidator_Validate_Call {
	_c.Call.Return(stringToV)
	return _c
}

func (_c *MockValidator_Validate_Call) RunAndReturn(run func(s any) map[string]any) *MockValidator_Validate_Call {
	_c.Call.Return(run)
	return _c
}
