// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package http

import (
	"context"

	"github.com/google/uuid"
	"github.com/residwi/go-api-project-template/internal/modules/order/usecase/retrypayment"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUseCase creates a new instance of MockUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUseCase {
	mock := &MockUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUseCase is an autogenerated mock type for the UseCase type
type MockUseCase struct {
	mock.Mock
}

type MockUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUseCase) EXPECT() *MockUseCase_Expecter {
	return &MockUseCase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type MockUseCase
func (_mock *MockUseCase) Execute(ctx context.Context, userID uuid.UUID, orderID uuid.UUID, p retrypayment.Params) (*retrypayment.Result, error) {
	ret := _mock.Called(ctx, userID, orderID, p)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *retrypayment.Result
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, retrypayment.Params) (*retrypayment.Result, error)); ok {
		return returnFunc(ctx, userID, orderID, p)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, retrypayment.Params) *retrypayment.Result); ok {
		r0 = returnFunc(ctx, userID, orderID, p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*retrypayment.Result)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, retrypayment.Params) error); ok {
		r1 = returnFunc(ctx, userID, orderID, p)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUseCase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockUseCase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - orderID uuid.UUID
//   - p retrypayment.Params
func (_e *MockUseCase_Expecter) Execute(ctx any, userID any, orderID any, p any) *MockUseCase_Execute_Call {
	return &MockUseCase_Execute_Call{Call: _e.mock.On("Execute", ctx, userID, orderID, p)}
}

func (_c *MockUseCase_Execute_Call) Run(run func(ctx context.Context, userID uuid.UUID, orderID uuid.UUID, p retrypayment.Params)) *MockUseCase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 retrypayment.Params
		if args[3] != nil {
			arg3 = args[3].(retrypayment.Params)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockUseCase_Execute_Call) Return(v *retrypayment.Result, err error) *MockUseCase_Execute_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockUseCase_Execute_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, orderID uuid.UUID, p retrypayment.Params) (*retrypayment.Result, error)) *MockUseCase_Execute_Call {
	_c.Call.Return(run)
	return _c
}
