// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/residwi/go-api-project-template/internal/review"
	mock "github.com/stretchr/testify/mock"
)

// NewMockPurchaseVerifier creates a new instance of MockPurchaseVerifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPurchaseVerifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPurchaseVerifier {
	mock := &MockPurchaseVerifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPurchaseVerifier is an autogenerated mock type for the PurchaseVerifier type
type MockPurchaseVerifier struct {
	mock.Mock
}

type MockPurchaseVerifier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPurchaseVerifier) EXPECT() *MockPurchaseVerifier_Expecter {
	return &MockPurchaseVerifier_Expecter{mock: &_m.Mock}
}

// HasDeliveredOrder provides a mock function for the type MockPurchaseVerifier
func (_mock *MockPurchaseVerifier) HasDeliveredOrder(ctx context.Context, p review.DeliveredPurchase) (bool, error) {
	ret := _mock.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for HasDeliveredOrder")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, review.DeliveredPurchase) (bool, error)); ok {
		return returnFunc(ctx, p)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, review.DeliveredPurchase) bool); ok {
		r0 = returnFunc(ctx, p)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, review.DeliveredPurchase) error); ok {
		r1 = returnFunc(ctx, p)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPurchaseVerifier_HasDeliveredOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasDeliveredOrder'
type MockPurchaseVerifier_HasDeliveredOrder_Call struct {
	*mock.Call
}

// HasDeliveredOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - p review.DeliveredPurchase
func (_e *MockPurchaseVerifier_Expecter) HasDeliveredOrder(ctx any, p any) *MockPurchaseVerifier_HasDeliveredOrder_Call {
	return &MockPurchaseVerifier_HasDeliveredOrder_Call{Call: _e.mock.On("HasDeliveredOrder", ctx, p)}
}

func (_c *MockPurchaseVerifier_HasDeliveredOrder_Call) Run(run func(ctx context.Context, p review.DeliveredPurchase)) *MockPurchaseVerifier_HasDeliveredOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 review.DeliveredPurchase
		if args[1] != nil {
			arg1 = args[1].(review.DeliveredPurchase)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPurchaseVerifier_HasDeliveredOrder_Call) Return(b bool, err error) *MockPurchaseVerifier_HasDeliveredOrder_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockPurchaseVerifier_HasDeliveredOrder_Call) RunAndReturn(run func(ctx context.Context, p review.DeliveredPurchase) (bool, error)) *MockPurchaseVerifier_HasDeliveredOrder_Call {
	_c.Call.Return(run)
	return _c
}
