// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package auth

import (
	"context"
	"time"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"

	"github.com/residwi/go-api-project-template/internal/features/auth/domain"
	"github.com/residwi/go-api-project-template/internal/features/user"
)

// NewMockUserDirectory creates a new instance of MockUserDirectory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserDirectory(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserDirectory {
	mock := &MockUserDirectory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserDirectory is an autogenerated mock type for the UserDirectory type
type MockUserDirectory struct {
	mock.Mock
}

type MockUserDirectory_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserDirectory) EXPECT() *MockUserDirectory_Expecter {
	return &MockUserDirectory_Expecter{mock: &_m.Mock}
}

// CheckStatus provides a mock function for the type MockUserDirectory
func (_mock *MockUserDirectory) CheckStatus(ctx context.Context, id uuid.UUID) (user.AccountStatus, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for CheckStatus")
	}

	var r0 user.AccountStatus
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (user.AccountStatus, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) user.AccountStatus); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(user.AccountStatus)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserDirectory_CheckStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckStatus'
type MockUserDirectory_CheckStatus_Call struct {
	*mock.Call
}

// CheckStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockUserDirectory_Expecter) CheckStatus(ctx any, id any) *MockUserDirectory_CheckStatus_Call {
	return &MockUserDirectory_CheckStatus_Call{Call: _e.mock.On("CheckStatus", ctx, id)}
}

func (_c *MockUserDirectory_CheckStatus_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockUserDirectory_CheckStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserDirectory_CheckStatus_Call) Return(accountStatus user.AccountStatus, err error) *MockUserDirectory_CheckStatus_Call {
	_c.Call.Return(accountStatus, err)
	return _c
}

func (_c *MockUserDirectory_CheckStatus_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (user.AccountStatus, error)) *MockUserDirectory_CheckStatus_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockUserDirectory
func (_mock *MockUserDirectory) Create(ctx context.Context, p user.NewUser) (user.Profile, error) {
	ret := _mock.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 user.Profile
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, user.NewUser) (user.Profile, error)); ok {
		return returnFunc(ctx, p)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, user.NewUser) user.Profile); ok {
		r0 = returnFunc(ctx, p)
	} else {
		r0 = ret.Get(0).(user.Profile)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, user.NewUser) error); ok {
		r1 = returnFunc(ctx, p)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserDirectory_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockUserDirectory_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - p user.NewUser
func (_e *MockUserDirectory_Expecter) Create(ctx any, p any) *MockUserDirectory_Create_Call {
	return &MockUserDirectory_Create_Call{Call: _e.mock.On("Create", ctx, p)}
}

func (_c *MockUserDirectory_Create_Call) Run(run func(ctx context.Context, p user.NewUser)) *MockUserDirectory_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 user.NewUser
		if args[1] != nil {
			arg1 = args[1].(user.NewUser)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserDirectory_Create_Call) Return(profile user.Profile, err error) *MockUserDirectory_Create_Call {
	_c.Call.Return(profile, err)
	return _c
}

func (_c *MockUserDirectory_Create_Call) RunAndReturn(run func(ctx context.Context, p user.NewUser) (user.Profile, error)) *MockUserDirectory_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByEmail provides a mock function for the type MockUserDirectory
func (_mock *MockUserDirectory) GetByEmail(ctx context.Context, email string) (user.Credentials, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetByEmail")
	}

	var r0 user.Credentials
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (user.Credentials, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) user.Credentials); ok {
		r0 = returnFunc(ctx, email)
	} else {
		r0 = ret.Get(0).(user.Credentials)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserDirectory_GetByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByEmail'
type MockUserDirectory_GetByEmail_Call struct {
	*mock.Call
}

// GetByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockUserDirectory_Expecter) GetByEmail(ctx any, email any) *MockUserDirectory_GetByEmail_Call {
	return &MockUserDirectory_GetByEmail_Call{Call: _e.mock.On("GetByEmail", ctx, email)}
}

func (_c *MockUserDirectory_GetByEmail_Call) Run(run func(ctx context.Context, email string)) *MockUserDirectory_GetByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserDirectory_GetByEmail_Call) Return(credentials user.Credentials, err error) *MockUserDirectory_GetByEmail_Call {
	_c.Call.Return(credentials, err)
	return _c
}

func (_c *MockUserDirectory_GetByEmail_Call) RunAndReturn(run func(ctx context.Context, email string) (user.Credentials, error)) *MockUserDirectory_GetByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockUserDirectory
func (_mock *MockUserDirectory) GetByID(ctx context.Context, id uuid.UUID) (user.Profile, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 user.Profile
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (user.Profile, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) user.Profile); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(user.Profile)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserDirectory_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockUserDirectory_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockUserDirectory_Expecter) GetByID(ctx any, id any) *MockUserDirectory_GetByID_Call {
	return &MockUserDirectory_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockUserDirectory_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockUserDirectory_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserDirectory_GetByID_Call) Return(profile user.Profile, err error) *MockUserDirectory_GetByID_Call {
	_c.Call.Return(profile, err)
	return _c
}

func (_c *MockUserDirectory_GetByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (user.Profile, error)) *MockUserDirectory_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTokens creates a new instance of MockTokens. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokens(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokens {
	mock := &MockTokens{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTokens is an autogenerated mock type for the Tokens type
type MockTokens struct {
	mock.Mock
}

type MockTokens_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokens) EXPECT() *MockTokens_Expecter {
	return &MockTokens_Expecter{mock: &_m.Mock}
}

// Issue provides a mock function for the type MockTokens
func (_mock *MockTokens) Issue(claims domain.Claims, kind domain.Kind, ttl time.Duration) (string, error) {
	ret := _mock.Called(claims, kind, ttl)

	if len(ret) == 0 {
		panic("no return value specified for Issue")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(domain.Claims, domain.Kind, time.Duration) (string, error)); ok {
		return returnFunc(claims, kind, ttl)
	}
	if returnFunc, ok := ret.Get(0).(func(domain.Claims, domain.Kind, time.Duration) string); ok {
		r0 = returnFunc(claims, kind, ttl)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(domain.Claims, domain.Kind, time.Duration) error); ok {
		r1 = returnFunc(claims, kind, ttl)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokens_Issue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Issue'
type MockTokens_Issue_Call struct {
	*mock.Call
}

// Issue is a helper method to define mock.On call
//   - claims domain.Claims
//   - kind domain.Kind
//   - ttl time.Duration
func (_e *MockTokens_Expecter) Issue(claims any, kind any, ttl any) *MockTokens_Issue_Call {
	return &MockTokens_Issue_Call{Call: _e.mock.On("Issue", claims, kind, ttl)}
}

func (_c *MockTokens_Issue_Call) Run(run func(claims domain.Claims, kind domain.Kind, ttl time.Duration)) *MockTokens_Issue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 domain.Claims
		if args[0] != nil {
			arg0 = args[0].(domain.Claims)
		}
		var arg1 domain.Kind
		if args[1] != nil {
			arg1 = args[1].(domain.Kind)
		}
		var arg2 time.Duration
		if args[2] != nil {
			arg2 = args[2].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTokens_Issue_Call) Return(s string, err error) *MockTokens_Issue_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockTokens_Issue_Call) RunAndReturn(run func(claims domain.Claims, kind domain.Kind, ttl time.Duration) (string, error)) *MockTokens_Issue_Call {
	_c.Call.Return(run)
	return _c
}

// Verify provides a mock function for the type MockTokens
func (_mock *MockTokens) Verify(token string, want domain.Kind) (domain.Claims, error) {
	ret := _mock.Called(token, want)

	if len(ret) == 0 {
		panic("no return value specified for Verify")
	}

	var r0 domain.Claims
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, domain.Kind) (domain.Claims, error)); ok {
		return returnFunc(token, want)
	}
	if returnFunc, ok := ret.Get(0).(func(string, domain.Kind) domain.Claims); ok {
		r0 = returnFunc(token, want)
	} else {
		r0 = ret.Get(0).(domain.Claims)
	}
	if returnFunc, ok := ret.Get(1).(func(string, domain.Kind) error); ok {
		r1 = returnFunc(token, want)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokens_Verify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Verify'
type MockTokens_Verify_Call struct {
	*mock.Call
}

// Verify is a helper method to define mock.On call
//   - token string
//   - want domain.Kind
func (_e *MockTokens_Expecter) Verify(token any, want any) *MockTokens_Verify_Call {
	return &MockTokens_Verify_Call{Call: _e.mock.On("Verify", token, want)}
}

func (_c *MockTokens_Verify_Call) Run(run func(token string, want domain.Kind)) *MockTokens_Verify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 domain.Kind
		if args[1] != nil {
			arg1 = args[1].(domain.Kind)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTokens_Verify_Call) Return(claims domain.Claims, err error) *MockTokens_Verify_Call {
	_c.Call.Return(claims, err)
	return _c
}

func (_c *MockTokens_Verify_Call) RunAndReturn(run func(token string, want domain.Kind) (domain.Claims, error)) *MockTokens_Verify_Call {
	_c.Call.Return(run)
	return _c
}
