// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package http

import (
	"context"

	"github.com/residwi/go-api-project-template/internal/modules/auth/domain"
	"github.com/residwi/go-api-project-template/internal/modules/auth/login"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAuthenticator creates a new instance of MockAuthenticator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthenticator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthenticator {
	mock := &MockAuthenticator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthenticator is an autogenerated mock type for the Authenticator type
type MockAuthenticator struct {
	mock.Mock
}

type MockAuthenticator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthenticator) EXPECT() *MockAuthenticator_Expecter {
	return &MockAuthenticator_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type MockAuthenticator
func (_mock *MockAuthenticator) Execute(ctx context.Context, p login.Params) (*domain.TokenPair, error) {
	ret := _mock.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *domain.TokenPair
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, login.Params) (*domain.TokenPair, error)); ok {
		return returnFunc(ctx, p)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, login.Params) *domain.TokenPair); ok {
		r0 = returnFunc(ctx, p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.TokenPair)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, login.Params) error); ok {
		r1 = returnFunc(ctx, p)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthenticator_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockAuthenticator_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - p login.Params
func (_e *MockAuthenticator_Expecter) Execute(ctx any, p any) *MockAuthenticator_Execute_Call {
	return &MockAuthenticator_Execute_Call{Call: _e.mock.On("Execute", ctx, p)}
}

func (_c *MockAuthenticator_Execute_Call) Run(run func(ctx context.Context, p login.Params)) *MockAuthenticator_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 login.Params
		if args[1] != nil {
			arg1 = args[1].(login.Params)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthenticator_Execute_Call) Return(tokenPair *domain.TokenPair, err error) *MockAuthenticator_Execute_Call {
	_c.Call.Return(tokenPair, err)
	return _c
}

func (_c *MockAuthenticator_Execute_Call) RunAndReturn(run func(ctx context.Context, p login.Params) (*domain.TokenPair, error)) *MockAuthenticator_Execute_Call {
	_c.Call.Return(run)
	return _c
}
