// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package http

import (
	"context"

	"github.com/google/uuid"
	"github.com/residwi/go-api-project-template/internal/modules/inventory/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockStockReader creates a new instance of MockStockReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStockReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStockReader {
	mock := &MockStockReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStockReader is an autogenerated mock type for the StockReader type
type MockStockReader struct {
	mock.Mock
}

type MockStockReader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStockReader) EXPECT() *MockStockReader_Expecter {
	return &MockStockReader_Expecter{mock: &_m.Mock}
}

// GetStock provides a mock function for the type MockStockReader
func (_mock *MockStockReader) GetStock(ctx context.Context, productID uuid.UUID) (*domain.Stock, error) {
	ret := _mock.Called(ctx, productID)

	if len(ret) == 0 {
		panic("no return value specified for GetStock")
	}

	var r0 *domain.Stock
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Stock, error)); ok {
		return returnFunc(ctx, productID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Stock); ok {
		r0 = returnFunc(ctx, productID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Stock)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, productID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStockReader_GetStock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStock'
type MockStockReader_GetStock_Call struct {
	*mock.Call
}

// GetStock is a helper method to define mock.On call
//   - ctx context.Context
//   - productID uuid.UUID
func (_e *MockStockReader_Expecter) GetStock(ctx any, productID any) *MockStockReader_GetStock_Call {
	return &MockStockReader_GetStock_Call{Call: _e.mock.On("GetStock", ctx, productID)}
}

func (_c *MockStockReader_GetStock_Call) Run(run func(ctx context.Context, productID uuid.UUID)) *MockStockReader_GetStock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStockReader_GetStock_Call) Return(stock *domain.Stock, err error) *MockStockReader_GetStock_Call {
	_c.Call.Return(stock, err)
	return _c
}

func (_c *MockStockReader_GetStock_Call) RunAndReturn(run func(ctx context.Context, productID uuid.UUID) (*domain.Stock, error)) *MockStockReader_GetStock_Call {
	_c.Call.Return(run)
	return _c
}
