// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package query

import (
	"context"

	"github.com/google/uuid"
	"github.com/residwi/go-api-project-template/internal/modules/order/contract"
	"github.com/residwi/go-api-project-template/internal/modules/shipping/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockOrderGetter creates a new instance of MockOrderGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderGetter {
	mock := &MockOrderGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOrderGetter is an autogenerated mock type for the OrderGetter type
type MockOrderGetter struct {
	mock.Mock
}

type MockOrderGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderGetter) EXPECT() *MockOrderGetter_Expecter {
	return &MockOrderGetter_Expecter{mock: &_m.Mock}
}

// GetInfo provides a mock function for the type MockOrderGetter
func (_mock *MockOrderGetter) GetInfo(ctx context.Context, orderID uuid.UUID) (contract.Order, error) {
	ret := _mock.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for GetInfo")
	}

	var r0 contract.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (contract.Order, error)); ok {
		return returnFunc(ctx, orderID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) contract.Order); ok {
		r0 = returnFunc(ctx, orderID)
	} else {
		r0 = ret.Get(0).(contract.Order)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, orderID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderGetter_GetInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInfo'
type MockOrderGetter_GetInfo_Call struct {
	*mock.Call
}

// GetInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID uuid.UUID
func (_e *MockOrderGetter_Expecter) GetInfo(ctx any, orderID any) *MockOrderGetter_GetInfo_Call {
	return &MockOrderGetter_GetInfo_Call{Call: _e.mock.On("GetInfo", ctx, orderID)}
}

func (_c *MockOrderGetter_GetInfo_Call) Run(run func(ctx context.Context, orderID uuid.UUID)) *MockOrderGetter_GetInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderGetter_GetInfo_Call) Return(order contract.Order, err error) *MockOrderGetter_GetInfo_Call {
	_c.Call.Return(order, err)
	return _c
}

func (_c *MockOrderGetter_GetInfo_Call) RunAndReturn(run func(ctx context.Context, orderID uuid.UUID) (contract.Order, error)) *MockOrderGetter_GetInfo_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// GetByOrderID provides a mock function for the type MockRepository
func (_mock *MockRepository) GetByOrderID(ctx context.Context, orderID uuid.UUID) (*domain.Shipment, error) {
	ret := _mock.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for GetByOrderID")
	}

	var r0 *domain.Shipment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Shipment, error)); ok {
		return returnFunc(ctx, orderID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Shipment); ok {
		r0 = returnFunc(ctx, orderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Shipment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, orderID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetByOrderID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByOrderID'
type MockRepository_GetByOrderID_Call struct {
	*mock.Call
}

// GetByOrderID is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID uuid.UUID
func (_e *MockRepository_Expecter) GetByOrderID(ctx any, orderID any) *MockRepository_GetByOrderID_Call {
	return &MockRepository_GetByOrderID_Call{Call: _e.mock.On("GetByOrderID", ctx, orderID)}
}

func (_c *MockRepository_GetByOrderID_Call) Run(run func(ctx context.Context, orderID uuid.UUID)) *MockRepository_GetByOrderID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetByOrderID_Call) Return(shipment *domain.Shipment, err error) *MockRepository_GetByOrderID_Call {
	_c.Call.Return(shipment, err)
	return _c
}

func (_c *MockRepository_GetByOrderID_Call) RunAndReturn(run func(ctx context.Context, orderID uuid.UUID) (*domain.Shipment, error)) *MockRepository_GetByOrderID_Call {
	_c.Call.Return(run)
	return _c
}
