// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/residwi/go-api-project-template/internal/features/order"
	mock "github.com/stretchr/testify/mock"
)

// NewMockPaymentInitiator creates a new instance of MockPaymentInitiator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPaymentInitiator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPaymentInitiator {
	mock := &MockPaymentInitiator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPaymentInitiator is an autogenerated mock type for the PaymentInitiator type
type MockPaymentInitiator struct {
	mock.Mock
}

type MockPaymentInitiator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPaymentInitiator) EXPECT() *MockPaymentInitiator_Expecter {
	return &MockPaymentInitiator_Expecter{mock: &_m.Mock}
}

// InitiatePayment provides a mock function for the type MockPaymentInitiator
func (_mock *MockPaymentInitiator) InitiatePayment(ctx context.Context, params order.InitiatePaymentParams) (order.PaymentResult, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for InitiatePayment")
	}

	var r0 order.PaymentResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, order.InitiatePaymentParams) (order.PaymentResult, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, order.InitiatePaymentParams) order.PaymentResult); ok {
		r0 = returnFunc(ctx, params)
	} else {
		r0 = ret.Get(0).(order.PaymentResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, order.InitiatePaymentParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPaymentInitiator_InitiatePayment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InitiatePayment'
type MockPaymentInitiator_InitiatePayment_Call struct {
	*mock.Call
}

// InitiatePayment is a helper method to define mock.On call
//   - ctx context.Context
//   - params order.InitiatePaymentParams
func (_e *MockPaymentInitiator_Expecter) InitiatePayment(ctx interface{}, params interface{}) *MockPaymentInitiator_InitiatePayment_Call {
	return &MockPaymentInitiator_InitiatePayment_Call{Call: _e.mock.On("InitiatePayment", ctx, params)}
}

func (_c *MockPaymentInitiator_InitiatePayment_Call) Run(run func(ctx context.Context, params order.InitiatePaymentParams)) *MockPaymentInitiator_InitiatePayment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 order.InitiatePaymentParams
		if args[1] != nil {
			arg1 = args[1].(order.InitiatePaymentParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPaymentInitiator_InitiatePayment_Call) Return(paymentResult order.PaymentResult, err error) *MockPaymentInitiator_InitiatePayment_Call {
	_c.Call.Return(paymentResult, err)
	return _c
}

func (_c *MockPaymentInitiator_InitiatePayment_Call) RunAndReturn(run func(ctx context.Context, params order.InitiatePaymentParams) (order.PaymentResult, error)) *MockPaymentInitiator_InitiatePayment_Call {
	_c.Call.Return(run)
	return _c
}
