// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package shipping

import (
	"context"

	"github.com/google/uuid"
	"github.com/residwi/go-api-project-template/internal/modules/order"
	"github.com/residwi/go-api-project-template/internal/modules/shipping/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockOrderGetter creates a new instance of MockOrderGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderGetter {
	mock := &MockOrderGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOrderGetter is an autogenerated mock type for the OrderGetter type
type MockOrderGetter struct {
	mock.Mock
}

type MockOrderGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderGetter) EXPECT() *MockOrderGetter_Expecter {
	return &MockOrderGetter_Expecter{mock: &_m.Mock}
}

// Snapshot provides a mock function for the type MockOrderGetter
func (_mock *MockOrderGetter) Snapshot(ctx context.Context, orderID uuid.UUID) (order.Snapshot, error) {
	ret := _mock.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for Snapshot")
	}

	var r0 order.Snapshot
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (order.Snapshot, error)); ok {
		return returnFunc(ctx, orderID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) order.Snapshot); ok {
		r0 = returnFunc(ctx, orderID)
	} else {
		r0 = ret.Get(0).(order.Snapshot)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, orderID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderGetter_Snapshot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Snapshot'
type MockOrderGetter_Snapshot_Call struct {
	*mock.Call
}

// Snapshot is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID uuid.UUID
func (_e *MockOrderGetter_Expecter) Snapshot(ctx any, orderID any) *MockOrderGetter_Snapshot_Call {
	return &MockOrderGetter_Snapshot_Call{Call: _e.mock.On("Snapshot", ctx, orderID)}
}

func (_c *MockOrderGetter_Snapshot_Call) Run(run func(ctx context.Context, orderID uuid.UUID)) *MockOrderGetter_Snapshot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderGetter_Snapshot_Call) Return(snapshot order.Snapshot, err error) *MockOrderGetter_Snapshot_Call {
	_c.Call.Return(snapshot, err)
	return _c
}

func (_c *MockOrderGetter_Snapshot_Call) RunAndReturn(run func(ctx context.Context, orderID uuid.UUID) (order.Snapshot, error)) *MockOrderGetter_Snapshot_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOrderShipper creates a new instance of MockOrderShipper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderShipper(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderShipper {
	mock := &MockOrderShipper{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOrderShipper is an autogenerated mock type for the OrderShipper type
type MockOrderShipper struct {
	mock.Mock
}

type MockOrderShipper_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderShipper) EXPECT() *MockOrderShipper_Expecter {
	return &MockOrderShipper_Expecter{mock: &_m.Mock}
}

// MarkShipped provides a mock function for the type MockOrderShipper
func (_mock *MockOrderShipper) MarkShipped(ctx context.Context, orderID uuid.UUID) error {
	ret := _mock.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for MarkShipped")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, orderID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOrderShipper_MarkShipped_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkShipped'
type MockOrderShipper_MarkShipped_Call struct {
	*mock.Call
}

// MarkShipped is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID uuid.UUID
func (_e *MockOrderShipper_Expecter) MarkShipped(ctx any, orderID any) *MockOrderShipper_MarkShipped_Call {
	return &MockOrderShipper_MarkShipped_Call{Call: _e.mock.On("MarkShipped", ctx, orderID)}
}

func (_c *MockOrderShipper_MarkShipped_Call) Run(run func(ctx context.Context, orderID uuid.UUID)) *MockOrderShipper_MarkShipped_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderShipper_MarkShipped_Call) Return(err error) *MockOrderShipper_MarkShipped_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOrderShipper_MarkShipped_Call) RunAndReturn(run func(ctx context.Context, orderID uuid.UUID) error) *MockOrderShipper_MarkShipped_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOrderDeliverer creates a new instance of MockOrderDeliverer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderDeliverer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderDeliverer {
	mock := &MockOrderDeliverer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOrderDeliverer is an autogenerated mock type for the OrderDeliverer type
type MockOrderDeliverer struct {
	mock.Mock
}

type MockOrderDeliverer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderDeliverer) EXPECT() *MockOrderDeliverer_Expecter {
	return &MockOrderDeliverer_Expecter{mock: &_m.Mock}
}

// MarkDelivered provides a mock function for the type MockOrderDeliverer
func (_mock *MockOrderDeliverer) MarkDelivered(ctx context.Context, orderID uuid.UUID) error {
	ret := _mock.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for MarkDelivered")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, orderID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOrderDeliverer_MarkDelivered_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkDelivered'
type MockOrderDeliverer_MarkDelivered_Call struct {
	*mock.Call
}

// MarkDelivered is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID uuid.UUID
func (_e *MockOrderDeliverer_Expecter) MarkDelivered(ctx any, orderID any) *MockOrderDeliverer_MarkDelivered_Call {
	return &MockOrderDeliverer_MarkDelivered_Call{Call: _e.mock.On("MarkDelivered", ctx, orderID)}
}

func (_c *MockOrderDeliverer_MarkDelivered_Call) Run(run func(ctx context.Context, orderID uuid.UUID)) *MockOrderDeliverer_MarkDelivered_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderDeliverer_MarkDelivered_Call) Return(err error) *MockOrderDeliverer_MarkDelivered_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOrderDeliverer_MarkDelivered_Call) RunAndReturn(run func(ctx context.Context, orderID uuid.UUID) error) *MockOrderDeliverer_MarkDelivered_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockRepository
func (_mock *MockRepository) Create(ctx context.Context, shipment *domain.Shipment) error {
	ret := _mock.Called(ctx, shipment)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Shipment) error); ok {
		r0 = returnFunc(ctx, shipment)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - shipment *domain.Shipment
func (_e *MockRepository_Expecter) Create(ctx any, shipment any) *MockRepository_Create_Call {
	return &MockRepository_Create_Call{Call: _e.mock.On("Create", ctx, shipment)}
}

func (_c *MockRepository_Create_Call) Run(run func(ctx context.Context, shipment *domain.Shipment)) *MockRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Shipment
		if args[1] != nil {
			arg1 = args[1].(*domain.Shipment)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Create_Call) Return(err error) *MockRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Create_Call) RunAndReturn(run func(ctx context.Context, shipment *domain.Shipment) error) *MockRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockRepository
func (_mock *MockRepository) GetByID(ctx context.Context, id uuid.UUID) (*domain.Shipment, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Shipment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Shipment, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Shipment); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Shipment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockRepository_Expecter) GetByID(ctx any, id any) *MockRepository_GetByID_Call {
	return &MockRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetByID_Call) Return(shipment *domain.Shipment, err error) *MockRepository_GetByID_Call {
	_c.Call.Return(shipment, err)
	return _c
}

func (_c *MockRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*domain.Shipment, error)) *MockRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByOrderID provides a mock function for the type MockRepository
func (_mock *MockRepository) GetByOrderID(ctx context.Context, orderID uuid.UUID) (*domain.Shipment, error) {
	ret := _mock.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for GetByOrderID")
	}

	var r0 *domain.Shipment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Shipment, error)); ok {
		return returnFunc(ctx, orderID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Shipment); ok {
		r0 = returnFunc(ctx, orderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Shipment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, orderID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetByOrderID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByOrderID'
type MockRepository_GetByOrderID_Call struct {
	*mock.Call
}

// GetByOrderID is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID uuid.UUID
func (_e *MockRepository_Expecter) GetByOrderID(ctx any, orderID any) *MockRepository_GetByOrderID_Call {
	return &MockRepository_GetByOrderID_Call{Call: _e.mock.On("GetByOrderID", ctx, orderID)}
}

func (_c *MockRepository_GetByOrderID_Call) Run(run func(ctx context.Context, orderID uuid.UUID)) *MockRepository_GetByOrderID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetByOrderID_Call) Return(shipment *domain.Shipment, err error) *MockRepository_GetByOrderID_Call {
	_c.Call.Return(shipment, err)
	return _c
}

func (_c *MockRepository_GetByOrderID_Call) RunAndReturn(run func(ctx context.Context, orderID uuid.UUID) (*domain.Shipment, error)) *MockRepository_GetByOrderID_Call {
	_c.Call.Return(run)
	return _c
}

// MarkDelivered provides a mock function for the type MockRepository
func (_mock *MockRepository) MarkDelivered(ctx context.Context, id uuid.UUID) (*domain.Shipment, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for MarkDelivered")
	}

	var r0 *domain.Shipment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Shipment, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Shipment); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Shipment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_MarkDelivered_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkDelivered'
type MockRepository_MarkDelivered_Call struct {
	*mock.Call
}

// MarkDelivered is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockRepository_Expecter) MarkDelivered(ctx any, id any) *MockRepository_MarkDelivered_Call {
	return &MockRepository_MarkDelivered_Call{Call: _e.mock.On("MarkDelivered", ctx, id)}
}

func (_c *MockRepository_MarkDelivered_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockRepository_MarkDelivered_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_MarkDelivered_Call) Return(shipment *domain.Shipment, err error) *MockRepository_MarkDelivered_Call {
	_c.Call.Return(shipment, err)
	return _c
}

func (_c *MockRepository_MarkDelivered_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*domain.Shipment, error)) *MockRepository_MarkDelivered_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockRepository
func (_mock *MockRepository) Update(ctx context.Context, shipment *domain.Shipment) error {
	ret := _mock.Called(ctx, shipment)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Shipment) error); ok {
		r0 = returnFunc(ctx, shipment)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - shipment *domain.Shipment
func (_e *MockRepository_Expecter) Update(ctx any, shipment any) *MockRepository_Update_Call {
	return &MockRepository_Update_Call{Call: _e.mock.On("Update", ctx, shipment)}
}

func (_c *MockRepository_Update_Call) Run(run func(ctx context.Context, shipment *domain.Shipment)) *MockRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Shipment
		if args[1] != nil {
			arg1 = args[1].(*domain.Shipment)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Update_Call) Return(err error) *MockRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Update_Call) RunAndReturn(run func(ctx context.Context, shipment *domain.Shipment) error) *MockRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
