// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	"github.com/residwi/go-api-project-template/internal/features/product"
	mock "github.com/stretchr/testify/mock"
)

// NewMockInventoryReader creates a new instance of MockInventoryReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInventoryReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInventoryReader {
	mock := &MockInventoryReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockInventoryReader is an autogenerated mock type for the InventoryReader type
type MockInventoryReader struct {
	mock.Mock
}

type MockInventoryReader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInventoryReader) EXPECT() *MockInventoryReader_Expecter {
	return &MockInventoryReader_Expecter{mock: &_m.Mock}
}

// GetAvailability provides a mock function for the type MockInventoryReader
func (_mock *MockInventoryReader) GetAvailability(ctx context.Context, ids []uuid.UUID) (map[uuid.UUID]product.Availability, error) {
	ret := _mock.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for GetAvailability")
	}

	var r0 map[uuid.UUID]product.Availability
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID) (map[uuid.UUID]product.Availability, error)); ok {
		return returnFunc(ctx, ids)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID) map[uuid.UUID]product.Availability); ok {
		r0 = returnFunc(ctx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[uuid.UUID]product.Availability)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []uuid.UUID) error); ok {
		r1 = returnFunc(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockInventoryReader_GetAvailability_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAvailability'
type MockInventoryReader_GetAvailability_Call struct {
	*mock.Call
}

// GetAvailability is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []uuid.UUID
func (_e *MockInventoryReader_Expecter) GetAvailability(ctx any, ids any) *MockInventoryReader_GetAvailability_Call {
	return &MockInventoryReader_GetAvailability_Call{Call: _e.mock.On("GetAvailability", ctx, ids)}
}

func (_c *MockInventoryReader_GetAvailability_Call) Run(run func(ctx context.Context, ids []uuid.UUID)) *MockInventoryReader_GetAvailability_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []uuid.UUID
		if args[1] != nil {
			arg1 = args[1].([]uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockInventoryReader_GetAvailability_Call) Return(uUIDToAvailability map[uuid.UUID]product.Availability, err error) *MockInventoryReader_GetAvailability_Call {
	_c.Call.Return(uUIDToAvailability, err)
	return _c
}

func (_c *MockInventoryReader_GetAvailability_Call) RunAndReturn(run func(ctx context.Context, ids []uuid.UUID) (map[uuid.UUID]product.Availability, error)) *MockInventoryReader_GetAvailability_Call {
	_c.Call.Return(run)
	return _c
}
