// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package query

import (
	"context"

	"github.com/google/uuid"
	"github.com/residwi/go-api-project-template/internal/modules/inventory/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// GetLevels provides a mock function for the type MockRepository
func (_mock *MockRepository) GetLevels(ctx context.Context, ids []uuid.UUID) (map[uuid.UUID]domain.Stock, error) {
	ret := _mock.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for GetLevels")
	}

	var r0 map[uuid.UUID]domain.Stock
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID) (map[uuid.UUID]domain.Stock, error)); ok {
		return returnFunc(ctx, ids)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID) map[uuid.UUID]domain.Stock); ok {
		r0 = returnFunc(ctx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[uuid.UUID]domain.Stock)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []uuid.UUID) error); ok {
		r1 = returnFunc(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetLevels_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLevels'
type MockRepository_GetLevels_Call struct {
	*mock.Call
}

// GetLevels is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []uuid.UUID
func (_e *MockRepository_Expecter) GetLevels(ctx any, ids any) *MockRepository_GetLevels_Call {
	return &MockRepository_GetLevels_Call{Call: _e.mock.On("GetLevels", ctx, ids)}
}

func (_c *MockRepository_GetLevels_Call) Run(run func(ctx context.Context, ids []uuid.UUID)) *MockRepository_GetLevels_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []uuid.UUID
		if args[1] != nil {
			arg1 = args[1].([]uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetLevels_Call) Return(uUIDToStock map[uuid.UUID]domain.Stock, err error) *MockRepository_GetLevels_Call {
	_c.Call.Return(uUIDToStock, err)
	return _c
}

func (_c *MockRepository_GetLevels_Call) RunAndReturn(run func(ctx context.Context, ids []uuid.UUID) (map[uuid.UUID]domain.Stock, error)) *MockRepository_GetLevels_Call {
	_c.Call.Return(run)
	return _c
}

// GetStock provides a mock function for the type MockRepository
func (_mock *MockRepository) GetStock(ctx context.Context, productID uuid.UUID) (*domain.Stock, error) {
	ret := _mock.Called(ctx, productID)

	if len(ret) == 0 {
		panic("no return value specified for GetStock")
	}

	var r0 *domain.Stock
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Stock, error)); ok {
		return returnFunc(ctx, productID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Stock); ok {
		r0 = returnFunc(ctx, productID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Stock)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, productID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetStock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStock'
type MockRepository_GetStock_Call struct {
	*mock.Call
}

// GetStock is a helper method to define mock.On call
//   - ctx context.Context
//   - productID uuid.UUID
func (_e *MockRepository_Expecter) GetStock(ctx any, productID any) *MockRepository_GetStock_Call {
	return &MockRepository_GetStock_Call{Call: _e.mock.On("GetStock", ctx, productID)}
}

func (_c *MockRepository_GetStock_Call) Run(run func(ctx context.Context, productID uuid.UUID)) *MockRepository_GetStock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetStock_Call) Return(stock *domain.Stock, err error) *MockRepository_GetStock_Call {
	_c.Call.Return(stock, err)
	return _c
}

func (_c *MockRepository_GetStock_Call) RunAndReturn(run func(ctx context.Context, productID uuid.UUID) (*domain.Stock, error)) *MockRepository_GetStock_Call {
	_c.Call.Return(run)
	return _c
}
