// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package http

import (
	"context"

	"github.com/google/uuid"
	"github.com/residwi/go-api-project-template/internal/modules/order/usecase/place"
	mock "github.com/stretchr/testify/mock"
)

// NewMockOrderPlacer creates a new instance of MockOrderPlacer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderPlacer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderPlacer {
	mock := &MockOrderPlacer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOrderPlacer is an autogenerated mock type for the OrderPlacer type
type MockOrderPlacer struct {
	mock.Mock
}

type MockOrderPlacer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderPlacer) EXPECT() *MockOrderPlacer_Expecter {
	return &MockOrderPlacer_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type MockOrderPlacer
func (_mock *MockOrderPlacer) Execute(ctx context.Context, userID uuid.UUID, p place.Params, idempotencyKey string) (*place.Result, error) {
	ret := _mock.Called(ctx, userID, p, idempotencyKey)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *place.Result
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, place.Params, string) (*place.Result, error)); ok {
		return returnFunc(ctx, userID, p, idempotencyKey)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, place.Params, string) *place.Result); ok {
		r0 = returnFunc(ctx, userID, p, idempotencyKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*place.Result)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, place.Params, string) error); ok {
		r1 = returnFunc(ctx, userID, p, idempotencyKey)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderPlacer_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockOrderPlacer_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - p place.Params
//   - idempotencyKey string
func (_e *MockOrderPlacer_Expecter) Execute(ctx any, userID any, p any, idempotencyKey any) *MockOrderPlacer_Execute_Call {
	return &MockOrderPlacer_Execute_Call{Call: _e.mock.On("Execute", ctx, userID, p, idempotencyKey)}
}

func (_c *MockOrderPlacer_Execute_Call) Run(run func(ctx context.Context, userID uuid.UUID, p place.Params, idempotencyKey string)) *MockOrderPlacer_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 place.Params
		if args[2] != nil {
			arg2 = args[2].(place.Params)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockOrderPlacer_Execute_Call) Return(result *place.Result, err error) *MockOrderPlacer_Execute_Call {
	_c.Call.Return(result, err)
	return _c
}

func (_c *MockOrderPlacer_Execute_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, p place.Params, idempotencyKey string) (*place.Result, error)) *MockOrderPlacer_Execute_Call {
	_c.Call.Return(run)
	return _c
}
