// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package create

import (
	"context"

	"github.com/google/uuid"
	"github.com/residwi/go-api-project-template/internal/modules/order/contract"
	"github.com/residwi/go-api-project-template/internal/modules/shipping/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockOrderGetter creates a new instance of MockOrderGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderGetter {
	mock := &MockOrderGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOrderGetter is an autogenerated mock type for the OrderGetter type
type MockOrderGetter struct {
	mock.Mock
}

type MockOrderGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderGetter) EXPECT() *MockOrderGetter_Expecter {
	return &MockOrderGetter_Expecter{mock: &_m.Mock}
}

// GetInfo provides a mock function for the type MockOrderGetter
func (_mock *MockOrderGetter) GetInfo(ctx context.Context, orderID uuid.UUID) (contract.Order, error) {
	ret := _mock.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for GetInfo")
	}

	var r0 contract.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (contract.Order, error)); ok {
		return returnFunc(ctx, orderID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) contract.Order); ok {
		r0 = returnFunc(ctx, orderID)
	} else {
		r0 = ret.Get(0).(contract.Order)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, orderID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderGetter_GetInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInfo'
type MockOrderGetter_GetInfo_Call struct {
	*mock.Call
}

// GetInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID uuid.UUID
func (_e *MockOrderGetter_Expecter) GetInfo(ctx any, orderID any) *MockOrderGetter_GetInfo_Call {
	return &MockOrderGetter_GetInfo_Call{Call: _e.mock.On("GetInfo", ctx, orderID)}
}

func (_c *MockOrderGetter_GetInfo_Call) Run(run func(ctx context.Context, orderID uuid.UUID)) *MockOrderGetter_GetInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderGetter_GetInfo_Call) Return(order contract.Order, err error) *MockOrderGetter_GetInfo_Call {
	_c.Call.Return(order, err)
	return _c
}

func (_c *MockOrderGetter_GetInfo_Call) RunAndReturn(run func(ctx context.Context, orderID uuid.UUID) (contract.Order, error)) *MockOrderGetter_GetInfo_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOrderShipper creates a new instance of MockOrderShipper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderShipper(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderShipper {
	mock := &MockOrderShipper{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOrderShipper is an autogenerated mock type for the OrderShipper type
type MockOrderShipper struct {
	mock.Mock
}

type MockOrderShipper_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderShipper) EXPECT() *MockOrderShipper_Expecter {
	return &MockOrderShipper_Expecter{mock: &_m.Mock}
}

// MarkShipped provides a mock function for the type MockOrderShipper
func (_mock *MockOrderShipper) MarkShipped(ctx context.Context, orderID uuid.UUID) error {
	ret := _mock.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for MarkShipped")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, orderID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOrderShipper_MarkShipped_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkShipped'
type MockOrderShipper_MarkShipped_Call struct {
	*mock.Call
}

// MarkShipped is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID uuid.UUID
func (_e *MockOrderShipper_Expecter) MarkShipped(ctx any, orderID any) *MockOrderShipper_MarkShipped_Call {
	return &MockOrderShipper_MarkShipped_Call{Call: _e.mock.On("MarkShipped", ctx, orderID)}
}

func (_c *MockOrderShipper_MarkShipped_Call) Run(run func(ctx context.Context, orderID uuid.UUID)) *MockOrderShipper_MarkShipped_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderShipper_MarkShipped_Call) Return(err error) *MockOrderShipper_MarkShipped_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOrderShipper_MarkShipped_Call) RunAndReturn(run func(ctx context.Context, orderID uuid.UUID) error) *MockOrderShipper_MarkShipped_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockRepository
func (_mock *MockRepository) Create(ctx context.Context, shipment *domain.Shipment) error {
	ret := _mock.Called(ctx, shipment)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Shipment) error); ok {
		r0 = returnFunc(ctx, shipment)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - shipment *domain.Shipment
func (_e *MockRepository_Expecter) Create(ctx any, shipment any) *MockRepository_Create_Call {
	return &MockRepository_Create_Call{Call: _e.mock.On("Create", ctx, shipment)}
}

func (_c *MockRepository_Create_Call) Run(run func(ctx context.Context, shipment *domain.Shipment)) *MockRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Shipment
		if args[1] != nil {
			arg1 = args[1].(*domain.Shipment)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Create_Call) Return(err error) *MockRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Create_Call) RunAndReturn(run func(ctx context.Context, shipment *domain.Shipment) error) *MockRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}
